/**
 * The content the CMS is seeded with: a developer knowledge base for this stack.
 *
 * Kept separate from seed.ts so that file stays readable as the *mechanism* —
 * find-or-create, API keys, media uploads — while this one is purely *data*.
 *
 * ── The mini-format in `body` ─────────────────────────────────────────────
 *
 * Each entry is one block. A tiny markdown subset is parsed by `richText()` in
 * seed.ts into real Lexical nodes:
 *
 *   "## Text"    → heading (h2)
 *   "### Text"   → heading (h3)
 *   "- Text"     → bulleted list item (consecutive ones merge into one list)
 *   "1. Text"    → numbered list item (likewise)
 *   "> Text"     → blockquote
 *   "---"        → horizontal rule
 *   anything else→ paragraph
 *
 * Inline `backticks` become Lexical's CODE format (bitmask 16) and **double
 * asterisks** become BOLD (bitmask 1).
 *
 * ⚠️ There is deliberately no fenced-code-block syntax. Lexical's `code` node is
 * not in the storefront renderer's switch (apps/storefront/src/lib/lexical.ts),
 * so a fenced block would render as an unstyled paragraph. Inline code is
 * supported and is what these guides use. Commands that need a real code block
 * live in docs/how-to/, which every guide links to.
 */

export type Guide = {
  title: string
  category: string
  status: 'published' | 'draft'
  excerpt: string
  tags: string[]
  /** Staggered so `sort: '-publishedAt'` is meaningful. See seed.ts. */
  publishedAt: string
  body: string[]
}

/**
 * Six categories, replacing the generic Architecture / Tutorials / Release
 * Notes. These map onto how someone actually looks for an answer: by the part of
 * the stack they are stuck in.
 */
export const categorySeeds = [
  {
    name: 'Getting Started',
    description: 'Orientation, project structure, and the commands you will type every day.',
  },
  {
    name: 'Content Modelling',
    description: 'Payload collections, fields, blocks, globals and relationships.',
  },
  {
    name: 'Frontend',
    description: 'Astro routing, pages, layouts, components and islands.',
  },
  {
    name: 'Commerce',
    description: 'Medusa products, payments, inventory and multi-store.',
  },
  {
    name: 'Data & APIs',
    description: 'Reading, writing and deleting across two backends over HTTP.',
  },
  {
    name: 'Operations & Tooling',
    description: 'Databases, backups, monitoring, editors and the things that keep it running.',
  },
] as const

/** Base date; each guide is offset by an hour so ordering is stable. */
const DAY = '2026-09-15'

const at = (hoursFromStart: number) => {
  const base = new Date(`${DAY}T08:00:00.000Z`).getTime()
  return new Date(base + hoursFromStart * 3_600_000).toISOString()
}

export const guideSeeds: Guide[] = [
  // ── Getting Started ───────────────────────────────────────────────────────
  {
    title: 'What is the wp-config.php equivalent in this stack?',
    category: 'Getting Started',
    status: 'published',
    excerpt:
      'There is no single config file. Configuration is split three ways, and two of the three are code rather than settings.',
    tags: ['config', 'env', 'wordpress'],
    publishedAt: at(0),
    body: [
      'In WordPress, `wp-config.php` is the one file that holds database credentials, salts, debug flags and anything else you bolt on. There is exactly one, it sits at the web root, and everything reads from it.',
      'This stack has no such file, and looking for one is the first thing that goes wrong. Configuration is split across three apps, and it is split by *kind* as well as by app.',
      '## The three kinds of configuration',
      'Each app separates secrets from structure, which WordPress never did.',
      '- **Secrets and environment** live in a `.env` file — one per app. This is the part that genuinely maps to `wp-config.php`.',
      '- **Structure** lives in a TypeScript config file that is read at boot: `payload.config.ts`, `medusa-config.ts`, `astro.config.mjs`. There is no WordPress equivalent, because WordPress discovers plugins and post types at runtime.',
      '- **Per-app tooling** lives in `package.json` and `tsconfig.json`.',
      '## Where each one lives',
      '- `apps/cms/.env` plus `apps/cms/src/payload.config.ts`',
      '- `apps/commerce/.env` plus `apps/commerce/medusa-config.ts`',
      '- `apps/storefront/.env` plus `apps/storefront/astro.config.mjs`',
      'There is **no root `.env`**. Each app is a separate npm project with its own dependencies and its own deploy, so each carries its own environment.',
      '## The part that surprises people',
      'In WordPress, registering a post type is a function call that runs on every request. Here, the equivalent is a declaration in `payload.config.ts` that is read **once at boot** and diffed against the database. That is why adding a collection requires a restart, and why nothing can register one at runtime.',
      '> The trade: you lose runtime flexibility, and you gain a schema that is in version control and cannot drift.',
      'Each `.env` has a committed `.env.example` beside it listing the keys with dummy values. `.env` itself is gitignored.',
      '## Going deeper',
      'The file structure guide covers every directory, and the operations chapter covers which two keys are regenerated when you reset the database.',
    ],
  },
  {
    title: 'The file structure of a Payload, Medusa and Astro project',
    category: 'Getting Started',
    status: 'published',
    excerpt:
      'Three npm projects in one repository, two databases, and three .env files. Here is what lives where and why.',
    tags: ['structure', 'monorepo', 'env'],
    publishedAt: at(1),
    body: [
      'A WordPress install is one tree: `wp-content/themes` for presentation, `wp-content/plugins` for behaviour, `wp-admin` and `wp-includes` for core. One codebase, one deploy.',
      'This repository holds three independent applications that happen to live beside each other.',
      '## The top level',
      '- `apps/cms` — Payload 3, running inside Next.js, on port 3000',
      '- `apps/commerce` — Medusa 2, on port 9000',
      '- `apps/storefront` — Astro 7, on port 4321',
      '- `infra` — the Docker Compose file for Postgres and Redis',
      '- `scripts` — setup, backup and restore shell scripts',
      '- `docs` — three documentation tracks',
      'The root `package.json` holds **no dependencies**. It exists only to orchestrate: `npm run dev` starts all three, `npm run typecheck` checks all three.',
      '## Why three node_modules',
      'Because they have genuinely different dependency trees and genuinely different deploy targets. Payload needs Next. Medusa needs its own framework. Astro needs neither. A single workspace would force their versions to agree, and they do not.',
      '## There are three .env files, and no root one',
      'This is the question everyone asks, and the answer is three.',
      '- `apps/cms/.env` — `DATABASE_URL`, `PAYLOAD_SECRET`',
      '- `apps/commerce/.env` — `DATABASE_URL`, `JWT_SECRET`, `COOKIE_SECRET`, `REDIS_URL`, CORS settings',
      '- `apps/storefront/.env` — `PAYLOAD_URL`, `MEDUSA_URL`, and the two API keys',
      'Note that the two `DATABASE_URL` values point at **different databases** on the same Postgres server: `payload_crud` and `medusa_crud`. Neither app can see the other\'s tables, and no query can join across them.',
      '## The two generated keys',
      '`PAYLOAD_API_KEY` and `MEDUSA_PUBLISHABLE_KEY` in the storefront\'s `.env` are generated during setup and stored **in the databases**. Reset the database and both become invalid — which is why `npm run setup` rewrites that file for you.',
      '## Going deeper',
      'The how-to track walks each app\'s tree directory by directory, including which parts Next owns inside the CMS app.',
    ],
  },
  {
    title: 'The terminal commands worth memorising',
    category: 'Getting Started',
    status: 'published',
    excerpt:
      'A working set of about a dozen commands, grouped by what you are actually doing, with the wp-cli equivalent where one exists.',
    tags: ['cli', 'npm', 'workflow'],
    publishedAt: at(2),
    body: [
      'WordPress development needs very few commands — mostly `wp-cli` and whatever your host gives you. Here the terminal is the primary interface, and there is no admin screen that restarts a service for you.',
      '## Every day',
      '- `npm run dev` — all three services, colour-coded in one terminal',
      '- `npm run dev:cms` — just one of them, when you want a quiet log',
      '- `npm run logs` — tail all three log files',
      '- `npm run logs:errors` — grep warnings and errors out of them',
      '## Database',
      '- `npm run db:up` — start Postgres and Redis in Docker and wait for health',
      '- `npm run db:psql` — a psql shell inside the container, no client install needed',
      '- `npm run db:export` — dump both databases plus a manifest',
      '- `npm run db:import` — restore, with checksum and migration-drift checks',
      '- `npm run db:reset` — **destroys the Docker volume.** Take a backup first.',
      '## After changing things',
      '- `npm run typecheck` — all three apps',
      '- `npm --prefix apps/cms run generate:types` — after editing a Payload field',
      '- `npm --prefix apps/commerce run db:generate` — after editing a Medusa model',
      '- `npm --prefix apps/commerce run db:migrate` — apply it',
      '## Testing',
      '- `npm test` — unit tests plus the compensation test',
      '- `npm run postman:test` — the full API collection through newman',
      '## The one that catches everyone',
      'Astro 7 **backgrounds its own dev server**. Pressing Ctrl-C on `npm run dev` does not stop it. From `apps/storefront`, run `npx astro dev stop`, and `npx astro dev status` to ask which port it actually took.',
      '> If the storefront is not on 4321, something else has the port and Astro silently moved to 4322.',
      '## Going deeper',
      'The how-to track has the full table grouped by task, with wp-cli equivalents side by side.',
    ],
  },
  {
    title: 'What is seeding, and when should you use it?',
    category: 'Getting Started',
    status: 'published',
    excerpt:
      'Seeding is sample content as code: versioned, repeatable, and run from the terminal rather than clicked through an importer.',
    tags: ['seeding', 'database', 'workflow'],
    publishedAt: at(3),
    body: [
      'Seeding means running a script that inserts a known set of starting data into an empty database, so that every developer — and every reset — lands in the same state.',
      '## The WordPress equivalent, and the difference',
      'The closest things you already know are a WXR import or WooCommerce\'s sample-products importer. Both put demo content in a fresh install.',
      'The difference is that those are **one-off actions you click**, while a seed is **code in your repository**. It is versioned alongside the schema it populates, it runs from the terminal, and it is reviewed like any other code.',
      '## What this project seeds',
      '- `apps/cms/src/scripts/seed.ts` — the admin user, an API key, categories, these guides, a block-built page and the site settings global',
      '- `apps/commerce/src/scripts/seed.ts` — region, currencies, sales channel, warehouse, shipping options, product categories, products and inventory',
      '- `apps/commerce/src/scripts/seed-reviews.ts` — reviews, created through the workflow rather than written directly',
      'That last point matters. The review seed calls `createReviewWorkflow`, not the service, because the workflow is what writes the cross-module link row. Inserting directly would produce reviews attached to nothing.',
      '## When to use it',
      '- Setting up a development machine',
      '- Continuous integration, where every run needs identical data',
      '- Demos, where you want the app to look populated',
      '- Immediately after `npm run db:reset`',
      '## When not to use it',
      '- **Production content.** Seeds are sample data, not a content management strategy.',
      '- **Anything with real customer data.**',
      '- **As a migration mechanism.** Changing a table\'s shape is `db:migrate`. Seeds fill tables; migrations change them.',
      '## Idempotency is a design decision',
      'A seed can skip what already exists, or it can delete and rewrite. This project\'s Payload seed does both: it clears the content it owns, then writes it fresh, so you can re-run it without ending up with duplicates.',
      '> Medusa\'s seed is different — it is unguarded, so running it twice throws a unique-constraint violation on a product handle. That is why the documented path is a reset.',
      '## Going deeper',
      'The stack guide covers how to re-seed without duplicating everything, and what the two generated API keys have to do with it.',
    ],
  },
  {
    title: 'How to run this stack locally from a cold clone',
    category: 'Getting Started',
    status: 'published',
    excerpt:
      'Four commands, in order, and the two things that go wrong if you run them out of order.',
    tags: ['setup', 'docker', 'cli'],
    publishedAt: at(4),
    body: [
      'Unlike a WordPress install, there is no five-minute web installer. There is a sequence of terminal commands, and the order matters.',
      '## The sequence',
      '1. `npm run install:all` — installs dependencies in all three apps',
      '2. `npm run db:up` — starts Postgres and Redis and waits until both report healthy',
      '3. `npm run setup` — creates schemas, seeds content, generates both API keys and writes them into the storefront `.env`',
      '4. `npm run dev` — starts all three services',
      'Then open the storefront on port 4321. If the two service cards at the top of the dashboard say **reachable**, you are done.',
      '## What setup actually does',
      'It is idempotent, so running it again is safe. It pushes the Payload schema, runs Medusa migrations, seeds both databases, creates the Medusa admin user, and — the part that matters — captures the two generated keys and writes them into `apps/storefront/.env`.',
      'Doing those steps by hand is possible but easy to get wrong, because the keys are generated mid-sequence and the storefront cannot talk to either backend without them.',
      '## The two things that go wrong',
      '**Running the seed before the database is up.** The Payload seed reads `DATABASE_URL` at module-evaluation time, before the script body runs. If Postgres is not listening you get a connection error rather than a helpful message.',
      '**A stale Astro dev server.** Astro backgrounds itself, so a previous run may still hold port 4321 even after you closed the terminal. Check with `npx astro dev status` from `apps/storefront`.',
      '## Credentials',
      'Both admin panels use the same development login: `admin@local.test` with the password `supersecret`. The CMS admin is on port 3000, the commerce admin on 9000.',
      '## Going deeper',
      'The infrastructure chapter covers the Docker Compose file line by line, and the recovery ladder for when something is wedged.',
    ],
  },

  // ── Content Modelling ─────────────────────────────────────────────────────
  {
    title: 'What are Payload CMS collections?',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'A collection is the closest thing to a custom post type — except the config is the schema, and it builds the API, the admin UI and the types too.',
    tags: ['payload', 'collections', 'wordpress'],
    publishedAt: at(5),
    body: [
      'A **collection** is a type of document that Payload stores, manages and exposes. If you know WordPress, start from `register_post_type()` — that is the nearest idea.',
      '## What one collection gives you',
      'Declaring a collection in a single TypeScript file produces, with no further work:',
      '- Postgres tables matching the field list',
      '- A full REST API, with filtering, sorting, pagination and depth',
      '- A GraphQL API',
      '- Generated TypeScript types',
      '- An admin UI with forms, validation and list views',
      '- Access-control hooks for each of create, read, update and delete',
      'WordPress gives you the admin UI and a post type; the REST shape is generic and the fields need a plugin like ACF.',
      '## The collections here',
      'This project has five: `users`, `media`, `categories`, `posts` and `pages`. Every one is a file in `apps/cms/src/collections/` plus one entry in the `collections` array in `payload.config.ts`.',
      '## The big difference from register_post_type',
      '`register_post_type()` runs on the `init` hook, on **every request**, and any plugin can call it. Payload reads its `collections` array **once at boot** and compares it to the database.',
      '> That is why adding a collection needs a restart, and why no plugin can inject one at runtime.',
      'What you gain is that the schema is in version control. What you lose is runtime registration — there is no equivalent of a plugin adding a post type after the fact.',
      '## Fields are columns, not meta',
      'Another real difference. ACF stores every field as a row in `wp_postmeta`, keyed by name, all values as strings. A Payload field becomes a **typed column** — or, for arrays and blocks, its own table.',
      'So five collections here produce twenty-one tables. Relationships become foreign keys, arrays become child tables, and the database enforces shape rather than trusting the application.',
      '## Going deeper',
      'The content guide walks through creating one end to end, and the databases chapter explains exactly how five declarations became twenty-one tables.',
    ],
  },
  {
    title: 'How to create a new post type in Payload CMS',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'One file, one line in the config, and a restart. The equivalent of register_post_type, except the schema comes with it.',
    tags: ['payload', 'collections', 'tutorial'],
    publishedAt: at(6),
    body: [
      'In WordPress you call `register_post_type()` from a plugin or `functions.php`, then usually add ACF field groups to make it useful. Here it is one file.',
      '## The steps',
      '1. Create a file in `apps/cms/src/collections/`, for example `Testimonials.ts`, exporting a `CollectionConfig`.',
      '2. Give it a `slug`, an `admin.useAsTitle`, an `access` block and a `fields` array.',
      '3. Import it in `apps/cms/src/payload.config.ts` and add it to the `collections` array.',
      '4. **Restart the CMS.** The config is read at boot and is not hot-reloaded.',
      '5. Run `npm --prefix apps/cms run generate:types` to refresh `payload-types.ts`.',
      '## What to copy',
      'The smallest useful example in this repo is `Categories.ts` — a title field, a slug with a `beforeValidate` hook that derives it, and a description. It is about forty lines including comments.',
      '## What happens when you restart',
      'In development, Payload is running in `push` mode. It compares your config to the live database and applies the difference automatically — creating the table, its columns, its indexes and any relationship tables.',
      'You can watch it happen by counting tables in `payload_crud` before and after.',
      '> In production you would turn `push` off and use migration files instead, so that schema changes are reviewed and reversible.',
      '## The gotcha that costs an hour',
      '**A new collection 404s until you restart.** Editing a collection file hot-reloads fine, but adding one to the config array does not. The REST route simply does not exist yet, and the error gives no hint that a restart is what you need.',
      '## Slugs are not free',
      'If you add a `slug` field, make it `unique: true` and `index: true`, and derive it with the shared `slugFrom()` hook in `apps/cms/src/hooks/slugify.ts`. That hook only fills a slug when one is absent, so a hand-typed slug is never silently overwritten.',
      '## Going deeper',
      'The content guide has the full walkthrough with the before-and-after table counts.',
    ],
  },
  {
    title: 'How to add a custom field to posts',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'The ACF question. A field is a line of TypeScript, and it becomes a real column rather than a row in a meta table.',
    tags: ['payload', 'fields', 'acf'],
    publishedAt: at(7),
    body: [
      'With ACF you create a field group in the admin, bind it to a post type with location rules, and read it with `get_field()`. The value lands in `wp_postmeta` as a string.',
      'Here you add an object to the `fields` array in `apps/cms/src/collections/Posts.ts`, and it becomes a typed column.',
      '## The steps',
      '1. Open `apps/cms/src/collections/Posts.ts` and find the `fields` array.',
      '2. Add a field object with at least a `name` and a `type`.',
      '3. Save. The dev server hot-reloads and `push` mode applies the column.',
      '4. Run `npm --prefix apps/cms run generate:types`.',
      '5. The field appears in the admin, in the REST response and in the TypeScript types.',
      '## The field types you will use most',
      '- `text` — ACF Text',
      '- `textarea` — ACF Textarea',
      '- `number` — ACF Number',
      '- `select` with `options` — ACF Select',
      '- `checkbox` — ACF True/False',
      '- `date` — ACF Date Picker',
      '- `richText` — the WYSIWYG, but stored as a tree rather than HTML',
      '- `relationship` — ACF Relationship or Post Object',
      '- `upload` — ACF Image or File',
      '- `array` — ACF Repeater',
      '- `blocks` — ACF Flexible Content',
      '- `group` — ACF Group',
      '## Where it goes in the database',
      'Simple fields become columns on the `posts` table. An `array` field becomes **its own table** with a foreign key back to the post and an `_order` column. A `blocks` field becomes one table per block type.',
      '> This is the real difference from ACF. There is no key-value side table, so a field that is not in the config has nowhere to live — and orphaned meta from a plugin you removed years ago is not a thing that can happen.',
      '## Two useful admin options',
      '`admin: { position: \'sidebar\' }` moves a field out of the main editing column, and `admin: { description: \'…\' }` adds help text under the input.',
      '## Going deeper',
      'The content guide shows the column appearing in psql before and after, and the databases chapter covers the array and block tables.',
    ],
  },
  {
    title: 'How to create a custom block and reuse it',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'The closest thing to ACF Flexible Content. Editors choose sections and order them; you own the markup each one renders.',
    tags: ['payload', 'blocks', 'elementor'],
    publishedAt: at(8),
    body: [
      'If you build pages with Elementor or ACF Flexible Content, this is the idea you already have: an editor assembles a page from a set of approved sections, in any order, as many times as they like.',
      'The closest equivalent is **ACF Flexible Content**, not Gutenberg.',
      '## How it works here',
      'A `blocks` field holds a list of block instances. Each block type is declared with a `slug` and its own `fields` array. `apps/cms/src/collections/Pages.ts` declares three: `hero`, `prose` and `stats`.',
      '## The steps',
      '1. Add a block object to the `blocks` array in the field config, with a `slug` and `fields`.',
      '2. Restart or let it hot-reload; `push` creates a table named after the block.',
      '3. In the admin, open a page, click **Add block** and pick the new type.',
      '4. In Astro, render it — see below.',
      '## The part that differs from Elementor',
      'Elementor composes in a visual builder and stores a JSON blob describing the layout, including styling. Here the editor picks **which** blocks and in **what order**, but a developer writes the component that renders each one.',
      '> The editor controls structure. You control markup. Nobody can inject a `<div>` soup into your templates, and nobody can change your CSS from the admin.',
      'The rendering lives in `apps/storefront/src/pages/pages/[slug].astro`, which loops the `layout` array and switches on `blockType`.',
      '## Reusable in which sense?',
      'A block type is reusable in that an editor can insert it any number of times, on any document with a `blocks` field. That covers most of what people mean.',
      'What it does **not** give you is one piece of content edited once and shown everywhere — a shared call-to-action, say. For that you want a **global**: exactly one record, no list view. The site settings global in this project is the live example, and its announcement banner renders on every page.',
      '## Going deeper',
      'The content guide covers both, including when to reach for a global instead of a block.',
    ],
  },
  {
    title: 'How to use field relationships and the depth parameter',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'Relationships are foreign keys, and depth controls how far Payload expands them. There is no WordPress equivalent for depth.',
    tags: ['payload', 'relationships', 'depth'],
    publishedAt: at(9),
    body: [
      'A `relationship` field links one document to another. In ACF terms it is the Relationship or Post Object field; in database terms it is a real foreign key, not a serialised post ID in a meta row.',
      '## Declaring one',
      'The `category` field on `posts` is the example in this project: `type: \'relationship\'` with `relationTo: \'categories\'`. Adding `hasMany: true` makes it a list, which becomes a join table.',
      '## Depth is the part with no WordPress analogue',
      'When you read a document, Payload has to decide whether a relationship comes back as an ID or as the whole related document. `depth` is that control.',
      '- `depth=0` — `category: 3`. Just the ID. One query.',
      '- `depth=1` — `category: { id: 3, name: "Frontend", slug: "frontend" }`. The document, joined.',
      '- `depth=2` — also expands relationships **inside** the category.',
      'The default is 2, which is usually more than you need.',
      '## How to choose',
      '- Use `depth=0` when you only need the ID — building a filter, or checking which category something is in. It is the cheapest read.',
      '- Use `depth=1` when you are rendering and need the related document\'s fields, such as showing a category name on a post card.',
      '- Use `depth=2` or higher only when you genuinely need a relationship of a relationship, and expect it to cost you.',
      '> Every level of depth is more joins and a larger response. On a list of fifty posts, the difference between depth 0 and depth 2 is substantial.',
      '## The upload field behaves the same way',
      '`coverImage` is an `upload` relationship to the `media` collection. At `depth=0` you get the media ID; at `depth=1` you get the document including `url` and the generated `thumbnail` and `card` sizes. Rendering an image therefore needs at least depth 1.',
      '## A practical default',
      'This project\'s post list uses `depth: 1` and the single post page uses the same. Nothing needs more.',
      '## Going deeper',
      'The data guide has a section on choosing depth, with the response sizes side by side.',
    ],
  },
  {
    title: 'How to create a page and render it in Astro',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'In WordPress one act creates the content and its URL. Here they are two jobs in two services, and understanding that split is the whole lesson.',
    tags: ['payload', 'astro', 'pages'],
    publishedAt: at(10),
    body: [
      'This is the question where the stack feels most unfamiliar, because "create a page" means two different things.',
      'In WordPress, adding a page in the admin creates both the content **and** its URL. The rewrite layer and the template hierarchy take care of the rest.',
      'Here those are separate. Payload stores the content. Astro decides the URL and renders it. Neither knows about the other.',
      '## Part one — the content',
      '1. Open the CMS admin on port 3000 and choose **Pages**.',
      '2. Click **Create new**, give it a title, and leave the slug blank — it derives from the title.',
      '3. Add blocks to the `layout` field: a hero, some prose, a stats row.',
      '4. Save.',
      'You can do the same over the REST API with a POST to `/api/pages`, sending the `layout` array as JSON.',
      '## Part two — the URL',
      'The page is now in the database but no URL serves it until a route exists. In this project that route is already there: `apps/storefront/src/pages/pages/[slug].astro`.',
      'That one file serves **every** page document. The `[slug]` part is a parameter; the frontmatter reads it, fetches the matching document from Payload, and renders each block.',
      '> One file, any number of pages. You do not add a route per page, which is the thing that trips people up coming from a per-template mental model.',
      '## Why it is split this way',
      'Because the storefront is a separate application that reaches Payload over HTTP. It has no database access at all. That constraint is what lets you replace the frontend without touching the CMS, and serve the same content to a mobile app.',
      '## If nothing renders',
      'Check the slug matches, and check the document is **published** rather than draft. The read access rule narrows anonymous queries to published documents, so a draft is not hidden — it genuinely does not exist as far as an anonymous request is concerned.',
      '## Going deeper',
      'The content guide covers the Payload half and the frontend guide covers the routing half.',
    ],
  },
  {
    title: 'How to create a post in Payload CMS',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'Through the admin, or over the REST API with an API key. Both paths, and the header format that catches everyone.',
    tags: ['payload', 'posts', 'rest'],
    publishedAt: at(11),
    body: [
      'Posts are the collection you will touch most. Creating one works the way you expect; the API path has one surprise.',
      '## Through the admin',
      '1. Open port 3000, log in, choose **Posts**.',
      '2. Click **Create new**.',
      '3. Fill in the title. Leave the slug blank and it is derived.',
      '4. Write the body in the rich-text editor, choose a category, add tags.',
      '5. Use **Save draft** or **Publish** — the status control is in the sidebar.',
      '## Over the REST API',
      'POST to `/api/posts` with a JSON body. Only `title` is strictly required.',
      'The authentication header is the surprise:',
      '> `Authorization: users API-Key <key>` — the collection slug, then a literal space, then `API-Key`, then the key. **Not** `Bearer`.',
      'That format catches almost everyone once. A wrong header gives a 403 that looks like a permissions problem rather than a syntax problem.',
      '## Draft or published',
      'Send `"_status": "published"` to publish immediately; omit it and the `beforeChange` hook defaults the post to a draft. The same hook stamps `publishedAt` the first time a post actually goes live, and leaves it alone afterwards.',
      '## Field limits worth knowing',
      '- `title` — required, maximum 200 characters',
      '- `excerpt` — optional, maximum 300 characters',
      '- `slug` — unique and indexed, so two posts whose titles reduce to the same slug will collide',
      'That last one is a real constraint when you write a series of similarly-named guides.',
      '## Drafts keep versions',
      'The posts collection has `versions: { drafts: true, maxPerDoc: 10 }`, so every save writes a version row. That is why there is a `_posts_v` table alongside `posts`, and why the count in it grows faster than the post count.',
      '## Going deeper',
      'The content guide covers both paths with runnable commands, and the data guide covers reading posts back.',
    ],
  },
  {
    title: 'How to add user roles and control access',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'The Advanced Access Manager question. There is no capability registry here — access is four functions per collection, and one of them can return a query.',
    tags: ['payload', 'access', 'security'],
    publishedAt: at(12),
    body: [
      'In WordPress, roles are rows in `wp_options` holding capability maps, any plugin can add a capability at runtime, and you gate behaviour with `current_user_can()`. Plugins like Advanced Access Manager give you a UI over all of it.',
      'This stack has nothing resembling that, and the replacement is smaller and stricter.',
      '## Roles are a field',
      'The `users` collection has a `role` select field with two options, `admin` and `editor`. That list is TypeScript, not data — adding a third role is a code change and a deploy, not an admin screen.',
      '## Access is four functions',
      'Every collection declares `access` with up to four keys: `create`, `read`, `update` and `delete`. Each is a function receiving the request, returning either a boolean or — and this is the interesting part — a query.',
      'In this project, delete on posts is `req.user?.role === \'admin\'`. Straightforward.',
      '## The idea worth stealing',
      'A `read` function can return a **`Where` query** instead of true or false. Payload merges it into the SQL.',
      'The posts collection does exactly this: a logged-in user gets `true`, and anonymous gets `{ _status: { equals: \'published\' } }`.',
      '> Drafts are not *forbidden* to anonymous readers. They do not exist. The count comes back lower, pagination adjusts, and there is no 403 to leak that something was hidden.',
      'In WordPress the equivalent is combining `current_user_can()` with a `pre_get_posts` filter — two mechanisms, applied in two places, that can disagree. Here it is one function.',
      '## What you do not get',
      '- No capability registry, no `add_cap`, no per-user overrides',
      '- No role editor in the admin',
      '- No way for external code to grant itself access',
      'The unit of authorisation is an operation on a collection, and there are exactly four of them.',
      '## And a warning',
      'The **storefront has no authentication at all**. Anyone who can reach it can call any of its endpoints. Payload\'s access control protects Payload; it does not protect a frontend that holds an admin-capable API key.',
      '## Going deeper',
      'The Payload chapter covers access control in depth, and the production chapter covers the missing storefront auth.',
    ],
  },

  // ── Frontend ──────────────────────────────────────────────────────────────
  {
    title: 'How routing works in Astro',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'A file in src/pages is a URL, and nothing else is. No template hierarchy, no rewrite rules, no flushing.',
    tags: ['astro', 'routing', 'themes'],
    publishedAt: at(13),
    body: [
      'WordPress resolves a URL by running the main query and then walking the template hierarchy — `single-{post_type}-{slug}.php`, then `single-{post_type}.php`, then `single.php`, then `index.php`. It is a cascade you memorise, backed by rewrite rules you sometimes have to flush.',
      'Astro has none of that. **A file in `src/pages/` is a URL. Nothing else is.**',
      '## The mapping',
      '- `src/pages/index.astro` → `/`',
      '- `src/pages/posts/index.astro` → `/posts`',
      '- `src/pages/posts/[slug].astro` → `/posts/anything`',
      '- `src/pages/posts/[id]/edit.astro` → `/posts/123/edit`',
      '- `src/pages/api/health.ts` → `/api/health`',
      'Square brackets mark a parameter. Read it in the frontmatter with `Astro.params`.',
      '## What you gain and lose',
      'You gain that the routing table is a directory listing. There is no cascade to reason about and no cache to flush — add a file and the route exists.',
      'You lose the automatic fallbacks. Nothing serves `/posts/missing` unless your `[slug].astro` handles the not-found case itself.',
      '## The gotcha from tutorials',
      'Most Astro tutorials are written for static output and tell you to export `getStaticPaths()`. This project runs `output: \'server\'`, so routes are resolved per request and **`getStaticPaths` is not needed**. Copying it in from a tutorial causes confusing errors.',
      '## API routes live in the same tree',
      'A `.ts` file under `src/pages/api/` exporting `GET` or `POST` is an HTTP endpoint. Same routing rules — the file path is the URL. That is where this project\'s review endpoints live.',
      '## Middleware runs first',
      '`src/middleware.ts` sees every request before any page does. This project uses it for rate limiting and request logging. The nearest WordPress equivalent is an mu-plugin hooking `template_redirect`.',
      '## Going deeper',
      'The frontend guide has the full routing table for this project and the archive and single-page recipes.',
    ],
  },
  {
    title: 'How to build a posts archive page in Astro',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'The archive.php equivalent: one file, a fetch in the frontmatter, and a loop. No WP_Query, because there is no database.',
    tags: ['astro', 'archive', 'themes'],
    publishedAt: at(14),
    body: [
      'An archive page lists posts. In a WordPress theme that is `archive.php` or `home.php`, and the posts arrive automatically in the main query — you just run the loop.',
      'Here you fetch them yourself, over HTTP.',
      '## The steps',
      '1. Create `src/pages/posts/index.astro`.',
      '2. In the frontmatter, call the Payload client to list posts.',
      '3. Below the fence, loop the array and render each one.',
      'The real file in this project is exactly that, plus a delete form per row.',
      '## The frontmatter is where the query goes',
      'Everything between the `---` fences runs **on the server, once per request**, and never ships to the browser. It is the part of a PHP template above the HTML — except it is TypeScript and it cannot touch a database.',
      'Instead of `WP_Query`, you call a function that makes an HTTP request to Payload. In this project that is `listPosts()` in `src/lib/payload.ts`.',
      '## Pagination',
      'Payload returns an envelope, not a bare array: `docs` plus `totalDocs`, `totalPages`, `page`, `hasNextPage` and `hasPrevPage`. That is more than `WP_Query` gives you without extra work, and it is all you need to render a pager.',
      '## Showing drafts',
      'By default an anonymous request sees only published posts, because of the read access rule. This project\'s archive passes `includeDrafts: true` and authenticates with the API key, which is why drafts appear there with a status badge.',
      '> That is a deliberate choice for a teaching app. A public blog archive would not do this.',
      '## Depth matters here',
      'If you want to show a category name or a cover image on each card, you need `depth: 1` so the relationship comes back expanded rather than as an ID.',
      '## Going deeper',
      'The frontend guide builds this page step by step and shows the real response envelope.',
    ],
  },
  {
    title: 'How to build a single post page in Astro',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'One file serves every post. The twist is rich text: Lexical is a JSON tree, and the_content() has no equivalent.',
    tags: ['astro', 'lexical', 'richtext'],
    publishedAt: at(15),
    body: [
      'The `single.php` equivalent is `src/pages/posts/[slug].astro`. One file serves every post; the `[slug]` is a parameter.',
      '## The steps',
      '1. Create `src/pages/posts/[slug].astro`.',
      '2. Read the parameter: `const { slug } = Astro.params`.',
      '3. Fetch the matching post with `depth: 1`.',
      '4. If nothing came back, return a 404 response.',
      '5. Render the title, metadata and body.',
      '## The part with no WordPress equivalent',
      '`the_content()` echoes HTML, because WordPress stores HTML. Payload\'s rich text is **Lexical**, which stores a JSON tree of nodes — paragraphs, headings, lists, links, each with its own properties.',
      'There is no function that turns it into HTML for you. You walk the tree.',
      'This project has a converter at `src/lib/lexical.ts` that handles paragraphs, headings, lists, quotes, links and horizontal rules, plus the text-format bitmask for bold, italic, underline, strikethrough and inline code.',
      '## Why a bitmask',
      'Formatting is not nested tags. It is a number on the text node: bold is 1, italic is 2, strikethrough 4, underline 8, code 16. Bold-italic is `format: 3`, not two wrapper elements.',
      '> That is why a naive converter drops formatting — it looks for tags that are not there.',
      '## Escaping is your job',
      'Because you are producing HTML yourself, you must escape text nodes. The converter here escapes every text node and every link href, and that is covered by unit tests. Rendering it with `set:html` is safe only because of that escaping.',
      '## Handling not-found',
      'Nothing serves a missing slug for you. Check whether the fetch returned a document and return a real 404 if not — otherwise the page renders empty with a 200, which is worse.',
      '## Going deeper',
      'The frontend guide covers the page and the rich-text conversion, with the bitmask worked through.',
    ],
  },
  {
    title: 'How to create a reusable widget for your site',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'Widget means two different things. One is a reusable component an editor can fill; the other is an admin dashboard panel.',
    tags: ['astro', 'components', 'widgets'],
    publishedAt: at(16),
    body: [
      'In WordPress, a widget is a block of content you drop into a sidebar. In Medusa, a widget is a panel injected into the admin UI. The word covers both, so this guide covers both.',
      '## Sense one — a reusable front-end block',
      'The equivalent is an Astro component: a `.astro` file in `src/components/` that takes props and renders markup. It is `get_template_part()` with a signature and type checking.',
      'This project has seven, including `RatingStars`, `StatTile` and `ReviewCard`. They ship **zero JavaScript** — they render on the server and send HTML.',
      '## Making one editable',
      'A component alone is not a widget in the WordPress sense, because an editor cannot change it. For that, pair it with a Payload **global**.',
      'The announcement banner in this project is exactly that pattern. The content lives in the site settings global; the layout reads it on every page and renders it if enabled. An editor toggles a checkbox and types a message, and every page changes.',
      '> That is a sidebar widget, rebuilt from parts: a global for the content, a component for the markup.',
      '## Sense two — an admin dashboard widget',
      'Medusa supports injecting React components into defined zones of its admin. This project has one at `apps/commerce/src/admin/widgets/product-reviews.tsx`, registered with `defineWidgetConfig` and a zone of `product.details.after`.',
      'It fetches reviews for the product you are viewing and offers approve, reject and delete buttons — a moderation panel inside the product page.',
      '## Worth knowing',
      'Payload has **no custom admin UI** in this project. Both systems support admin extensions; only Medusa\'s is used here. If you need a custom Payload admin component, that is a supported feature, just not demonstrated.',
      '## When to make it an island',
      'Add a `client:` directive only when the browser must do something the server cannot pre-compute. This storefront has exactly one island, a review filter, and every other component is zero-JavaScript.',
      '## Going deeper',
      'The frontend guide covers both senses and the full component list with props.',
    ],
  },
  {
    title: 'How to use TypeScript across Payload, Medusa and Astro',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'It is all three, not just Payload. Each app types things differently, and one of them deliberately hand-writes its types.',
    tags: ['typescript', 'types', 'tooling'],
    publishedAt: at(17),
    body: [
      'A common assumption is that TypeScript is a Payload thing here. It is not — all three apps are TypeScript, and each uses it differently.',
      '## Payload — generated from the config',
      'Payload reads your collection configs and writes `apps/cms/src/payload-types.ts`, containing an interface per collection. Regenerate it after any field change with `npm --prefix apps/cms run generate:types`.',
      'This is genuinely useful: the types cannot drift from the schema, because both come from the same declaration.',
      '## Medusa — framework types plus generated entry points',
      'Models, services, routes and workflows are all `.ts`. Types come from `@medusajs/framework/types`, and a build step writes generated query entry points into `.medusa/types/`.',
      '> That directory is a build artefact. On a cold clone it does not exist, and `tsc` fails until you have booted the dev server once.',
      '## Astro — frontmatter is TypeScript',
      'The code between the `---` fences in a `.astro` file is TypeScript, checked by `astro check` rather than plain `tsc`. Action schemas use `astro/zod`, which gives you validation and inferred types from one declaration.',
      '## The honest part',
      'Payload generates perfectly good types, and **this project does not import them in the storefront**. The storefront hand-writes its own in `src/lib/types.ts`, and the file explains why.',
      'The reasoning: the storefront talks to Payload over HTTP, across a service boundary. Importing the CMS\'s internal types would couple the frontend to the CMS\'s internals and to its release cycle. A hand-written type is an explicit statement of the contract the frontend depends on — and it covers only the fields actually used.',
      '> Whether you agree or not, know that it is a decision rather than an oversight. On a single-team project, importing the generated types is reasonable.',
      '## Checking everything',
      '`npm run typecheck` runs all three: `tsc --noEmit` for the two backends and `astro check` for the storefront.',
      '## Going deeper',
      'The stack guide covers each app\'s setup and the regeneration commands.',
    ],
  },

  // ── Data & APIs ───────────────────────────────────────────────────────────
  {
    title: 'How to fetch and display data from Payload and Medusa',
    category: 'Data & APIs',
    status: 'published',
    excerpt:
      'One rule governs everything: Astro has no database. Every read is an HTTP request to the service that owns the data.',
    tags: ['data', 'rest', 'astro'],
    publishedAt: at(18),
    body: [
      'This is the adjustment that matters most coming from WordPress. `WP_Query` talks to MySQL directly. **Astro cannot talk to a database at all.**',
      'Every read is an HTTP request to whichever service owns that data. Payload owns content; Medusa owns commerce and reviews; Astro owns nothing.',
      '## Reading Payload content',
      'Call `/api/posts` with query parameters. The ones you will use:',
      '- `where[field][operator]=value` — filtering, the `WP_Query` meta/tax query equivalent',
      '- `sort=-publishedAt` — ordering, with a leading minus for descending',
      '- `limit` and `page` — pagination',
      '- `depth` — how far to expand relationships',
      '- `select` — which fields to return',
      'The response is an envelope with `docs` plus pagination metadata.',
      '## Reading Medusa data',
      'Medusa\'s store API needs a publishable key header on every request. Without it you get a 400, not a 401, which is confusing the first time.',
      'The storefront uses the official JS SDK for built-in resources and plain fetch for the custom review routes.',
      '## Reading across two modules',
      'Reviews live in a custom module and products live in Medusa\'s. A module cannot join to another module, so the route that returns a product with its reviews uses `query.graph` and the link table.',
      '> You never write that JOIN yourself. You declare a link once, and the query layer resolves it.',
      '## Inside an Astro page',
      'Do the fetching in the frontmatter, which runs on the server. The dashboard in this project fires five backend calls in a single `Promise.all`, each wrapped so one failure does not blank the page.',
      'That pattern matters: if Medusa is down, the Payload panels should still render, and the broken one should say why.',
      '## The N+1 worth seeing',
      'The products page makes one request for the product list, then one more per product to get its reviews. It is labelled on the page rather than hidden, because recognising the shape is the lesson.',
      '## Going deeper',
      'The data guide covers all of this with runnable commands and the full query-parameter table.',
    ],
  },
  {
    title: 'How to add and insert data across the stack',
    category: 'Data & APIs',
    status: 'published',
    excerpt:
      'Three ways to write: a form with no JavaScript, a typed Action, or your own endpoint. This project ships all three.',
    tags: ['data', 'actions', 'forms'],
    publishedAt: at(19),
    body: [
      'Writing data has more moving parts than reading it, because of validation, credentials and the fact that two different backends disagree about HTTP verbs.',
      '## Option one — an Astro Action',
      'An Action is a typed server function with a zod schema. Point a form at it and it works **with JavaScript disabled**, because it posts to the page URL and the server handles it.',
      'This project has three, all for posts: create, update and delete. Validation errors come back per field, so the form can show a message under the offending input.',
      'The nearest WordPress equivalent is `admin-post.php` — a form posting to a handler — but typed, validated, and without a global router every plugin registers into.',
      '## Option two — your own REST endpoint',
      'A `.ts` file under `src/pages/api/` exporting `POST`. This project uses endpoints for reviews, deliberately, so the two patterns sit side by side.',
      'Use an endpoint when something other than your own form needs to call it: another service, a mobile app, curl.',
      '## Option three — straight to the backend',
      'POST to Payload\'s `/api/posts` with the API key header, or to Medusa\'s store API with the publishable key. Useful for scripts and for understanding the wire format.',
      '> The Payload header is `Authorization: users API-Key <key>`, not `Bearer`. That is the single most common mistake.',
      '## Update is where the backends disagree',
      'Payload updates with `PATCH`. Medusa\'s admin API updates with `POST`. Neither is wrong; they are different conventions.',
      'The storefront hides that: its own endpoint accepts `PATCH` and translates. Your pages call one function and never learn which backend wanted what — which is precisely the job of a backend-for-frontend layer.',
      '## Writes that run workflows',
      'Creating a review does not just insert a row. It runs a Medusa workflow: validate the product, insert the review, write the link row, emit an event. If any step fails, the completed steps are undone.',
      'So a failed review creation leaves **nothing** behind — no orphan row, no dangling link.',
      '## Going deeper',
      'The data guide covers all three paths with runnable examples, including the form that works without JavaScript.',
    ],
  },
  {
    title: 'How to delete data, and why some rows survive',
    category: 'Data & APIs',
    status: 'published',
    excerpt:
      'Payload deletes rows. Medusa marks them deleted. Knowing which is which changes how you read every count.',
    tags: ['data', 'soft-delete', 'medusa'],
    publishedAt: at(20),
    body: [
      'Deleting looks simple until you notice the two backends mean different things by it.',
      '## Payload — the row is gone',
      '`DELETE /api/posts/:id` removes the row. There is no trash, no `wp_trash_post` equivalent, no thirty-day window. Version rows in `_posts_v` go with it.',
      'If you want a trash, model it: add a status field and filter on it. Nothing gives it to you.',
      '## Medusa — the row stays',
      'Deleting a review is a **soft delete**. The row remains in the table with `deleted_at` set to a timestamp, and the normal list queries exclude it.',
      'You can prove it: count rows, delete one, count again. The total is unchanged; only the live count drops.',
      '> This is closer to WordPress\'s trash than Payload is, but it is invisible rather than a screen you visit.',
      '## Why that matters for counting',
      'Any `select count(*) from review` includes deleted rows. If your numbers look too high, that is usually why. Filter on `deleted_at is null` to get the live count.',
      '## The link row outlives the review',
      'When a review is soft-deleted, its row in the product-to-review link table **stays**. That is deliberate: restoring the review reattaches it without rebuilding the relationship.',
      'The consequence is that a query joining products to reviews can return gaps where a soft-deleted review used to be. Every reader in this project filters those out, and the comment above each one explains why.',
      '## The 403 you will hit first',
      'A `DELETE` to the storefront without an `Origin` header returns **403 before any of your code runs**. That is Astro\'s built-in origin check, a CSRF protection enabled by default for server-rendered sites.',
      'Add a matching `Origin` header and the same request works. Browsers set it automatically, so this only bites from curl.',
      '> Because it runs upstream of middleware, those rejected requests never appear in the request log. A tool can only log what reaches it.',
      '## Going deeper',
      'The data guide proves the soft delete with psql counts before and after.',
    ],
  },

  // ── Commerce ──────────────────────────────────────────────────────────────
  {
    title: 'How to add an online payment gateway with Medusa',
    category: 'Commerce',
    status: 'published',
    excerpt:
      'You register a provider rather than building one. The official Stripe package exists — and so does an older one that will not work.',
    tags: ['medusa', 'payments', 'stripe'],
    publishedAt: at(21),
    body: [
      'The good news first: you do not build this. Medusa ships a payment module with a provider architecture, and providers are installed packages.',
      '## The approach',
      '1. Install the provider, for example `@medusajs/payment-stripe`.',
      '2. Register it in the `payment` module\'s `providers` array in `medusa-config.ts`.',
      '3. Put the API keys in `apps/commerce/.env`.',
      '4. Attach the provider to a region, so carts in that region can use it.',
      '5. Add the client-side payment form to the storefront.',
      'Step two has a shape worth copying from something already working. The `locking` module in this project is configured exactly that way — a host module with a `providers` array — so read that block before writing yours.',
      '## The trap that will cost you an evening',
      'Searching npm for a Medusa Stripe package finds **`medusa-payment-stripe`** first. That is the **Medusa v1 community package and it does not work with v2**.',
      '> The one you want is `@medusajs/payment-stripe`. The naming is close enough to lose real time over.',
      '## The flow, mapped to WooCommerce',
      '- Cart → the WooCommerce cart',
      '- Payment collection → the order\'s payment record',
      '- Payment session → the gateway handoff',
      '- Authorise → the gateway holds the funds',
      '- Capture → the funds move',
      'WooCommerce collapses several of these; Medusa keeps them separate so each is independently inspectable and retryable.',
      '## Where the storefront fits',
      'The card form runs in the browser, because card details must never touch your server. This is one of the few places client-side JavaScript is genuinely required in an otherwise server-rendered site.',
      '**The secret key belongs in Medusa, never in the Astro app.** Astro holds a publishable key only.',
      '## Not configured here',
      'This repository has no payment provider. The seeded region lists a built-in no-op provider, and no cart or order has ever been created. Treat the above as the map, not a transcript.',
      '## Going deeper',
      'The commerce guide covers the full flow and the configuration shape.',
    ],
  },
  {
    title: 'How to run multiple stores and multiple warehouses in Medusa',
    category: 'Commerce',
    status: 'published',
    excerpt:
      'You do not custom-build it. Sales channels, stock locations and inventory levels are core — which is the real Medusa win over WooCommerce.',
    tags: ['medusa', 'inventory', 'multistore'],
    publishedAt: at(22),
    body: [
      'In WooCommerce, multiple storefronts usually means WordPress Multisite, and multiple warehouses means a paid plugin. Both are bolted on.',
      'In Medusa they are core concepts, and this is the clearest advantage the platform has for anyone coming from Woo.',
      '## Sales channels — multiple storefronts',
      'A sales channel is a storefront. Products are assigned to channels, and an API key is scoped to a channel, so each storefront sees its own catalogue from one backend and one database.',
      'A retail site, a wholesale site and a mobile app can be three channels over the same products.',
      '> This project has one channel, and the storefront\'s publishable key is scoped to it. A product not assigned to that channel is **invisible** to the storefront — silently, with an empty list rather than an error.',
      '## Stock locations — multiple warehouses',
      'A stock location is a place inventory sits. You can have as many as you like.',
      '## Inventory levels — quantity per item per location',
      'An inventory level joins an inventory item to a location with a quantity. That is what makes multi-warehouse work: one product variant can hold different quantities in different places, and Medusa decides what is available.',
      '## Regions — currency, countries, tax',
      'A region groups countries with a currency, tax settings and permitted payment providers. One store can serve several regions with different prices and tax rules.',
      '## Price lists — sale and customer-group pricing',
      'Price lists override prices for a period or for a customer group. That covers sales, wholesale tiers and contract pricing without touching the base price.',
      '## What is actually running here',
      'All of these exist as seeded rows in this project — one region, one sales channel, one warehouse, inventory levels per variant — but **nothing in the app reads most of them**. There is no region selector and no stock display.',
      'They are there so you can inspect the shape in the database, not because this is a working multi-region store.',
      '## When Medusa is the wrong answer',
      'A single-currency, single-warehouse shop with two hundred products and a Stripe button is faster to build and cheaper to run in WooCommerce. Medusa earns its complexity when you genuinely have the dimensions above.',
      '## Going deeper',
      'The commerce guide shows the row counts for each and maps them to their WooCommerce equivalents.',
    ],
  },
  {
    title: 'How workflows and compensation keep your data consistent',
    category: 'Commerce',
    status: 'published',
    excerpt:
      'The single most valuable thing Medusa offers a WooCommerce developer: a multi-step write that undoes itself when a later step fails.',
    tags: ['medusa', 'workflows', 'compensation'],
    publishedAt: at(23),
    body: [
      'In WooCommerce, when order creation half-fails you clean up by hand. The order exists, the stock was decremented, the email did not send, and you are in the database working out what to undo.',
      'Medusa\'s answer is the workflow, and it is the feature most worth understanding.',
      '## What a workflow is',
      'A sequence of steps. Each step does its work and may also declare **how to undo it**. If any later step fails, Medusa runs the undo functions of the completed steps, in reverse.',
      '## The example in this project',
      'Creating a review runs four steps: validate the product exists, insert the review, write the link row joining review to product, emit an event.',
      '- Validate has **no** compensation, because it only reads. Nothing to undo.',
      '- Insert compensates by deleting the review it created.',
      '- Link compensates by dismissing the link.',
      '- Emit never needs undoing.',
      '## Watching it fail',
      'There is a deliberate failure switch in the link step, enabled by an environment variable. Turn it on, create a review, and the request fails — then count the rows.',
      '> Eleven reviews before, eleven after. No orphan row, no dangling link. There is a test that asserts exactly this and exits non-zero if it ever stops being true.',
      '## Reverted is not the same as failed',
      'Medusa records each execution with a state, and two of them look similar but mean opposite things.',
      '- `reverted` — it failed, and **every compensation ran**. The database is clean. This is the success case of failure handling.',
      '- `failed` — it failed and could not be fully rolled back. This is the one to investigate, because it may have left something behind.',
      'Collapsing both into one error count throws away the only distinction worth alerting on.',
      '## It only gets recorded if you ask',
      'Workflow executions are only persisted when the Redis workflow engine is configured **and** the workflow opts in with a retention time. Miss either and the table stays empty — and an empty failure count looks exactly like good news.',
      '## Going deeper',
      'The Medusa chapter builds a workflow step by step, and the operations chapter covers reading the execution states.',
    ],
  },

  // ── Operations & Tooling ──────────────────────────────────────────────────
  {
    title: 'Are there plugins for SEO and caching in this stack?',
    category: 'Operations & Tooling',
    status: 'published',
    excerpt:
      'Yes, but far fewer, and installing one means npm plus a config edit plus a restart. The honest comparison to 60,000 WordPress plugins.',
    tags: ['plugins', 'seo', 'caching'],
    publishedAt: at(24),
    body: [
      'The honest answer first: WordPress has roughly sixty thousand free plugins, installable from inside the admin with no build step. These three projects have a few dozen official packages each.',
      'There is no marketplace, no one-click install, and far less "somebody already solved this". That is a genuine loss and worth knowing before you plan a project.',
      'What you gain is that what you do install is typed, versioned, and cannot silently inject into your `<head>` or rewrite your queries.',
      '## Payload plugins that exist',
      '- `@payloadcms/plugin-seo` — meta fields and previews',
      '- `@payloadcms/plugin-form-builder` — the Gravity Forms analogue',
      '- `@payloadcms/plugin-redirects` — redirect management',
      '- `@payloadcms/plugin-search` — a search index collection',
      '- `@payloadcms/plugin-nested-docs` — parent/child pages and breadcrumbs',
      '- `@payloadcms/storage-s3` — move uploads off local disk',
      '## Astro integrations',
      '- `@astrojs/sitemap` — sitemap.xml',
      '- `@astrojs/rss` — a feed',
      '- `@astrojs/partytown` — third-party scripts off the main thread',
      '- `astro-seo` — a community meta and Open Graph component',
      '## Medusa modules',
      '- `@medusajs/payment-stripe` — payments',
      '- `@medusajs/file-s3` — file storage',
      '- `@medusajs/notification-sendgrid` — email',
      '## How you install one',
      'npm install it in the right app, add it to that app\'s config array, restart. For Payload that is the `plugins` array in `payload.config.ts` — which in this project is currently **empty**, so it is a clean place to start.',
      '## Caching is the awkward one',
      '**There is no caching plugin.** Nothing in this project caches pages. Astro re-renders every request, Medusa has a Redis cache for module data, and Payload has none.',
      'Page caching here is a CDN or reverse-proxy concern, not something you install. Coming from WP Super Cache, that is a real adjustment.',
      '## Going deeper',
      'The plugins guide covers installation step by step and the four questions worth asking before adding any dependency.',
    ],
  },
  {
    title: 'How to build a multilingual site without WPML',
    category: 'Operations & Tooling',
    status: 'published',
    excerpt:
      'Payload localises fields inside one document rather than duplicating posts per language. That difference changes how you query.',
    tags: ['i18n', 'localization', 'wpml'],
    publishedAt: at(25),
    body: [
      'With WPML or Polylang you install a plugin, pick languages, and each post gets a translated **copy** linked to the original. Two languages means two posts.',
      'Payload does it differently, and the difference is structural rather than cosmetic.',
      '## Field-level localization',
      'You declare locales once in `payload.config.ts`, then mark individual fields `localized: true`. One document holds every translation of those fields.',
      '> One post, one ID, many language values. There is no "translation of" relationship, because there is no second post.',
      '## Why that matters in practice',
      '- A relationship pointing at that post keeps working in every language. Under WPML you have to decide which translation a link refers to.',
      '- Fields you do not mark localized are shared, so a publish date or a category stays in sync automatically.',
      '- Queries take a `locale` parameter and return that language\'s values in the normal field names, so your rendering code does not change.',
      '- Migrating from WPML is not a copy — it is a restructure, because you are collapsing N posts into one.',
      '## The Astro half',
      'Astro has built-in i18n routing: configure locales and a default, and it handles prefixed URLs like `/de/posts/...` and locale detection. You then pass the locale through to your Payload queries.',
      '## The Medusa half',
      'Commerce multilingualism is partly a **region** concern rather than a translation one — currency, tax and available payment providers vary by region, independently of the language a visitor reads.',
      '## Not configured here',
      'Both features are genuinely built in, and **neither is configured in this project**. There are no locales in the Payload config and no i18n block in the Astro config. The shapes above are the map, not a transcript — you cannot run them against this repo as it stands.',
      '## Going deeper',
      'The plugins guide covers the configuration for both and the WPML comparison in more detail.',
    ],
  },
  {
    title: 'How to browse PostgreSQL with pgAdmin and other tools',
    category: 'Operations & Tooling',
    status: 'published',
    excerpt:
      'The phpMyAdmin question. Several good options, one connection detail that catches everyone, and one warning about editing rows.',
    tags: ['postgres', 'pgadmin', 'tooling'],
    publishedAt: at(26),
    body: [
      'Coming from phpMyAdmin or Adminer, you want a window into the database. There are several, and they all need the same five values.',
      '## The connection details',
      '- Host: `localhost`',
      '- **Port: 5433** — not 5432',
      '- User: `postgres`',
      '- Password: `postgres`',
      '- Databases: `payload_crud` and `medusa_crud`',
      'The port is the thing that catches everyone. The container maps 5433 on your machine to 5432 inside, deliberately, so it cannot collide with a Postgres already installed locally.',
      '## The options',
      '- **pgAdmin 4** — the closest thing to phpMyAdmin, a web UI, free. Heavy, but familiar if you are used to a browser-based tool.',
      '- **DBeaver** — free desktop client, works with many engines, a better query editor than pgAdmin.',
      '- **TablePlus** — desktop, paid with a limited free tier, the nicest interface of the group.',
      '- **Beekeeper Studio** — open-source desktop client.',
      '- **Adminer** — a single PHP file, the literal analogue of phpMyAdmin. Can be added to the Docker Compose file as another service.',
      '- **psql** — already wired up. `npm run db:psql` opens a shell inside the container with nothing to install.',
      '## The psql commands worth knowing',
      '- `\\l` — list databases',
      '- `\\c payload_crud` — connect to one',
      '- `\\dt` — list tables',
      '- `\\d posts` — describe a table',
      '- `\\x` — toggle expanded output, which makes wide rows readable',
      '- `\\q` — quit',
      '## The warning that matters',
      'A GUI lets you edit rows directly. In WordPress, editing `wp_posts` by hand is risky. **Here it is architecturally wrong.**',
      '> A review edited in pgAdmin skips its Medusa workflow, so no link row is written and no event is emitted. A post edited in pgAdmin skips Payload\'s hooks, so no slug is derived and no version is recorded.',
      'Read freely. Write through the APIs.',
      '## Going deeper',
      'The tools guide has connection steps for each client and the full psql command table.',
    ],
  },
  {
    title: 'Which VS Code extensions to install for this stack',
    category: 'Operations & Tooling',
    status: 'published',
    excerpt:
      'A short list that earns its place, plus the one extension without which .astro files are unreadable.',
    tags: ['vscode', 'tooling', 'editor'],
    publishedAt: at(27),
    body: [
      'Coming from a PHP setup you probably have Intelephense and a linter. This stack needs a different short list, and one of them is essential rather than nice to have.',
      '## The essential one',
      '**Astro** (`astro-build.astro-vscode`). Without it a `.astro` file has no syntax highlighting, no IntelliSense and no type checking in the frontmatter — it reads like a text file with angle brackets. Install this first.',
      '## Strongly recommended',
      '- **ESLint** — all three apps are configured for it; surfacing problems inline beats finding them in a terminal.',
      '- **Prettier** — consistent formatting across `.ts`, `.astro` and `.tsx`.',
      '- **Docker** — the database and Redis run in containers; being able to see status and logs without leaving the editor is worth the install.',
      '## Worth having',
      '- **REST Client** — runs the `docs/requests.http` file in this repository directly. Every endpoint in the stack is already written out there, so you get a working API client with no setup.',
      '- **Error Lens** — puts TypeScript errors inline instead of in a panel. Opinionated, and very good when learning a new type system.',
      '- **PostgreSQL** — query the database from the editor, as an alternative to a separate GUI.',
      '## If you use React',
      'The storefront has exactly one React island. If you add more, the usual React and JSX tooling applies — but note that most components here are `.astro` and ship no JavaScript, so React tooling matters less than it would in a Next project.',
      '## What you can skip',
      'You do not need a PHP extension, and you do not need anything WordPress-specific. There is no `functions.php`, no theme to lint, and no plugin boilerplate to generate.',
      '## Checking it worked',
      'Open any `.astro` file. If the frontmatter between the fences is syntax-highlighted as TypeScript and hovering a variable shows its type, the Astro extension is active.',
      '## Going deeper',
      'The tools guide lists the extensions with IDs and covers the rest of the local toolkit.',
    ],
  },
  {
    title: 'How to debug when a request fails',
    category: 'Operations & Tooling',
    status: 'published',
    excerpt:
      'Four layers can produce an error. Identifying which one is talking is most of the work, and the status code usually tells you.',
    tags: ['debugging', 'troubleshooting', 'logs'],
    publishedAt: at(28),
    body: [
      'With WordPress there is one program, so an error is in one place. Here a failed request may have been rejected by any of four layers, and each produces a different-looking error.',
      '## The four layers',
      '1. The browser or curl — never reached the server',
      '2. Astro — middleware, a page, or one of its endpoints',
      '3. Payload or Medusa — the backend that owns the data',
      '4. Postgres — a constraint or a connection problem',
      '## Read the status code first',
      '- **400** from Medusa — usually a missing publishable key header',
      '- **401** — no credentials, or the wrong kind',
      '- **403** — credentials present but not permitted; from Astro on a `DELETE`, almost always the missing `Origin` header',
      '- **404** — the route does not exist, or a read-access rule narrowed it out of existence',
      '- **422** — validation failed; the body will name the field',
      '- **429** — rate limited',
      '- **500** — the backend threw; check its log',
      '- **502** — your BFF reached the backend and the backend failed',
      '## The 404 that is really access control',
      'Worth internalising: a draft post requested anonymously returns 404, not 403. The read rule narrows the query to published documents, so the draft genuinely does not exist for that request. Nothing is hidden — it was never in the result set.',
      '## Where to look',
      '`npm run logs` tails all three services. `npm run logs:errors` greps warnings and errors out of them.',
      'The storefront also keeps an in-memory log of recent requests with status and duration, visible on its monitor page.',
      '## The blind spot',
      'That request log cannot see anything rejected **before** middleware runs — including Astro\'s own origin check. So a 403 from a missing `Origin` header never appears there.',
      '> If your traffic graph and your users disagree about whether requests are arriving, that gap is where to look.',
      '## The escalation ladder',
      'Restart one service, then all three, then reset the database, then reinstall dependencies. Work down it and stop at the first thing that works.',
      '## Going deeper',
      'The troubleshooting chapter is organised as symptom, cause, fix, with the literal error strings as headings.',
    ],
  },
  {
    title: 'Draft: how to migrate an existing WordPress site to this stack',
    category: 'Operations & Tooling',
    status: 'draft',
    excerpt:
      'Unfinished notes on content migration. Left as a draft deliberately, so the access-control rules have something to hide.',
    tags: ['migration', 'wordpress', 'draft'],
    publishedAt: at(29),
    body: [
      'This post is an unpublished draft. It exists so that the draft machinery has something real to demonstrate: fetch the posts list anonymously and it will not appear, because the read access rule narrows the query to published documents.',
      'Authenticate with the API key, or pass the draft flag while logged in, and it appears.',
      '## Rough notes so far',
      '- Export `wp_posts` and `wp_postmeta`, and decide which meta keys become real Payload fields. There is no key-value store on the other side, so every one needs a home in the config or it has nowhere to go.',
      '- ACF Flexible Content layouts map reasonably well onto Payload blocks, but each layout needs declaring up front.',
      '- The media library is the slow part. Files need re-uploading so Payload can generate its own derivative sizes; the URLs in post content need rewriting afterwards.',
      '- Rich text is the hard part. WordPress stores HTML; Payload stores a Lexical node tree. Converting means parsing the HTML and emitting nodes, and anything unusual needs a decision.',
      '- Redirects matter. Permalink structures rarely survive a migration unchanged, so plan the old-to-new URL map before cutover rather than after.',
      '- WooCommerce products to Medusa is a separate project from content migration, with its own variant and pricing model to reconcile.',
      '## Still to write',
      'A worked example with a real export, and an honest estimate of how long each stage takes.',
    ],
  },
  {
    title: 'Draft: a performance budget for this stack',
    category: 'Operations & Tooling',
    status: 'draft',
    excerpt:
      'Working notes on what to measure and what to cap. Unpublished until the numbers are measured rather than guessed.',
    tags: ['performance', 'draft'],
    publishedAt: at(30),
    body: [
      'Another deliberate draft. Anonymous requests will not see it; authenticated ones will.',
      '## What is worth measuring',
      '- Time to first byte on a server-rendered page, which is dominated by backend round trips rather than by rendering',
      '- JavaScript shipped per route. Most pages here send **zero**, and the one island is the exception worth watching',
      '- Backend calls per page. The products page currently makes one request per product on top of the list request',
      '## What is not yet decided',
      'Whether to set a hard cap on island count, and where page caching should live given there is none today.',
      'Numbers go here once they are measured on something other than a laptop.',
    ],
  },
  {
    title: 'Draft: deployment notes for three services',
    category: 'Operations & Tooling',
    status: 'draft',
    excerpt:
      'Rough notes on taking this to production. Three deploys, two databases, and several things this repo deliberately does not do.',
    tags: ['deployment', 'production', 'draft'],
    publishedAt: at(31),
    body: [
      'A third draft, kept unpublished on purpose.',
      '## The shape of the problem',
      'Three applications means three build pipelines and three deploys that can be out of step with each other. WordPress has one artefact; this has three, and they must agree on API contracts across versions.',
      '## Known blockers in this repo',
      '- Payload runs in `push` mode, so there are no migration files to apply on deploy',
      '- Files are stored on local disk, so a container rebuild loses uploads',
      '- The storefront has no authentication at all',
      '- Secrets are development placeholders',
      '## Still to work out',
      'Whether the three services deploy together or independently, and what the rollback story is when only one of them moves.',
    ],
  },
]
