import type { CollectionConfig } from 'payload'

/**
 * Media — an upload-enabled collection.
 *
 * `upload` turns a normal collection into a file store. Payload adds `filename`,
 * `mimeType`, `filesize`, `width`, `height` and `url` fields automatically, and
 * exposes the binary at:
 *
 *   GET /api/media/file/<filename>
 *
 * The `imageSizes` below are generated by sharp on upload. Each named size
 * becomes an entry under `doc.sizes`, so a consumer can request exactly the
 * variant it needs instead of downloading the original.
 */
export const Media: CollectionConfig = {
  slug: 'media',
  admin: {
    useAsTitle: 'alt',
  },
  access: {
    // Images are public; writing them requires a logged-in user or an API key.
    read: () => true,
    create: ({ req }) => Boolean(req.user),
    update: ({ req }) => Boolean(req.user),
    delete: ({ req }) => Boolean(req.user),
  },
  upload: {
    staticDir: 'public/media',
    mimeTypes: ['image/*'],
    imageSizes: [
      { name: 'thumbnail', width: 400, height: 300, position: 'centre' },
      { name: 'card', width: 768, height: 512, position: 'centre' },
    ],
  },
  fields: [
    {
      name: 'alt',
      type: 'text',
      required: true,
      admin: {
        description: 'Describe the image for screen readers. Required on purpose.',
      },
    },
  ],
}
