import type { Guide } from './types'

/** Commerce — 3 guides. */
export const commerce: Guide[] = [
  {
    title: 'How to add an online payment gateway with Medusa',
    category: 'Commerce',
    status: 'published',
    excerpt:
      'You register a provider rather than building one. The official Stripe package exists — and so does an older one that will not work.',
    tags: ['medusa', 'payments', 'stripe'],
    body: [
      'The good news first: you do not build this. Medusa ships a payment module with a provider architecture, and providers are installed packages.',
      '## The approach',
      '1. Install the provider, for example `@medusajs/payment-stripe`.',
      '2. Register it in the `payment` module\'s `providers` array in `medusa-config.ts`.',
      '3. Put the API keys in `apps/commerce/.env`.',
      '4. Attach the provider to a region, so carts in that region can use it.',
      '5. Add the client-side payment form to the storefront.',
      'Step two has a shape worth copying from something already working. The `locking` module in this project is configured exactly that way — a host module with a `providers` array — so read that block before writing yours.',
      '## The trap that will cost you an evening',
      'Searching npm for a Medusa Stripe package finds **`medusa-payment-stripe`** first. That is the **Medusa v1 community package and it does not work with v2**.',
      '> The one you want is `@medusajs/payment-stripe`. The naming is close enough to lose real time over.',
      '## The flow, mapped to WooCommerce',
      '- Cart → the WooCommerce cart',
      '- Payment collection → the order\'s payment record',
      '- Payment session → the gateway handoff',
      '- Authorise → the gateway holds the funds',
      '- Capture → the funds move',
      'WooCommerce collapses several of these; Medusa keeps them separate so each is independently inspectable and retryable.',
      '## Where the storefront fits',
      'The card form runs in the browser, because card details must never touch your server. This is one of the few places client-side JavaScript is genuinely required in an otherwise server-rendered site.',
      '**The secret key belongs in Medusa, never in the Astro app.** Astro holds a publishable key only.',
      '## Not configured here',
      'This repository has no payment provider. The seeded region lists a built-in no-op provider, and no cart or order has ever been created. Treat the above as the map, not a transcript.',
      '## Going deeper',
      'The commerce guide covers the full flow and the configuration shape.',
    ],
  },
  {
    title: 'How to run multiple stores and multiple warehouses in Medusa',
    category: 'Commerce',
    status: 'published',
    excerpt:
      'You do not custom-build it. Sales channels, stock locations and inventory levels are core — which is the real Medusa win over WooCommerce.',
    tags: ['medusa', 'inventory', 'multistore'],
    body: [
      'In WooCommerce, multiple storefronts usually means WordPress Multisite, and multiple warehouses means a paid plugin. Both are bolted on.',
      'In Medusa they are core concepts, and this is the clearest advantage the platform has for anyone coming from Woo.',
      '## Sales channels — multiple storefronts',
      'A sales channel is a storefront. Products are assigned to channels, and an API key is scoped to a channel, so each storefront sees its own catalogue from one backend and one database.',
      'A retail site, a wholesale site and a mobile app can be three channels over the same products.',
      '> This project has one channel, and the storefront\'s publishable key is scoped to it. A product not assigned to that channel is **invisible** to the storefront — silently, with an empty list rather than an error.',
      '## Stock locations — multiple warehouses',
      'A stock location is a place inventory sits. You can have as many as you like.',
      '## Inventory levels — quantity per item per location',
      'An inventory level joins an inventory item to a location with a quantity. That is what makes multi-warehouse work: one product variant can hold different quantities in different places, and Medusa decides what is available.',
      '## Regions — currency, countries, tax',
      'A region groups countries with a currency, tax settings and permitted payment providers. One store can serve several regions with different prices and tax rules.',
      '## Price lists — sale and customer-group pricing',
      'Price lists override prices for a period or for a customer group. That covers sales, wholesale tiers and contract pricing without touching the base price.',
      '## What is actually running here',
      'All of these exist as seeded rows in this project — one region, one sales channel, one warehouse, inventory levels per variant — but **nothing in the app reads most of them**. There is no region selector and no stock display.',
      'They are there so you can inspect the shape in the database, not because this is a working multi-region store.',
      '## When Medusa is the wrong answer',
      'A single-currency, single-warehouse shop with two hundred products and a Stripe button is faster to build and cheaper to run in WooCommerce. Medusa earns its complexity when you genuinely have the dimensions above.',
      '## Going deeper',
      'The commerce guide shows the row counts for each and maps them to their WooCommerce equivalents.',
    ],
  },
  {
    title: 'How workflows and compensation keep your data consistent',
    category: 'Commerce',
    status: 'published',
    excerpt:
      'The single most valuable thing Medusa offers a WooCommerce developer: a multi-step write that undoes itself when a later step fails.',
    tags: ['medusa', 'workflows', 'compensation'],
    body: [
      'In WooCommerce, when order creation half-fails you clean up by hand. The order exists, the stock was decremented, the email did not send, and you are in the database working out what to undo.',
      'Medusa\'s answer is the workflow, and it is the feature most worth understanding.',
      '## What a workflow is',
      'A sequence of steps. Each step does its work and may also declare **how to undo it**. If any later step fails, Medusa runs the undo functions of the completed steps, in reverse.',
      '## The example in this project',
      'Creating a review runs four steps: validate the product exists, insert the review, write the link row joining review to product, emit an event.',
      '- Validate has **no** compensation, because it only reads. Nothing to undo.',
      '- Insert compensates by deleting the review it created.',
      '- Link compensates by dismissing the link.',
      '- Emit never needs undoing.',
      '## Watching it fail',
      'There is a deliberate failure switch in the link step, enabled by an environment variable. Turn it on, create a review, and the request fails — then count the rows.',
      '> Eleven reviews before, eleven after. No orphan row, no dangling link. There is a test that asserts exactly this and exits non-zero if it ever stops being true.',
      '## Reverted is not the same as failed',
      'Medusa records each execution with a state, and two of them look similar but mean opposite things.',
      '- `reverted` — it failed, and **every compensation ran**. The database is clean. This is the success case of failure handling.',
      '- `failed` — it failed and could not be fully rolled back. This is the one to investigate, because it may have left something behind.',
      'Collapsing both into one error count throws away the only distinction worth alerting on.',
      '## It only gets recorded if you ask',
      'Workflow executions are only persisted when the Redis workflow engine is configured **and** the workflow opts in with a retention time. Miss either and the table stays empty — and an empty failure count looks exactly like good news.',
      '## Going deeper',
      'The Medusa chapter builds a workflow step by step, and the operations chapter covers reading the execution states.',
    ],
  },
  {
    title: 'The cart, and why this repo has never created one',
    category: 'Commerce',
    status: 'published',
    excerpt:
      'Medusa ships a complete cart module. The table exists, it has zero rows, and understanding why is more useful than pretending otherwise.',
    tags: ['medusa', 'cart', 'woocommerce'],
    body: [
      '🚫 **Zero carts have ever been created here.** The `cart` table exists because Medusa ships it, and nothing in this repo touches it.',
      '## What a cart is in Medusa',
      'More than a list of items. A cart carries the region (so currency and tax are known), line items with prices captured at add time, shipping methods, addresses, and payment sessions once checkout starts.',
      'It is effectively **an order before it is an order** — which is why the two are separate concepts rather than one row with a status.',
      '## Compared to WooCommerce',
      'Woo keeps the cart in the session, serialised, and in the database for logged-in customers. It belongs to a browser session more than to a record.',
      'A Medusa cart is a **first-class row with an id** from the moment it exists. That means it survives a browser change, can be recovered after abandonment, and can be inspected server-side without unserialising a session blob.',
      '## Prices are captured, not referenced',
      '⚠️ A line item stores the price **at the time it was added**. Change the product price and existing carts keep theirs.',
      'That is correct behaviour and surprises people. The alternative — recalculating against current prices — means a customer sees one price at add time and another at checkout.',
      '## What it would take to add',
      'Create a cart with a region, add line items by variant, set shipping and addresses, create a payment collection, complete. Each is a Store API call, and Medusa provides all of them — ✅ **you would write no cart logic**, only the UI and the sequencing.',
      '## Why it is not here',
      'This repo demonstrates reviews and operations on top of Medusa\'s product module. A checkout flow is a substantial piece of frontend work that would not teach anything about the architecture the repo exists to show.',
      '⚠️ **Do not read the empty tables as "Medusa cannot do this".** Read them as "nobody asked it to".',
    ],
  },
  {
    title: 'The checkout flow, mapped to WooCommerce',
    category: 'Commerce',
    status: 'published',
    excerpt:
      'Medusa separates steps WooCommerce collapses into one. More moving parts, and each is independently inspectable and retryable.',
    tags: ['medusa', 'checkout', 'payments'],
    body: [
      '🚫 **No checkout exists in this repo.** This is the map.',
      '## The sequence',
      '1. **Cart** — with a region, which fixes currency and tax',
      '2. **Line items** — added by variant, prices captured',
      '3. **Shipping address** — which may change the tax calculation',
      '4. **Shipping method** — chosen from options valid for that region',
      '5. **Payment collection** — the container for payment attempts on this cart',
      '6. **Payment session** — one attempt with one provider',
      '7. **Authorize** — the provider holds the funds',
      '8. **Complete** — the cart becomes an order',
      '9. **Capture** — the funds actually move',
      '## Where WooCommerce differs',
      'Woo collapses 5 through 9. You click Place Order, and the gateway, the order creation and the status change happen as one flow with hooks between.',
      '> Medusa keeps them separate so each is independently inspectable and retryable.',
      'Concretely: a payment that authorised but whose order creation failed is a **recoverable state** here, with the authorisation sitting there to be completed or released. In Woo that situation usually needs a human in the database.',
      '## Authorize and capture are not the same',
      '⚠️ Worth internalising if you are coming from Woo, where they are usually one step. **Authorize** reserves the money. **Capture** takes it. Separating them lets you authorise at checkout and capture at dispatch, which is how physical goods should work and what card-scheme rules often expect.',
      '## The failure mode that matters',
      'Every step can fail, and the ones involving money must not leave the system half-changed. ✅ This is exactly what Medusa\'s workflows and compensation are for, and why this repo spends a whole chapter on a workflow that only creates a review — the mechanism is the same one that will handle your orders.',
    ],
  },
  {
    title: 'Orders, and what happens after the money moves',
    category: 'Commerce',
    status: 'published',
    excerpt:
      'An order is not a post with a status. Fulfilment, payment and returns are separate concerns with their own lifecycles.',
    tags: ['medusa', 'orders', 'fulfillment'],
    body: [
      '🚫 **No order has ever been created here.** The tables exist; nothing writes to them.',
      '## The shape',
      'In WooCommerce an order is a post with a status — `wc-processing`, `wc-completed` — and metadata hanging off it. One status field describes everything.',
      'Medusa splits it, because the things it describes move independently:',
      '- The **order** — what was bought, by whom, at what price',
      '- **Payment** — authorised, captured, refunded',
      '- **Fulfilment** — picked, shipped, delivered',
      '- **Returns and exchanges** — their own lifecycle entirely',
      '## Why that matters',
      '> An order can be fully paid and not shipped, partly shipped and partly refunded, or delivered and then partly returned.',
      'A single status field cannot express that, which is why Woo stores have so many custom statuses and why reporting against them is painful. Separate lifecycles describe the real situation without inventing vocabulary.',
      '## Orders are immutable-ish',
      '⚠️ You do not edit an order the way you edit a post. Changes are recorded as **events** — a refund, an exchange, an edit — rather than overwriting fields.',
      'That is deliberate: an order is a financial record. Knowing what it looked like at the time, and what changed since, is the point. Woo\'s order notes approximate this; Medusa models it.',
      '## What you get for free',
      '✅ If you do add checkout, you write no order state machine. Medusa provides order creation, payment capture, fulfilment, returns, exchanges and credit lines as workflows that already handle their own rollback.',
      '## The number worth knowing',
      'The `order` table here has **0 rows**, and the review table has 45. That ratio says exactly what this repo is: reviews and operations built on Medusa\'s product module, not a commerce demo.',
    ],
  },
  {
    title: 'Customers, and why reviews here are not linked to them',
    category: 'Commerce',
    status: 'published',
    excerpt:
      'The customer module is unused and reviews carry a free-text name instead. That was a deliberate simplification with real consequences.',
    tags: ['medusa', 'customers', 'reviews'],
    body: [
      '🚫 **Zero customers.** Reviews carry `author_name` and an optional `author_email` as plain text.',
      '## What that costs',
      '- No verified-purchase badge — nothing connects a review to an order',
      '- No review history per person',
      '- No way to contact a reviewer reliably',
      '- Nothing stops someone reviewing the same product repeatedly under different names',
      'That last one is why moderation exists here at all: with no identity, every review needs a human to approve it.',
      '## What the customer module would give you',
      'Accounts with addresses, order history, customer groups — ✅ and groups matter commercially, because **price lists target them**. Wholesale pricing is a customer group plus a price list, not custom code.',
      '## Compared to WordPress',
      '⚠️ A WooCommerce customer **is** a WordPress user — one `wp_users` row, one identity for the shop and the blog.',
      'Here they are different things in different databases. A Payload user is an editor who logs into the CMS. A Medusa customer is someone who buys. **They cannot be the same row**, and if you need one identity across both you are building an identity layer in front of two systems — one of the genuinely hard parts of this architecture.',
      '## The three identities',
      'Worth being explicit, because it catches people:',
      '- **Payload user** — edits content, has an API key',
      '- **Medusa admin user** — manages commerce, gets a JWT',
      '- **Medusa customer** 🚫 — buys things, does not exist here',
      'Three credential systems, no shared table, no single sign-on.',
      '## If you added it',
      'Link reviews to customers through the same `defineLink` mechanism that already joins reviews to products, and keep the free-text fields for guests. Verified-purchase then becomes a query across the link and the order history.',
    ],
  },
  {
    title: 'Regions, currencies and tax',
    category: 'Commerce',
    status: 'published',
    excerpt:
      'One region is seeded and nothing reads it, yet it already decides whether a price appears at all.',
    tags: ['medusa', 'regions', 'tax', 'currency'],
    body: [
      '📋 **One region exists — "Europe", EUR, seven countries — and no code configures or reads it beyond pricing.** It still matters, because of what it controls.',
      '## What a region is',
      'A grouping of countries that share a currency, tax behaviour and permitted payment providers. It answers "what does this cost, including tax, and how can they pay".',
      '## The thing that catches everyone',
      '⚠️ **Without a region, the API returns no price at all.** Not zero — absent.',
      'Ask for products without a `region_id` and the variants come back with no `calculated_price` field. Nothing errors; the price is simply missing.',
      '> That is correct. Currency, tax inclusivity and price lists are all region-dependent, so Medusa refuses to guess rather than returning a number that might be wrong.',
      '✅ This repo resolves the single region once and reuses it. A multi-region storefront would pick the region from the visitor instead.',
      '## Tax-inclusive versus exclusive',
      'A real difference between markets. European prices usually include VAT; US prices usually exclude sales tax and add it at checkout.',
      'Medusa models this per region, so **the same product shows €120 in one and $100 plus tax in another** — without a second product or a plugin.',
      '⚠️ Medusa calculates tax but is not a tax service. Rates change, thresholds exist, digital goods have special rules. Real stores use a tax provider for the rates and Medusa for applying them.',
      '## Compared to WooCommerce',
      'Woo has tax classes, rates by location, and a multi-currency plugin bolted on. Medusa has regions as a core concept with currency, tax and payment providers attached.',
      'For one country Woo is simpler. For several, this is the part where Medusa pulls clearly ahead.',
    ],
  },
  {
    title: 'Price lists, promotions and sale pricing',
    category: 'Commerce',
    status: 'published',
    excerpt:
      'Neither is used here, and both solve problems that become custom code in WooCommerce. The distinction between them is the useful part.',
    tags: ['medusa', 'pricing', 'promotions'],
    body: [
      '🚫 **Zero price lists and zero promotions in this repo.** Both are core Medusa, and the difference between them is worth knowing.',
      '## Price lists override the price',
      'A price list says "for these products, these customers, during this window, the price is this instead".',
      'That covers sale pricing, wholesale tiers, contract pricing and member rates — **without touching the base price**. When the window ends, the base price is still there, unmodified.',
      '> The important part: you never overwrite the real price. Woo stores that run sales by editing prices lose the original, and getting it back is somebody\'s spreadsheet.',
      '## Promotions discount the cart',
      'A promotion applies at checkout — a code, a percentage, free shipping, buy-one-get-one, conditional on cart contents or customer group.',
      '## The distinction',
      '- **Price list** — changes *what a thing costs*, visible while browsing',
      '- **Promotion** — changes *what this order costs*, applied at checkout',
      'A sale badge on a product page is a price list. A discount code is a promotion. Using the wrong one produces either prices that do not show on the catalogue or discounts that cannot be conditional.',
      '## Compared to WooCommerce',
      'Woo has sale price as a product field and coupons as a post type. Sale price is one value — no scheduling beyond dates, no per-customer-group pricing without a plugin.',
      'Wholesale pricing in Woo is a paid plugin. Here it is a price list targeting a customer group — ✅ core, no extension.',
      '## What exists here',
      '**86 price rows** across 40 variants, in EUR and USD. ✅ That is base pricing, computed per region, and rendered on the product pages.',
      'No price lists, so no sale pricing. Adding one is configuration rather than code.',
    ],
  },
  {
    title: 'Products, variants and options, modelled properly',
    category: 'Commerce',
    status: 'published',
    excerpt:
      'Fifteen products and forty variants here. The modelling decision that matters is what a variant actually represents.',
    tags: ['medusa', 'products', 'variants'],
    body: [
      '✅ **Real and running.** 15 products, 40 variants, 86 prices — readable through the API and rendered on the product pages.',
      '## The three levels',
      '- **Product** — the thing conceptually. "Managed PostgreSQL".',
      '- **Option** — a dimension of choice. "Tier".',
      '- **Variant** — one specific combination, with its own SKU and price. "Production · 16 GB".',
      '## What a variant actually is',
      '> A variant is the thing with a price and a stock level. The product is a grouping.',
      'That is the decision. If two things can be bought at different prices, or stocked separately, they are variants — not two products.',
      '## The storage difference from WooCommerce',
      'Woo stores a product as a `wp_posts` row with everything else in `wp_postmeta`, and a variation as a **child post** with its own meta. Prices are meta values, so finding every product under €50 means querying a string column.',
      'Medusa has dedicated normalised tables. ⚠️ A variant has a real `product_id` **foreign key** — variants live inside the product module, where a foreign key is legal. The no-foreign-keys rule is about crossing *module* boundaries, not tables in general.',
      '## Options are not free text',
      '⚠️ An option declares its valid values, and a variant must use them. You cannot have a variant with "Lage" when the option says "Large" — the catalogue stays consistent by construction rather than by discipline.',
      '## Inventory is per variant, and optional',
      '✅ Here most variants set `manage_inventory: false`, because a subscription does not run out. Medusa then creates no inventory item at all, which is why the inventory table has 2 rows for a 15-product catalogue rather than 40.',
      'That is the right model for licences, and it mirrors Woo\'s "Manage stock?" checkbox with the same consequence: unchecked means no stock record exists to decrement.',
    ],
  },
]
