import type { Guide } from './types'

/** Content Modelling — 8 guides. */
export const contentModelling: Guide[] = [
  {
    title: 'What are Payload CMS collections?',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'A collection is the closest thing to a custom post type — except the config is the schema, and it builds the API, the admin UI and the types too.',
    tags: ['payload', 'collections', 'wordpress'],
    body: [
      'A **collection** is a type of document that Payload stores, manages and exposes. If you know WordPress, start from `register_post_type()` — that is the nearest idea.',
      '## What one collection gives you',
      'Declaring a collection in a single TypeScript file produces, with no further work:',
      '- Postgres tables matching the field list',
      '- A full REST API, with filtering, sorting, pagination and depth',
      '- A GraphQL API',
      '- Generated TypeScript types',
      '- An admin UI with forms, validation and list views',
      '- Access-control hooks for each of create, read, update and delete',
      'WordPress gives you the admin UI and a post type; the REST shape is generic and the fields need a plugin like ACF.',
      '## The collections here',
      'This project has five: `users`, `media`, `categories`, `posts` and `pages`. Every one is a file in `apps/cms/src/collections/` plus one entry in the `collections` array in `payload.config.ts`.',
      '## The big difference from register_post_type',
      '`register_post_type()` runs on the `init` hook, on **every request**, and any plugin can call it. Payload reads its `collections` array **once at boot** and compares it to the database.',
      '> That is why adding a collection needs a restart, and why no plugin can inject one at runtime.',
      'What you gain is that the schema is in version control. What you lose is runtime registration — there is no equivalent of a plugin adding a post type after the fact.',
      '## Fields are columns, not meta',
      'Another real difference. ACF stores every field as a row in `wp_postmeta`, keyed by name, all values as strings. A Payload field becomes a **typed column** — or, for arrays and blocks, its own table.',
      'So five collections here produce twenty-one tables. Relationships become foreign keys, arrays become child tables, and the database enforces shape rather than trusting the application.',
      '## Going deeper',
      'The content guide walks through creating one end to end, and the databases chapter explains exactly how five declarations became twenty-one tables.',
    ],
  },
  {
    title: 'How to create a new post type in Payload CMS',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'One file, one line in the config, and a restart. The equivalent of register_post_type, except the schema comes with it.',
    tags: ['payload', 'collections', 'tutorial'],
    body: [
      'In WordPress you call `register_post_type()` from a plugin or `functions.php`, then usually add ACF field groups to make it useful. Here it is one file.',
      '## The steps',
      '1. Create a file in `apps/cms/src/collections/`, for example `Testimonials.ts`, exporting a `CollectionConfig`.',
      '2. Give it a `slug`, an `admin.useAsTitle`, an `access` block and a `fields` array.',
      '3. Import it in `apps/cms/src/payload.config.ts` and add it to the `collections` array.',
      '4. **Restart the CMS.** The config is read at boot and is not hot-reloaded.',
      '5. Run `npm --prefix apps/cms run generate:types` to refresh `payload-types.ts`.',
      '## What to copy',
      'The smallest useful example in this repo is `Categories.ts` — a title field, a slug with a `beforeValidate` hook that derives it, and a description. It is about forty lines including comments.',
      '## What happens when you restart',
      'In development, Payload is running in `push` mode. It compares your config to the live database and applies the difference automatically — creating the table, its columns, its indexes and any relationship tables.',
      'You can watch it happen by counting tables in `payload_crud` before and after.',
      '> In production you would turn `push` off and use migration files instead, so that schema changes are reviewed and reversible.',
      '## The gotcha that costs an hour',
      '**A new collection 404s until you restart.** Editing a collection file hot-reloads fine, but adding one to the config array does not. The REST route simply does not exist yet, and the error gives no hint that a restart is what you need.',
      '## Slugs are not free',
      'If you add a `slug` field, make it `unique: true` and `index: true`, and derive it with the shared `slugFrom()` hook in `apps/cms/src/hooks/slugify.ts`. That hook only fills a slug when one is absent, so a hand-typed slug is never silently overwritten.',
      '## Going deeper',
      'The content guide has the full walkthrough with the before-and-after table counts.',
    ],
  },
  {
    title: 'How to add a custom field to posts',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'The ACF question. A field is a line of TypeScript, and it becomes a real column rather than a row in a meta table.',
    tags: ['payload', 'fields', 'acf'],
    body: [
      'With ACF you create a field group in the admin, bind it to a post type with location rules, and read it with `get_field()`. The value lands in `wp_postmeta` as a string.',
      'Here you add an object to the `fields` array in `apps/cms/src/collections/Posts.ts`, and it becomes a typed column.',
      '## The steps',
      '1. Open `apps/cms/src/collections/Posts.ts` and find the `fields` array.',
      '2. Add a field object with at least a `name` and a `type`.',
      '3. Save. The dev server hot-reloads and `push` mode applies the column.',
      '4. Run `npm --prefix apps/cms run generate:types`.',
      '5. The field appears in the admin, in the REST response and in the TypeScript types.',
      '## The field types you will use most',
      '- `text` — ACF Text',
      '- `textarea` — ACF Textarea',
      '- `number` — ACF Number',
      '- `select` with `options` — ACF Select',
      '- `checkbox` — ACF True/False',
      '- `date` — ACF Date Picker',
      '- `richText` — the WYSIWYG, but stored as a tree rather than HTML',
      '- `relationship` — ACF Relationship or Post Object',
      '- `upload` — ACF Image or File',
      '- `array` — ACF Repeater',
      '- `blocks` — ACF Flexible Content',
      '- `group` — ACF Group',
      '## Where it goes in the database',
      'Simple fields become columns on the `posts` table. An `array` field becomes **its own table** with a foreign key back to the post and an `_order` column. A `blocks` field becomes one table per block type.',
      '> This is the real difference from ACF. There is no key-value side table, so a field that is not in the config has nowhere to live — and orphaned meta from a plugin you removed years ago is not a thing that can happen.',
      '## Two useful admin options',
      "`admin: { position: 'sidebar' }` moves a field out of the main editing column, and `admin: { description: '…' }` adds help text under the input.",
      '## Going deeper',
      'The content guide shows the column appearing in psql before and after, and the databases chapter covers the array and block tables.',
    ],
  },
  {
    title: 'How to create a custom block and reuse it',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'The closest thing to ACF Flexible Content. Editors choose sections and order them; you own the markup each one renders.',
    tags: ['payload', 'blocks', 'elementor'],
    body: [
      'If you build pages with Elementor or ACF Flexible Content, this is the idea you already have: an editor assembles a page from a set of approved sections, in any order, as many times as they like.',
      'The closest equivalent is **ACF Flexible Content**, not Gutenberg.',
      '## How it works here',
      'A `blocks` field holds a list of block instances. Each block type is declared with a `slug` and its own `fields` array. `apps/cms/src/collections/Pages.ts` declares three: `hero`, `prose` and `stats`.',
      '## The steps',
      '1. Add a block object to the `blocks` array in the field config, with a `slug` and `fields`.',
      '2. Restart or let it hot-reload; `push` creates a table named after the block.',
      '3. In the admin, open a page, click **Add block** and pick the new type.',
      '4. In Astro, render it — see below.',
      '## The part that differs from Elementor',
      'Elementor composes in a visual builder and stores a JSON blob describing the layout, including styling. Here the editor picks **which** blocks and in **what order**, but a developer writes the component that renders each one.',
      '> The editor controls structure. You control markup. Nobody can inject a `<div>` soup into your templates, and nobody can change your CSS from the admin.',
      'The rendering lives in `apps/storefront/src/pages/pages/[slug].astro`, which loops the `layout` array and switches on `blockType`.',
      '## Reusable in which sense?',
      'A block type is reusable in that an editor can insert it any number of times, on any document with a `blocks` field. That covers most of what people mean.',
      'What it does **not** give you is one piece of content edited once and shown everywhere — a shared call-to-action, say. For that you want a **global**: exactly one record, no list view. The site settings global in this project is the live example, and its announcement banner renders on every page.',
      '## Going deeper',
      'The content guide covers both, including when to reach for a global instead of a block.',
    ],
  },
  {
    title: 'How to use field relationships and the depth parameter',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'Relationships are foreign keys, and depth controls how far Payload expands them. There is no WordPress equivalent for depth.',
    tags: ['payload', 'relationships', 'depth'],
    body: [
      'A `relationship` field links one document to another. In ACF terms it is the Relationship or Post Object field; in database terms it is a real foreign key, not a serialised post ID in a meta row.',
      '## Declaring one',
      "The `category` field on `posts` is the example in this project: `type: 'relationship'` with `relationTo: 'categories'`. Adding `hasMany: true` makes it a list, which becomes a join table.",
      '## Depth is the part with no WordPress analogue',
      'When you read a document, Payload has to decide whether a relationship comes back as an ID or as the whole related document. `depth` is that control.',
      '- `depth=0` — `category: 3`. Just the ID. One query.',
      '- `depth=1` — `category: { id: 3, name: "Frontend", slug: "frontend" }`. The document, joined.',
      '- `depth=2` — also expands relationships **inside** the category.',
      'The default is 2, which is usually more than you need.',
      '## How to choose',
      '- Use `depth=0` when you only need the ID — building a filter, or checking which category something is in. It is the cheapest read.',
      "- Use `depth=1` when you are rendering and need the related document's fields, such as showing a category name on a post card.",
      '- Use `depth=2` or higher only when you genuinely need a relationship of a relationship, and expect it to cost you.',
      '> Every level of depth is more joins and a larger response. On a list of fifty posts, the difference between depth 0 and depth 2 is substantial.',
      '## The upload field behaves the same way',
      '`coverImage` is an `upload` relationship to the `media` collection. At `depth=0` you get the media ID; at `depth=1` you get the document including `url` and the generated `thumbnail` and `card` sizes. Rendering an image therefore needs at least depth 1.',
      '## A practical default',
      "This project's post list uses `depth: 1` and the single post page uses the same. Nothing needs more.",
      '## Going deeper',
      'The data guide has a section on choosing depth, with the response sizes side by side.',
    ],
  },
  {
    title: 'How to create a page and render it in Astro',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'In WordPress one act creates the content and its URL. Here they are two jobs in two services, and understanding that split is the whole lesson.',
    tags: ['payload', 'astro', 'pages'],
    body: [
      'This is the question where the stack feels most unfamiliar, because "create a page" means two different things.',
      'In WordPress, adding a page in the admin creates both the content **and** its URL. The rewrite layer and the template hierarchy take care of the rest.',
      'Here those are separate. Payload stores the content. Astro decides the URL and renders it. Neither knows about the other.',
      '## Part one — the content',
      '1. Open the CMS admin on port 3000 and choose **Pages**.',
      '2. Click **Create new**, give it a title, and leave the slug blank — it derives from the title.',
      '3. Add blocks to the `layout` field: a hero, some prose, a stats row.',
      '4. Save.',
      'You can do the same over the REST API with a POST to `/api/pages`, sending the `layout` array as JSON.',
      '## Part two — the URL',
      'The page is now in the database but no URL serves it until a route exists. In this project that route is already there: `apps/storefront/src/pages/pages/[slug].astro`.',
      'That one file serves **every** page document. The `[slug]` part is a parameter; the frontmatter reads it, fetches the matching document from Payload, and renders each block.',
      '> One file, any number of pages. You do not add a route per page, which is the thing that trips people up coming from a per-template mental model.',
      '## Why it is split this way',
      'Because the storefront is a separate application that reaches Payload over HTTP. It has no database access at all. That constraint is what lets you replace the frontend without touching the CMS, and serve the same content to a mobile app.',
      '## If nothing renders',
      'Check the slug matches, and check the document is **published** rather than draft. The read access rule narrows anonymous queries to published documents, so a draft is not hidden — it genuinely does not exist as far as an anonymous request is concerned.',
      '## Going deeper',
      'The content guide covers the Payload half and the frontend guide covers the routing half.',
    ],
  },
  {
    title: 'How to create a post in Payload CMS',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'Through the admin, or over the REST API with an API key. Both paths, and the header format that catches everyone.',
    tags: ['payload', 'posts', 'rest'],
    body: [
      'Posts are the collection you will touch most. Creating one works the way you expect; the API path has one surprise.',
      '## Through the admin',
      '1. Open port 3000, log in, choose **Posts**.',
      '2. Click **Create new**.',
      '3. Fill in the title. Leave the slug blank and it is derived.',
      '4. Write the body in the rich-text editor, choose a category, add tags.',
      '5. Use **Save draft** or **Publish** — the status control is in the sidebar.',
      '## Over the REST API',
      'POST to `/api/posts` with a JSON body. Only `title` is strictly required.',
      'The authentication header is the surprise:',
      '> `Authorization: users API-Key <key>` — the collection slug, then a literal space, then `API-Key`, then the key. **Not** `Bearer`.',
      'That format catches almost everyone once. A wrong header gives a 403 that looks like a permissions problem rather than a syntax problem.',
      '## Draft or published',
      'Send `"_status": "published"` to publish immediately; omit it and the `beforeChange` hook defaults the post to a draft. The same hook stamps `publishedAt` the first time a post actually goes live, and leaves it alone afterwards.',
      '## Field limits worth knowing',
      '- `title` — required, maximum 200 characters',
      '- `excerpt` — optional, maximum 300 characters',
      '- `slug` — unique and indexed, so two posts whose titles reduce to the same slug will collide',
      'That last one is a real constraint when you write a series of similarly-named guides.',
      '## Drafts keep versions',
      'The posts collection has `versions: { drafts: true, maxPerDoc: 10 }`, so every save writes a version row. That is why there is a `_posts_v` table alongside `posts`, and why the count in it grows faster than the post count.',
      '## Going deeper',
      'The content guide covers both paths with runnable commands, and the data guide covers reading posts back.',
    ],
  },
  {
    title: 'How to add user roles and control access',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'The Advanced Access Manager question. There is no capability registry here — access is four functions per collection, and one of them can return a query.',
    tags: ['payload', 'access', 'security'],
    body: [
      'In WordPress, roles are rows in `wp_options` holding capability maps, any plugin can add a capability at runtime, and you gate behaviour with `current_user_can()`. Plugins like Advanced Access Manager give you a UI over all of it.',
      'This stack has nothing resembling that, and the replacement is smaller and stricter.',
      '## Roles are a field',
      'The `users` collection has a `role` select field with two options, `admin` and `editor`. That list is TypeScript, not data — adding a third role is a code change and a deploy, not an admin screen.',
      '## Access is four functions',
      'Every collection declares `access` with up to four keys: `create`, `read`, `update` and `delete`. Each is a function receiving the request, returning either a boolean or — and this is the interesting part — a query.',
      "In this project, delete on posts is `req.user?.role === 'admin'`. Straightforward.",
      '## The idea worth stealing',
      'A `read` function can return a **`Where` query** instead of true or false. Payload merges it into the SQL.',
      "The posts collection does exactly this: a logged-in user gets `true`, and anonymous gets `{ _status: { equals: 'published' } }`.",
      '> Drafts are not *forbidden* to anonymous readers. They do not exist. The count comes back lower, pagination adjusts, and there is no 403 to leak that something was hidden.',
      'In WordPress the equivalent is combining `current_user_can()` with a `pre_get_posts` filter — two mechanisms, applied in two places, that can disagree. Here it is one function.',
      '## What you do not get',
      '- No capability registry, no `add_cap`, no per-user overrides',
      '- No role editor in the admin',
      '- No way for external code to grant itself access',
      'The unit of authorisation is an operation on a collection, and there are exactly four of them.',
      '## And a warning',
      "The **storefront has no authentication at all**. Anyone who can reach it can call any of its endpoints. Payload's access control protects Payload; it does not protect a frontend that holds an admin-capable API key.",
      '## Going deeper',
      'The Payload chapter covers access control in depth, and the production chapter covers the missing storefront auth.',
    ],
  },
  {
    title: 'How drafts and versions actually work',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'One config line creates a second table, doubles your row count and changes what anonymous readers can see. Worth understanding before you enable it everywhere.',
    tags: ['payload', 'drafts', 'versions'],
    body: [
      '✅ **Posts have drafts; Pages deliberately do not.** That contrast is in the repo on purpose.',
      '## What one line buys',
      'Setting `versions: { drafts: true, maxPerDoc: 10 }` on a collection gives you a `_status` field of `draft` or `published`, a version row on every save, and the ability to publish later.',
      '## The cost, in tables',
      '⚠️ **It creates a second table.** Posts get `_posts_v`, and every save writes a row there. Array sub-tables are duplicated too — `posts_tags` gains `_posts_v_version_tags`.',
      'That is why this repo has twenty-one tables from five collections, and why the version table grows faster than the post table.',
      '`maxPerDoc: 10` caps it. Without a cap, a frequently-edited document accumulates versions forever.',
      '## How it changes reads',
      "This is the part people miss. The posts collection's read rule returns `true` for a logged-in user and a **query** otherwise — narrowing anonymous reads to published documents.",
      '> A draft is not forbidden to an anonymous reader. It does not exist. The count comes back lower and there is no 403 to reveal that something was hidden.',
      '✅ Request a draft slug anonymously and you get a page saying "Not published" — with a 200, because the storefront looks again with the API key and reports honestly rather than pretending the post is missing.',
      '## The publishedAt trap',
      '⚠️ A `beforeChange` hook stamps `publishedAt` the first time a post goes live, **only if it is empty**. Seed content that does not set it explicitly gets timestamps milliseconds apart, and sorting by publish date becomes arbitrary.',
      '## When to skip drafts',
      '**Reach for drafts when** content is edited over time by people who need to save work in progress.',
      '**Skip them when** the document is structural rather than editorial — Pages here has none, because a half-finished landing page is not a useful idea.',
    ],
  },
  {
    title: 'Changing a model that already has data',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'Adding a field is easy. Renaming one, making it required, or dropping it are three different problems, and the third is irreversible.',
    tags: ['migrations', 'schema', 'payload', 'medusa'],
    body: [
      'Both backends make adding a field trivial. The interesting cases are the other ones.',
      '## Adding is safe',
      'A new nullable column is backwards-compatible: existing rows get null, old code ignores it. Payload applies it on save in dev; Medusa needs `db:generate` then `db:migrate`.',
      '## Making a field required is not',
      '⚠️ Existing rows have no value, so the constraint fails against real data. The safe sequence is three deploys:',
      '1. Add it nullable',
      '2. Backfill every existing row',
      '3. Add the constraint',
      'This is the **expand and contract** pattern, and it is how you make any breaking schema change without downtime.',
      '## Renaming is two columns, not one',
      'A rename is a drop plus an add as far as the database is concerned, and the data does not follow. Expand and contract again: add the new name, write to both, backfill, switch reads, then drop the old one.',
      '## Dropping is irreversible',
      '> A migration that drops a column is the only one you cannot undo by running it backwards. The data is gone.',
      '⚠️ **Payload in `push` mode will do this silently.** It diffs the config against the database and applies the difference — including removing a column you deleted from the config. In development that is convenient. In production it is why `push: false` is the first item in the production checklist.',
      '## Two databases, two migration histories',
      '⚠️ They migrate **independently**. There is no ordering between a Payload change and a Medusa change, and no transaction spanning both. If a feature needs both, deploy them so that either order works.',
      '## The rule',
      'Test every migration against a **copy of production data**, not against seed data. Seed data is small, clean and recent; production data has every edge case someone created in 2019.',
    ],
  },
  {
    title: 'Modelling data that spans both databases',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'A product description lives in Medusa and marketing copy lives in Payload. There is no foreign key between them, so you need a different discipline.',
    tags: ['architecture', 'modelling', 'consistency'],
    body: [
      'Eventually you want editorial content attached to a commerce object, and discover there is no mechanism for it.',
      '## The decision rule',
      '> Ask which service would still need this data if the others were deleted.',
      '- A blog post — Payload. Commerce does not care.',
      '- Stock level — Medusa. The CMS has no business knowing.',
      '- A product **description** — Medusa, because the catalogue is incomplete without it.',
      '- A **landing page about** a product — Payload, because it is editorial.',
      'That last pair is the interesting one, and it is where people put data in the wrong place.',
      '## Referencing across the boundary',
      'When Payload content must point at a Medusa product, store the **handle or id as a plain text field**. Not a relationship — Payload cannot have a relationship to something in another database.',
      '⚠️ **Nothing enforces that the reference is valid.** Delete the product and the Payload document still holds the handle, and nothing tells you. This is the cost of two databases, and there is no way around it.',
      '## So handle it deliberately',
      '- **Render defensively.** If the product fetch returns nothing, show the content without the commerce part rather than 500.',
      '- **Reconcile periodically.** A scheduled job that checks every reference still resolves, and reports the ones that do not.',
      '- **Prefer handles to ids** for human-maintained references. A handle is legible in the admin; `prod_01M4...` is not.',
      '## What this buys',
      'The alternative is one database and one program, where a foreign key solves it — which is WordPress, and is genuinely simpler. You chose two databases for independent deployment and scaling. Dangling references are the bill for that.',
      'Chapter 6 of the WordPress track works through what breaks if you put reviews in Payload instead.',
    ],
  },
  {
    title: 'Globals versus collections, and when to use each',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'A global is a collection with exactly one row. That sounds like a shortcut and is actually a different data model with different consequences.',
    tags: ['payload', 'globals', 'modelling'],
    body: [
      '✅ This repo has five collections and one global, `SiteSettings`. The split is worth getting right early, because converting later means a migration.',
      '## The distinction',
      'A **collection** holds many documents, each with an id and its own URL. A **global** holds exactly one document, with no id and no list view.',
      'In WordPress terms: collections are post types, globals are the options table — but typed, versioned, and with access control.',
      '## Use a global when there is exactly one, forever',
      'Site title, the announcement banner, a footer, default SEO, a maintenance flag. ✅ `SiteSettings` here holds the site title and the announcement shown on the home page.',
      '> The test: would a second one ever make sense? If "a second footer" is meaningless, it is a global. If it is meaningless *today* but plausible next year, make it a collection with one row.',
      '## Use a collection when there could ever be two',
      'Navigation menus feel like a global and usually should not be. Primary, footer, mobile — that is three, and a collection from the start costs nothing.',
      '⚠️ **Converting a global to a collection is a migration, not a refactor.** Different table shape, and every query and template that reads it changes.',
      '## What globals give up',
      '- No list view, no pagination, no filtering',
      '- No per-document access control — the rules apply to the one document',
      '- No relationship *to* a global; relationships point at collections',
      'That last one catches people. If something needs to be referenced by other documents, it must be a collection.',
      '## Reading one',
      'The REST path is `/api/globals/site-settings`, not `/api/site-settings`. ⚠️ Easy to get wrong, and the 404 does not explain itself.',
      '✅ Globals support drafts and versions exactly like collections, so a banner change can be previewed before it goes live.',
    ],
  },
  {
    title: 'The Lexical editor, and what reaches the page',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'Payload stores rich text as a JSON node tree, not HTML. That decision is why the storefront needs a renderer, and why XSS escaping is testable.',
    tags: ['payload', 'lexical', 'rich-text'],
    body: [
      'The single biggest surprise coming from the WordPress editor: **`content` is not HTML**. It is a tree of typed nodes stored as JSON.',
      '## What the shape looks like',
      'A root with children. Each child has a `type` — `paragraph`, `heading`, `list`, `quote`, `link` — and text nodes carry a `format` **bitmask**: 1 is bold, 2 italic, 16 code. Combinations are sums, so bold code is 17.',
      '## Why store a tree',
      'Because HTML in a database is a decision you cannot revisit. A tree can be rendered to HTML, to plain text for search indexing, to a native mobile view, or transformed before output.',
      '> It also means no one can paste a `<script>` into your content and have it execute, because nothing stores raw markup in the first place.',
      '## The cost: you must render it',
      '✅ `apps/storefront/src/lib/lexical.ts` walks the tree and emits HTML. It is one switch over node types, and ⚠️ **a node type not in that switch renders as nothing** — silently.',
      'That is the bug to expect. Enable a feature in the editor, use it, and the content disappears from the storefront with no error anywhere. The fix is always the same: add the case.',
      '## Why this repo has no fenced code blocks',
      '✅ A concrete instance of exactly that. Lexical has a `code` node; the renderer does not handle it; so the seeded guides use inline code only. Rather than half-render it, the format is documented as not supporting it.',
      "## Escaping is the renderer's job",
      '✅ Every text node and every link `href` is escaped on the way out, and that escaping is **unit-tested** — three of the twenty unit tests exist for it, including one asserting a `javascript:` href cannot be injected raw.',
      '⚠️ The output is inserted with `set:html`, which does no escaping of its own. The safety lives entirely in the converter, which is precisely why it is the part with tests.',
      '## Configuring it',
      '`lexicalEditor()` with no arguments gives the default feature set. 📋 Passing a `features` array adds or removes them — and anything added needs a matching case in the renderer first, or you ship an editor button that produces invisible content.',
    ],
  },
  {
    title: 'Uploads, image sizes and where the files actually go',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      "One upload becomes three files on disk and one row in the database. Knowing which is which explains the repo's most persistent bug.",
    tags: ['payload', 'uploads', 'media', 'images'],
    body: [
      '✅ `Media.ts` is the only collection with `upload`, and the seed is the only thing that has ever exercised it — 103 covers, generated locally and uploaded through the Local API.',
      '## One upload, three files',
      'The config declares two `imageSizes`:',
      '- **`thumbnail`** — 400×300, centre crop',
      '- **`card`** — 768×512, centre crop',
      'Payload keeps the original and generates both with sharp. ✅ **103 documents, 309 files.** That ratio is exact and worth remembering when a directory listing looks alarming.',
      '## Metadata in Postgres, bytes on disk',
      'The `media` row holds filename, mime type, dimensions, alt text and the size variants. The bytes live in `staticDir`, which is `public/media`.',
      '> This split is the same one WordPress makes, and it has the same consequence: **a database backup is not a backup.** Restore the dump alone and every image is a broken link.',
      '## The bug this caused',
      '⚠️ `db:reset` wipes the database and **not the disk**. The seed then re-uploaded the same filenames, Payload refused to overwrite and appended `-1`, then `-2`. The directory doubled on every reset while the database correctly reported one image each.',
      '✅ Fixed by clearing the directory in the seed. It now converges at 309 files however many times it runs — which the re-seed check verifies rather than assumes.',
      '## Requesting the right size',
      "`imageUrl(post.coverImage, 'thumbnail')` picks a variant. ⚠️ **At `depth=0` the field is a number**, so the helper returns null and no image renders, with no error. If an image silently fails to appear, check the depth before anything else.",
      '## Production',
      "📋 `public/media` on a server's filesystem means a container rebuild loses every upload. `@payloadcms/storage-s3` points the same field at object storage and changes no template code. Until then, the media directory must be in your backups — ✅ `npm run db:export` already tars it.",
    ],
  },
  {
    title: 'Conditional fields, validation and a usable admin',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'A form with thirty always-visible fields is a form nobody fills in correctly. Payload makes the fix declarative, and it costs almost nothing.',
    tags: ['payload', 'admin', 'validation', 'ux'],
    body: [
      'The admin UI is generated from your config, so improving it means improving the config. There is no template to override.',
      '## Conditional fields',
      '`admin.condition` is a function receiving the whole document and the sibling data, returning a boolean. False means the field is not rendered.',
      'Typical use: a `layout` select, and three different field groups that appear depending on the choice. The editor sees four fields instead of fourteen.',
      '⚠️ **A hidden field is not a protected field.** `condition` is presentation only — the API still accepts the value. Anything that must not be set belongs behind **access control**, which is enforced server-side.',
      '## Validation',
      '`required: true` covers most of it. Beyond that, a `validate` function returns `true` or an error string, and the string is shown to the editor.',
      '> Write the message as advice, not as a diagnosis. "Must be under 300 characters" is useful; "Invalid value" is not.',
      "✅ The excerpt limit here is enforced in two places — the collection and the storefront's zod schema — and ⚠️ **they must be changed together.** Divergence means content that saves in the admin and is rejected by the storefront.",
      '## The small things that matter most',
      '- `admin.description` — one line under the field. The cheapest documentation there is, because it appears where the question is asked',
      "- `admin.position: 'sidebar'` — moves metadata out of the editing flow. Slug, category, cover, publish date all live there",
      '- `admin.useAsTitle` — what the list view shows. Without it you get an id column and an unreadable list',
      '- `labels` on arrays — "Add Tag" rather than "Add Row"',
      '## Grouping',
      '📋 `group` nests fields under one heading **without creating a table**, unlike an array. Collapsible rows and tabs are the next step up for a genuinely large model.',
      '> You are the only person who will ever read the config. Everyone else experiences it as the form. Spending ten minutes on descriptions and sidebar placement is the highest-leverage work in the whole collection.',
    ],
  },
  {
    title: 'The full hook lifecycle, field and collection',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'Two levels, six moments, and one rule that decides between them. Picking the wrong one produces code that works until it is called from somewhere else.',
    tags: ['payload', 'hooks', 'lifecycle'],
    body: [
      "Hooks are Payload's answer to WordPress actions and filters, with one large difference: **they are typed and attached to the thing they affect**, not registered globally by name.",
      '## Two levels',
      "**Field hooks** see one value plus the surrounding document. ✅ `slugFrom('title')` in `src/hooks/slugify.ts` is one — it derives the slug and knows nothing about the collection.",
      '**Collection hooks** see the whole document and the request. ✅ `Posts.ts` has three.',
      '> The rule: if the logic concerns one field, make it a field hook. It then travels with the field when you copy it to another collection, instead of being left behind in a config somewhere.',
      '## The order they run in',
      '1. **`beforeValidate`** — normalise input. Slug generation lives here, because validation must see the final value',
      '2. **`beforeChange`** — last chance to rewrite the document. ✅ Stamps `publishedAt` when a post first goes live',
      '3. *the write happens*',
      '4. **`afterChange`** — the write has committed. ✅ Logs here; this is where a cache purge or a webhook belongs',
      '5. **`afterRead`** — shape data on the way out',
      '6. **`beforeDelete` / `afterDelete`** — ✅ `afterDelete` logs the removal',
      '## Why `afterChange` is the interesting one',
      'It runs **after the transaction commits**, so the data is really there. That makes it right for anything touching the outside world — purging a CDN, posting to a queue, notifying a search index.',
      '⚠️ **It cannot fail the write.** Throwing in `afterChange` does not undo anything; the document is already saved. If something must be able to abort the operation, it belongs in `beforeChange`.',
      '## The trap',
      '⚠️ **Hooks run on every write, including seeds, migrations and the Local API.** A hook that calls an external service will call it 103 times during a seed, and if that service is down the seed fails for a reason unrelated to the data.',
      'Guard on `operation`, on `req.context`, or on an environment flag. The seed in this repo is noisy in the logs precisely because the hooks fire — which is useful as a demonstration and would be unacceptable if they did real work.',
    ],
  },
  {
    title: 'Local API, REST and GraphQL — three ways in',
    category: 'Content Modelling',
    status: 'published',
    excerpt:
      'The same operations through three interfaces with different security models. One of them bypasses access control entirely by design.',
    tags: ['payload', 'api', 'local-api', 'graphql'],
    body: [
      'Payload exposes every collection three ways from one config. Choosing between them is mostly a question of **where your code runs**.',
      '## The Local API — in-process, no HTTP',
      "`payload.create({ collection: 'posts', data })`. A direct function call: no network, no serialisation, no auth header.",
      '⚠️ **It bypasses access control by default.** There is no user, so there is nothing to check. That is correct for a seed script and catastrophic in a request handler that forgot to pass `overrideAccess: false` and a `user`.',
      '✅ The seed uses it, which is why it can create 103 posts and three drafts without ever authenticating.',
      '> Rule: the Local API is for code you wrote that runs inside Payload. The moment a request from outside drives it, you must pass the user.',
      '## REST — what the storefront uses',
      '`/api/posts?limit=20&page=1&depth=1&sort=order`. Generated from the config; no controller written on either side.',
      '`where` is bracketed query params: `?where[title][contains]=astro`. Verbose, and ✅ it is a structured filter rather than a SQL fragment, so it is parameterised and cannot be injected.',
      'Auth is `Authorization: users API-Key <key>` — ⚠️ the collection slug, a space, `API-Key`, then the key. **Not `Bearer`.** This catches everyone exactly once.',
      '## GraphQL — generated and unused here',
      '📋 `/api/graphql`, with a schema generated from the same collections. 🚫 **Nothing in this repo calls it.**',
      'It earns its place when a client needs several unrelated things in one round trip, or when different screens need different field subsets from one endpoint. For a server-rendered storefront that can simply make two REST calls, it mostly adds a schema to maintain.',
      '## Choosing',
      '- Inside Payload → **Local API**, and be deliberate about access',
      '- Another service over the network → **REST**',
      '- A client fetching varied shapes, or over-fetching is measurably hurting → **GraphQL**',
      '✅ `select` narrows fields and `depth` controls relationship expansion. Together they close most of the gap REST is criticised for.',
    ],
  },
]
