import type { Guide } from './types'

/** Data & APIs — 3 guides. */
export const dataAndApis: Guide[] = [
  {
    title: 'How to fetch and display data from Payload and Medusa',
    category: 'Data & APIs',
    status: 'published',
    excerpt:
      'One rule governs everything: Astro has no database. Every read is an HTTP request to the service that owns the data.',
    tags: ['data', 'rest', 'astro'],
    body: [
      'This is the adjustment that matters most coming from WordPress. `WP_Query` talks to MySQL directly. **Astro cannot talk to a database at all.**',
      'Every read is an HTTP request to whichever service owns that data. Payload owns content; Medusa owns commerce and reviews; Astro owns nothing.',
      '## Reading Payload content',
      'Call `/api/posts` with query parameters. The ones you will use:',
      '- `where[field][operator]=value` — filtering, the `WP_Query` meta/tax query equivalent',
      '- `sort=-publishedAt` — ordering, with a leading minus for descending',
      '- `limit` and `page` — pagination',
      '- `depth` — how far to expand relationships',
      '- `select` — which fields to return',
      'The response is an envelope with `docs` plus pagination metadata.',
      '## Reading Medusa data',
      'Medusa\'s store API needs a publishable key header on every request. Without it you get a 400, not a 401, which is confusing the first time.',
      'The storefront uses the official JS SDK for built-in resources and plain fetch for the custom review routes.',
      '## Reading across two modules',
      'Reviews live in a custom module and products live in Medusa\'s. A module cannot join to another module, so the route that returns a product with its reviews uses `query.graph` and the link table.',
      '> You never write that JOIN yourself. You declare a link once, and the query layer resolves it.',
      '## Inside an Astro page',
      'Do the fetching in the frontmatter, which runs on the server. The dashboard in this project fires five backend calls in a single `Promise.all`, each wrapped so one failure does not blank the page.',
      'That pattern matters: if Medusa is down, the Payload panels should still render, and the broken one should say why.',
      '## The N+1 worth seeing',
      'The products page makes one request for the product list, then one more per product to get its reviews. It is labelled on the page rather than hidden, because recognising the shape is the lesson.',
      '## Going deeper',
      'The data guide covers all of this with runnable commands and the full query-parameter table.',
    ],
  },
  {
    title: 'How to add and insert data across the stack',
    category: 'Data & APIs',
    status: 'published',
    excerpt:
      'Three ways to write: a form with no JavaScript, a typed Action, or your own endpoint. This project ships all three.',
    tags: ['data', 'actions', 'forms'],
    body: [
      'Writing data has more moving parts than reading it, because of validation, credentials and the fact that two different backends disagree about HTTP verbs.',
      '## Option one — an Astro Action',
      'An Action is a typed server function with a zod schema. Point a form at it and it works **with JavaScript disabled**, because it posts to the page URL and the server handles it.',
      'This project has three, all for posts: create, update and delete. Validation errors come back per field, so the form can show a message under the offending input.',
      'The nearest WordPress equivalent is `admin-post.php` — a form posting to a handler — but typed, validated, and without a global router every plugin registers into.',
      '## Option two — your own REST endpoint',
      'A `.ts` file under `src/pages/api/` exporting `POST`. This project uses endpoints for reviews, deliberately, so the two patterns sit side by side.',
      'Use an endpoint when something other than your own form needs to call it: another service, a mobile app, curl.',
      '## Option three — straight to the backend',
      'POST to Payload\'s `/api/posts` with the API key header, or to Medusa\'s store API with the publishable key. Useful for scripts and for understanding the wire format.',
      '> The Payload header is `Authorization: users API-Key <key>`, not `Bearer`. That is the single most common mistake.',
      '## Update is where the backends disagree',
      'Payload updates with `PATCH`. Medusa\'s admin API updates with `POST`. Neither is wrong; they are different conventions.',
      'The storefront hides that: its own endpoint accepts `PATCH` and translates. Your pages call one function and never learn which backend wanted what — which is precisely the job of a backend-for-frontend layer.',
      '## Writes that run workflows',
      'Creating a review does not just insert a row. It runs a Medusa workflow: validate the product, insert the review, write the link row, emit an event. If any step fails, the completed steps are undone.',
      'So a failed review creation leaves **nothing** behind — no orphan row, no dangling link.',
      '## Going deeper',
      'The data guide covers all three paths with runnable examples, including the form that works without JavaScript.',
    ],
  },
  {
    title: 'How to delete data, and why some rows survive',
    category: 'Data & APIs',
    status: 'published',
    excerpt:
      'Payload deletes rows. Medusa marks them deleted. Knowing which is which changes how you read every count.',
    tags: ['data', 'soft-delete', 'medusa'],
    body: [
      'Deleting looks simple until you notice the two backends mean different things by it.',
      '## Payload — the row is gone',
      '`DELETE /api/posts/:id` removes the row. There is no trash, no `wp_trash_post` equivalent, no thirty-day window. Version rows in `_posts_v` go with it.',
      'If you want a trash, model it: add a status field and filter on it. Nothing gives it to you.',
      '## Medusa — the row stays',
      'Deleting a review is a **soft delete**. The row remains in the table with `deleted_at` set to a timestamp, and the normal list queries exclude it.',
      'You can prove it: count rows, delete one, count again. The total is unchanged; only the live count drops.',
      '> This is closer to WordPress\'s trash than Payload is, but it is invisible rather than a screen you visit.',
      '## Why that matters for counting',
      'Any `select count(*) from review` includes deleted rows. If your numbers look too high, that is usually why. Filter on `deleted_at is null` to get the live count.',
      '## The link row outlives the review',
      'When a review is soft-deleted, its row in the product-to-review link table **stays**. That is deliberate: restoring the review reattaches it without rebuilding the relationship.',
      'The consequence is that a query joining products to reviews can return gaps where a soft-deleted review used to be. Every reader in this project filters those out, and the comment above each one explains why.',
      '## The 403 you will hit first',
      'A `DELETE` to the storefront without an `Origin` header returns **403 before any of your code runs**. That is Astro\'s built-in origin check, a CSRF protection enabled by default for server-rendered sites.',
      'Add a matching `Origin` header and the same request works. Browsers set it automatically, so this only bites from curl.',
      '> Because it runs upstream of middleware, those rejected requests never appear in the request log. A tool can only log what reaches it.',
      '## Going deeper',
      'The data guide proves the soft delete with psql counts before and after.',
    ],
  },
  {
    title: 'Pagination, and the envelope Payload already gives you',
    category: 'Data & APIs',
    status: 'published',
    excerpt:
      'Payload returns more pagination metadata than WP_Query does without extra work. The mistake is fetching a large limit and never paging at all.',
    tags: ['pagination', 'payload', 'api'],
    body: [
      'A list endpoint without pagination works until the list grows, and then fails quietly rather than loudly.',
      '## What you get',
      'Payload returns an **envelope**, not a bare array: `docs` plus `totalDocs`, `totalPages`, `page`, `hasNextPage`, `hasPrevPage`, `nextPage` and `prevPage`.',
      'That is everything a pager needs, and more than `WP_Query` hands you without calling additional functions.',
      '## The failure mode worth seeing',
      '⚠️ This repo had exactly this bug. The posts page fetched `limit: 50` with no pager. At 32 guides it looked fine. At 88 it would have shown 50 and **silently hidden 38** — while still printing the true total on the page.',
      '> A truncated list with an accurate count is worse than either showing everything or paging properly, because nothing looks wrong.',
      '## Doing it server-side',
      'Read the page from the query string, pass it through, render links from `totalPages`. ✅ The client already accepts `page`, `categoryId` and `search` — no new code was needed, only the UI.',
      'Keeping it in the query string means it works without JavaScript and every view is a URL you can share or bookmark.',
      '## Offset pagination has a catch',
      '⚠️ **It is unstable under writes.** If a document is inserted while someone pages, a row can shift between pages and be seen twice or missed. For a blog archive that is harmless. For anything being actively written, cursor pagination is the correct answer.',
      '## Cost',
      'Each page is a query with `LIMIT` and `OFFSET`. ⚠️ **Large offsets get slow**, because the database walks and discards the skipped rows. Page 500 is genuinely more expensive than page 2 — another reason cursors win at scale.',
      '## The rule',
      'Never fetch an unbounded list. Pick a limit you can defend and page past it.',
    ],
  },
  {
    title: 'Webhooks, inbound and outbound',
    category: 'Data & APIs',
    status: 'published',
    excerpt:
      'Neither exists here, and both arrive the moment you add a payment provider. The security requirements are not optional.',
    tags: ['webhooks', 'integration', 'security'],
    body: [
      '🚫 **Nothing in this repo sends or receives a webhook.** It becomes relevant immediately once a third party is involved.',
      '## Inbound: someone calls you',
      'Stripe is the usual first one. A payment succeeds, Stripe calls your endpoint, you mark the order paid.',
      '⚠️ **This is a public, unauthenticated endpoint that changes your data.** Three things are mandatory, not optional:',
      '**1. Verify the signature.** Providers sign the payload with a shared secret. Without verification anyone who finds the URL can mark orders paid.',
      '**2. Be idempotent.** Webhooks are **at-least-once**. The same event will arrive twice, and processing it twice must not charge twice. Store the event id and ignore repeats.',
      '**3. Respond fast, process later.** Return 200 immediately and queue the work. Providers time out and retry, and a slow handler turns one event into several.',
      '## Outbound: you call someone',
      'Content changed, tell another system. ✅ The seam already exists — `Posts.afterChange` currently only logs, and the comment says plainly that it is where this belongs.',
      '⚠️ **Do not call out synchronously from a hook.** If the receiver is slow, your save is slow. If it is down, your save fails. Emit an event, handle it in a subscriber.',
      'Medusa already works this way: the review workflow emits `review.created` and a subscriber reacts. That is the shape to copy.',
      '## The guarantee nobody reads',
      '> At-least-once delivery means duplicates are normal, not exceptional.',
      'Every consumer needs to be idempotent. Designing for exactly-once and receiving twice is the most common webhook bug there is.',
      '## Where it would live here',
      'Inbound Stripe webhooks belong on **Medusa**, not Astro — the secret lives there, and so does the order. Astro is a frontend and has no business holding a payment secret.',
    ],
  },
  {
    title: 'The GraphQL API nobody here uses',
    category: 'Data & APIs',
    status: 'published',
    excerpt:
      'Payload generates a full GraphQL schema from the same config that builds the REST API. Not one line of this project touches it.',
    tags: ['graphql', 'payload', 'api'],
    body: [
      '📋 **It exists and is unused.** Declaring a collection gives you REST, TypeScript types, an admin UI **and** a GraphQL schema. This repo uses the first three.',
      '## What it would give you',
      '**Exactly the fields you ask for.** REST with `depth=1` returns whole related documents; GraphQL returns the three fields you name. On a list of fifty posts that is a materially smaller response.',
      '**One request for several resources.** Posts and categories and the site settings in a single round trip, rather than three.',
      'That second point is interesting here specifically, because the dashboard makes five backend calls per render.',
      '## Why REST is still the right default for this app',
      '- The storefront is server-side, so the round trips are server-to-server on a fast network — the latency GraphQL saves is cheapest here',
      '- REST is trivially inspectable with curl, which matters enormously in a teaching repo',
      '- Caching is simpler: a GET URL is a cache key, where a POSTed GraphQL query is not',
      '- ⚠️ **Medusa does not expose GraphQL**, so you would have two query styles for two backends',
      '## When it would earn its place',
      '**Reach for GraphQL when** a mobile client on a slow network needs to minimise both round trips and payload size, or when many different consumers want different shapes of the same data.',
      '**Stay on REST when** your main consumer is your own server-rendered frontend, which is this case.',
      '## Worth doing once',
      'Open Payload\'s GraphQL playground and run a query. Seeing the same data through a second generated interface makes the config-is-the-application idea concrete in a way reading about it does not.',
    ],
  },
  {
    title: 'Bulk operations, imports and exports',
    category: 'Data & APIs',
    status: 'published',
    excerpt:
      'Both backends are built for one document at a time. Moving a thousand is a different problem, and the seed scripts are the worked example.',
    tags: ['bulk', 'import', 'data'],
    body: [
      'Sooner or later someone hands you a spreadsheet.',
      '## What exists ✅',
      'The seed scripts **are** bulk imports. The Payload one creates 88 posts with images; the Medusa one creates products, variants, prices and inventory. Both are worth reading before writing your own.',
      '## Use the Local API, not HTTP',
      '✅ The Payload seed uses the **Local API** — direct in-process calls, no HTTP. For a thousand documents that is dramatically faster than a thousand requests, and it skips serialisation and network entirely.',
      '⚠️ It also **bypasses access control by default**. Correct for trusted setup code, dangerous anywhere a user\'s input reaches it.',
      '## Sequential, not parallel',
      '✅ The seed creates guides one at a time, and the comment explains why: each iteration rasterises an image and writes three files, and running 88 at once competes for the same CPU without finishing sooner.',
      '> Parallelism helps when you are waiting. It does not help when you are computing.',
      'For I/O-bound work, batching in small groups is the middle ground — not one at a time, not all at once.',
      '## Go through the workflow, not the service',
      '⚠️ The review seed calls `createReviewWorkflow`, never the service directly. **The workflow is what writes the cross-module link row.** Inserting directly produces reviews attached to nothing — rows that exist and are unreachable from any product.',
      'The general rule: bulk-import through the same path a single item takes, or you will miss side effects.',
      '## Make it idempotent',
      '✅ The Payload seed deletes what it owns, then writes fresh, so re-running converges. The review seed bails if any review exists.',
      '⚠️ **Deleting first is not transactional.** A failure halfway leaves fewer rows than you started with. Back up before a bulk operation on real data.',
      '## Exports',
      '`npm run db:export` dumps both databases plus media with a manifest. For a data export in a shape someone else can use, query the API and write CSV — the dump is for restoring, not for sharing.',
    ],
  },
  {
    title: 'Search across two databases that cannot join',
    category: 'Data & APIs',
    status: 'published',
    excerpt:
      'A filter is not a search. Postgres can do real full-text search, and searching content and commerce together is an architectural problem.',
    tags: ['search', 'postgres', 'architecture'],
    body: [
      '✅ **What exists is filtering, not search.** `where[title][contains]=astro` is a SQL `LIKE`. It matches substrings, cannot rank, and will not find "deploying" when you type "deploy".',
      '## Postgres can do better, already',
      '📋 Full-text search is built in and unused here. `to_tsvector` and `to_tsquery` give you stemming, so "deploy" matches "deploying" and "deployed", plus relevance ranking and multi-word queries.',
      'The implementation is a generated column holding the `tsvector`, a GIN index over it, and queries that rank by `ts_rank`. It is an afternoon, and no new infrastructure.',
      '## When to reach for a search engine',
      '**Stay on Postgres when** you are searching thousands of documents and want decent results without another service.',
      '**Reach for Meilisearch or Typesense when** you need typo tolerance, faceting, instant as-you-type results, or synonyms. ⚠️ That is another service to run, back up and keep in sync.',
      '## The architectural problem',
      '⚠️ **You cannot search both databases at once.** A query that returns guides *and* products does not exist, because Postgres cannot join across databases and the services cannot see each other\'s tables.',
      'Three options:',
      '1. **Search them separately** and merge in the storefront. Simple, and ranking across the two sets is arbitrary — you are interleaving two unrelated relevance scores.',
      '2. **One index for both.** Push content from both services into a search engine. Proper cross-ranking, and now you own keeping it fresh.',
      '3. **Do not.** Search content and catalogue separately, with separate interfaces. Often the honest answer.',
      '> Option 2 is the only one that gives a real unified result, and it is the one that introduces an eventual-consistency problem you did not previously have.',
      'This is the two-database trade-off at its sharpest: independent deployment bought you a query you cannot write.',
    ],
  },
]
