import type { Guide } from './types'

/**
 * Deployment & Infrastructure — 12 guides.
 *
 * The sizing numbers quoted throughout were measured on this repo, not
 * estimated: three services in production mode totalled 834 MB resident, and
 * the Payload/Next build peaked at 2.34 GB. Those two figures decide almost
 * every hosting question, so they appear wherever they are load-bearing.
 */
export const deployment: Guide[] = [
  {
    title: 'What server do you actually need for this stack?',
    category: 'Deployment & Infrastructure',
    status: 'published',
    excerpt:
      'Measured, not estimated. Running all three services takes 834 MB; building one of them takes 2.34 GB. The second number is the one that decides what you buy.',
    tags: ['deployment', 'hosting', 'sizing', 'vps'],
    body: [
      'Almost every hosting question about this stack comes down to two numbers, and they are very far apart.',
      '## Running it',
      'All three services, built and running in production mode, measured on this repo:',
      '- Medusa — **414 MB**',
      '- Payload on Next — **320 MB**',
      '- Astro — **99 MB**',
      '- Postgres and Redis, idle — about **56 MB**',
      'That is **834 MB** for the application and under 900 MB with the databases. Add roughly 300 MB for the operating system and you are at 1.2 GB.',
      '## Building it',
      'Building is a different workload entirely, and this is where plans fail:',
      '- Astro — 724 MB',
      '- Medusa — 1.61 GB',
      '- **Payload on Next — 2.34 GB**',
      '> The runtime figure is what hosts advertise. The build figure is what decides.',
      '## So what do you buy',
      '**4 GB.** Not 2.',
      'At 2 GB the stack runs comfortably, at about 40% utilisation, and then dies the first time you deploy — the Payload build is killed before it finishes. At 4 GB you can build on the server, which removes an entire category of deployment complexity.',
      '2 vCPU and 40 GB of NVMe is plenty. That is roughly five to fifteen euros a month.',
      '## Why the build is so hungry',
      'Look at the build script in `apps/cms/package.json` and you will find `--max-old-space-size=8000`. Somebody set an 8 GB heap because the default was not enough. It does not use 8 GB, but it needs considerably more than a fifth of it.',
      '⚠️ **If you only have 2 GB**, build somewhere else — your laptop or CI — and upload `apps/cms/.next`, `apps/commerce/.medusa/server` and `apps/storefront/dist`. That works, it is just more moving parts.',
      'The full walkthrough is in docs/learn/13-deploying-it.md.',
    ],
  },
  {
    title: 'Why shared hosting fails even when it looks adequate',
    category: 'Deployment & Infrastructure',
    status: 'published',
    excerpt:
      'A real cPanel plan with 2 GB, 150 processes and Node available. It would have run this stack at 40% utilisation and then failed on the first deploy.',
    tags: ['deployment', 'hosting', 'cpanel', 'wordpress'],
    body: [
      'This one is from life rather than theory, and it is the most useful hosting lesson in this knowledge base.',
      '## The plan looked fine',
      'A cPanel shared plan, the kind you already host WordPress on. Checking it honestly:',
      '- Memory limit — **2 GB**',
      '- Process limit — **150**',
      '- Entry processes — 60',
      '- Node — available through the Setup Node.js App panel',
      '- Outbound ports — unrestricted, so an external database was reachable',
      'Against a stack that needs 834 MB and four processes, that is comfortable. Everything said yes.',
      '## And it would still have failed',
      'The Payload build peaks at **2.34 GB**. The plan caps at 2 GB. The first `npm run build` would have been killed, and on CloudLinux it is killed rather than slowed — no warning, just a dead process.',
      '> You would have installed everything, run it successfully, and discovered the problem on deploy day.',
      '## The other blocker',
      'Shared cPanel offers MySQL. Payload has adapters for Postgres, SQLite and MongoDB — **there is no MySQL adapter** — and Medusa requires Postgres outright. So the database had to be external regardless.',
      '## What this teaches',
      '- **Check the build requirement, not just the runtime one.** They differ by 3x here.',
      '- **`free -m` on shared hosting lies.** It reports the physical host, which might be 62 GB, not your slice. Your real limits are in the cPanel Resource Usage panel.',
      '- **`ulimit -u` lies too.** On CloudLinux the enforced limits live in LVE and neither `free` nor `ulimit` can see them.',
      '- **A missing directory proves nothing.** `~/nodevenv` only appears after you create your first Node app; its absence does not mean Node is unsupported.',
      '⚠️ **Shared hosting remains excellent for WordPress.** This is not a criticism of the plan — it is a mismatch between a plan built to serve PHP from a document root and a stack of three long-running Node daemons.',
    ],
  },
  {
    title: 'Choosing a VPS: specs, providers and regions',
    category: 'Deployment & Infrastructure',
    status: 'published',
    excerpt:
      'What to actually buy, now that you know the stack needs 4 GB to build and 1.2 GB to run.',
    tags: ['deployment', 'vps', 'hosting'],
    body: [
      'Once the sizing question is settled, picking a box is mostly about not overthinking it.',
      '## The spec',
      '- **4 GB RAM** — covers the 2.34 GB build with the services running',
      '- **2 vCPU** — builds are the only CPU-heavy moment',
      '- **40–80 GB NVMe** — the repo plus databases plus images is a few GB',
      '- **Ubuntu 24.04 LTS** — matches a WSL2 development environment, so everything you have run locally transfers',
      '## Providers worth considering',
      '- **Hetzner** — by some distance the best value in Europe. A 4 GB box is a few euros a month. Nuremberg, Falkenstein or Helsinki.',
      '- **DigitalOcean** — more expensive, but the documentation is the best in the business when you are learning.',
      '- **Vultr and Linode** — comparable to DigitalOcean, more regions.',
      '- **Contabo and Hostinger** — very cheap, generous memory, more variable performance.',
      '## Region matters more than people expect',
      'Pick the datacentre nearest your users, not nearest you. Every page in this stack is server-rendered, so latency between the browser and the server is paid on **every request** rather than once at build time.',
      '⚠️ **Latency between your services is paid too.** If the databases are managed and in a different region from the application server, every query crosses that gap — and a page making five backend calls pays it five times. Keep them together.',
      '## What you do not need',
      '- Managed Kubernetes. Three services on one box does not need an orchestrator.',
      '- A load balancer, until you have two servers.',
      '- Premium bandwidth tiers. This stack serves HTML and a handful of images.',
    ],
  },
  {
    title: 'The first hour on a new server',
    category: 'Deployment & Infrastructure',
    status: 'published',
    excerpt:
      'Hardening before anything is installed. Ten minutes of work, after which the box stops being interesting to people scanning for it.',
    tags: ['deployment', 'security', 'ssh', 'firewall'],
    body: [
      'Do this before Node, before Docker, before the repo. A fresh VPS with a public address is found within minutes.',
      '## Create a user that is not root',
      'Work as a normal user with sudo, and copy your SSH key across so you can still get in.',
      '## Turn off password authentication',
      'Set both `PasswordAuthentication no` and `PermitRootLogin no` in `/etc/ssh/sshd_config`, then restart ssh.',
      '⚠️ **Open a second SSH session and confirm it works before closing the first.** A typo in that file plus a closed session is a support ticket and a rebuilt server.',
      '## Firewall',
      'Allow SSH, 80 and 443. Nothing else. The three services bind to localhost and are reached through the reverse proxy, so they never need a port open.',
      '## Automatic security updates',
      'Install `unattended-upgrades`. It is the single highest-value thing on this list, because the vulnerabilities that actually get exploited are old ones in packages nobody patched.',
      '## What about fail2ban',
      '**Reach for it when** the box has been public for a while and you are seeing noise in the auth log.',
      '**Skip it when** you are already key-only and firewalled — it mostly protects password authentication you have already disabled.',
      '## The WordPress comparison',
      'On shared hosting the host does all of this and you never see it. That is a genuine benefit of shared hosting, and giving it up is a real cost of moving to a VPS. You are now the sysadmin.',
      'Commands are in docs/learn/13-deploying-it.md section 13.3.',
    ],
  },
  {
    title: 'Installing Node, Docker and Caddy',
    category: 'Deployment & Infrastructure',
    status: 'published',
    excerpt:
      'Three installs. The only opinionated choice is Caddy over nginx, and it is opinionated for one good reason.',
    tags: ['deployment', 'node', 'docker', 'caddy'],
    body: [
      'The runtime layer is short, because this stack does not need much.',
      '## Node 22',
      'The repo requires `>=22.12`. Ubuntu ships something older, so use the NodeSource repository. Check with `node -v` before continuing — an older Node fails in confusing ways rather than refusing to start.',
      '## Docker',
      'For Postgres and Redis. The key point: **`infra/docker-compose.yml` transfers unchanged**. The databases you developed against are the databases you deploy, same versions, same configuration.',
      'Remember to add your user to the `docker` group, and log out and back in for it to take effect.',
      '## Caddy, not nginx',
      'One reason, and it is enough: **Caddy obtains and renews TLS certificates automatically**. No certbot, no renewal cron job, no expiry outage at 3am eighteen months from now.',
      'For three subdomains, the entire configuration is nine lines — three blocks each naming a hostname and a local port.',
      '**Reach for nginx when** you need something Caddy does not do, or your team already runs it everywhere.',
      '**Reach for Caddy when** you want TLS to stop being a thing you think about. For this stack, that is most people.',
      '⚠️ **Point your DNS at the server before starting Caddy.** It cannot obtain a certificate for a name that does not yet resolve to it, and the failure message is less obvious than you would hope.',
    ],
  },
  {
    title: 'Running three services under systemd',
    category: 'Deployment & Infrastructure',
    status: 'published',
    excerpt:
      'One unit file each, and the one trap that will cost you half an hour: Medusa does not start from where you think it does.',
    tags: ['deployment', 'systemd', 'medusa', 'process'],
    body: [
      'Three Node processes need something to keep them alive across crashes and reboots. On Linux that is systemd.',
      '## One unit per service',
      'Each needs the same handful of things: a user to run as, a working directory, an `EnvironmentFile` pointing at that app\'s `.env`, the start command, and `Restart=always`.',
      '`After=network.target docker.service` matters — two of the three will not start before Postgres is accepting connections.',
      '## The trap',
      '⚠️ **Medusa starts from its build output, not from the app directory.**',
      'Run `medusa start` in `apps/commerce` and it fails with *"Could not find index.html in the admin build directory"*. The working directory has to be `apps/commerce/.medusa/server`, and **that directory needs its own copy of `.env`**.',
      'This is not documented prominently anywhere and it looks like a build failure rather than a path problem. I hit it while measuring this stack for deployment.',
      '## Why not just Passenger or PM2',
      'Shared hosting uses Passenger, which is **request-driven**: it spins apps down when idle and starts them on demand. That is fine for a PHP-shaped application and wrong here, because Medusa has scheduled jobs. The uptime check runs every minute and the review digest daily, and neither fires reliably if the process is not running.',
      'systemd simply keeps the process up. That is the whole difference.',
      '## Or Compose',
      '**Reach for Docker Compose instead when** you are already running the databases that way and want one mechanism rather than two. `restart: unless-stopped` does the same job as a systemd unit.',
      '**Reach for systemd when** the application runs on the host and only the databases are containerised, which is the shape docs/learn/13-deploying-it.md describes.',
    ],
  },
  {
    title: 'TLS and three subdomains with Caddy',
    category: 'Deployment & Infrastructure',
    status: 'published',
    excerpt:
      'Nine lines of configuration, automatic certificates, and a clear rule about what should be reachable from the internet.',
    tags: ['deployment', 'caddy', 'tls', 'dns'],
    body: [
      'Three services, three names, one proxy.',
      '## The shape',
      '- `example.com` to the Astro storefront on port 4321',
      '- `cms.example.com` to Payload on 3000',
      '- `api.example.com` to Medusa on 9000',
      'Each is a three-line block in the Caddyfile naming the hostname and reverse-proxying to a localhost port. Caddy requests certificates on first use and renews them without being told.',
      '## The rule that matters',
      '**Only Caddy listens on a public interface.** The three services bind to localhost, so nothing reaches Payload or Medusa except through the proxy. Your firewall allows 80, 443 and SSH, and that is all.',
      'That single decision removes a whole class of mistake — a service accidentally exposed on 9000 with no authentication in front of it.',
      '## DNS first',
      'Create A records for all three names pointing at the server before you start Caddy. Certificate issuance proves you control the name by answering a challenge **on that name**, so it cannot work before DNS resolves.',
      '## Should the admins be public at all',
      'Worth thinking about. `cms.example.com` and `api.example.com` are admin surfaces. Options, roughly in order of effort:',
      '- Basic auth in Caddy in front of them — a few minutes, and surprisingly effective',
      '- Restrict by source IP, if your address is stable',
      '- A VPN, and do not expose them at all',
      '⚠️ **The storefront has no authentication whatsoever.** Anyone who reaches it can delete any post or review, because it holds an admin-capable API key. Until that is fixed, the mutating routes need protecting at the proxy too.',
    ],
  },
  {
    title: 'Deploying a change, and the downtime it costs',
    category: 'Deployment & Infrastructure',
    status: 'published',
    excerpt:
      'Pull, install, build, restart. Honest about the gap where the service is down, because pretending otherwise helps nobody.',
    tags: ['deployment', 'release', 'downtime'],
    body: [
      'The deploy loop on a single box is five commands and about a minute.',
      '## The sequence',
      '1. `git pull` on the server',
      '2. `npm run install:all` if dependencies changed',
      '3. Build whichever apps changed',
      '4. `sudo systemctl restart` those services',
      '5. Check `/api/health` reports both backends reachable',
      '## Build only what changed',
      'All three builds take about 40 seconds together, but there is no reason to rebuild Medusa because a blog post changed. Astro takes a second and a half; Payload takes fifteen.',
      '## The honest part',
      '⚠️ **There is downtime.** Each service is stopped and started with nothing taking over, so requests during the restart fail. For a learning deployment that is acceptable. For anything with users it is not.',
      '> Saying "zero downtime" when a service restarts in place is how people end up surprised during their first real incident.',
      '## Making it better, in order of value',
      '- **Build before restarting.** A failed build should not take the running service down with it.',
      '- **Health-gate the restart.** Do not restart the next service until the previous one answers.',
      '- **Two instances behind the proxy**, restarted one at a time. Redis already makes this possible — the event bus and locking are shared, so two Medusa instances do not double-run scheduled jobs.',
      '## Rolling back',
      'Rollback here is `git checkout` the previous commit and rebuild — which means rollback takes as long as a deploy and depends on the build still working. A versioned artefact you can flip back to is better, and is the next thing to build.',
    ],
  },
  {
    title: 'Environment variables and secrets in production',
    category: 'Deployment & Infrastructure',
    status: 'published',
    excerpt:
      'Three .env files, four secrets that must be regenerated, and the two API keys that live in the database rather than in configuration.',
    tags: ['deployment', 'secrets', 'env', 'security'],
    body: [
      'The repo ships development placeholders everywhere. Shipping them is the single most common way a learning project becomes an incident.',
      '## What must change',
      '- `PAYLOAD_SECRET` — signs Payload sessions',
      '- `JWT_SECRET` — signs Medusa admin tokens',
      '- `COOKIE_SECRET` — signs Medusa cookies',
      '- The Postgres password, in `infra/docker-compose.yml` **and** both `DATABASE_URL` values',
      'Generate each with `openssl rand -base64 32`. One per secret — reusing one across two of them means a leak in either compromises both.',
      '## CORS',
      '`STORE_CORS`, `ADMIN_CORS` and `AUTH_CORS` are `localhost` in the examples. Point them at your real domains. Leaving them permissive is a quiet way to allow any site to call your API with a visitor\'s credentials.',
      '## The two keys that are not configuration',
      '⚠️ `PAYLOAD_API_KEY` and `MEDUSA_PUBLISHABLE_KEY` **live in the databases**. They are not secrets you choose — they are generated during setup and written into the storefront\'s `.env` for you.',
      'The consequence: **a database reset invalidates both**. If the storefront suddenly cannot reach either backend after you restored a backup, this is why. Regenerate with `npm run postman:env` and restart.',
      '## Where secrets should actually live',
      'A `.env` file on the server is a reasonable starting point and better than committing them. It is not the end state — the file is readable by anything running as that user, and it does not rotate.',
      '📋 The next step is a secrets manager, which this repo does not use. Worth knowing the direction even while a file is what you have.',
      '⚠️ **All three `.env` files are gitignored, and should stay that way.** Check before every commit; a leaked secret in git history outlives the commit that removed it.',
    ],
  },
  {
    title: 'Backups you have actually restored',
    category: 'Deployment & Infrastructure',
    status: 'published',
    excerpt:
      'The repo already has export and import scripts with checksums and drift detection. The part people skip is proving the restore works.',
    tags: ['deployment', 'backup', 'postgres', 'recovery'],
    body: [
      'This stack ships a working backup pair: `npm run db:export` and `npm run db:import`. ✅ Both are real and you can run them now.',
      '## What export captures',
      '- Both databases, in Postgres custom format so a restore can be selective',
      '- The media directory, tarred — because Payload stores upload metadata in the database and the **files on disk**, and a database-only restore leaves every image 404ing',
      '- A manifest with checksums, migration state and per-table row counts',
      '## What the manifest buys',
      'The manifest is what turns a dump into a backup. On import it enables four checks:',
      '- **Integrity** — a checksum mismatch means a truncated file, caught before anything is overwritten',
      '- **Migration drift** — refusing a dump taken against a different schema, which is the failure that produces data in a shape the code no longer expects',
      '- **Connection clearing** — Postgres will not drop objects another session holds open',
      '- **Verification** — row counts compared per table afterwards, not as a total, because two tables off by plus and minus three net to zero',
      '## On a server',
      'Schedule it with cron and **get it off the box**. A backup on the same disk protects you against a bad migration, not against losing the disk. Sync to object storage after each run.',
      '> A backup nobody has restored is a hypothesis.',
      '## Do the restore now',
      '⚠️ **Before you need it.** Export, note the row counts, reset the database, import, confirm the counts match and the app renders. It takes ten minutes on a day when nothing is wrong, and the alternative is learning your backup is broken on the day it matters.',
      'The export in this repo has been restored into a deliberately emptied database and matched its manifest exactly. That is the bar.',
    ],
  },
  {
    title: 'Zero-downtime deploys, and why this repo cannot do them yet',
    category: 'Deployment & Infrastructure',
    status: 'published',
    excerpt:
      'What would have to change. Honest about the gap rather than describing a setup that does not exist here.',
    tags: ['deployment', 'scaling', 'release'],
    body: [
      '📋 **Not configured in this repo.** The deploy loop restarts services in place, and requests during the restart fail. This is the map of what closing that gap needs.',
      '## Why it is not just "run two copies"',
      'Three of the four requirements are already met, which is the encouraging part:',
      '- **Shared session state** — ✅ Medusa sessions are in Redis, so a request can hit either instance',
      '- **Shared event bus and locking** — ✅ Redis again, so two instances do not double-run scheduled jobs',
      '- **Shared workflow state** — ✅ persisted, so an interrupted workflow is not lost with the process',
      '- **Shared file storage** — 🚫 **this is the blocker.** Uploads go to local disk, so two instances have two different media directories, and an image uploaded to one 404s on the other',
      '## So the order of work is',
      '1. Move uploads to object storage. Until that is done, nothing else matters.',
      '2. Run two instances of each service on different ports.',
      '3. Teach the proxy to health-check and drain before removing an instance.',
      '4. Restart one at a time, waiting for health between.',
      '## The thing people get wrong',
      '⚠️ **A health check that only proves the process is listening will happily route traffic to a broken instance.** The storefront\'s `/api/health` checks both backends and returns 503 if either is unreachable — that is the right shape, because it fails when the service is useless rather than only when it is dead.',
      '## Is it worth it here',
      'For a learning deployment, no. A minute of downtime during a deploy you chose to run is not an outage. Build it when you have users who did not choose it.',
    ],
  },
  {
    title: 'Docker Compose in production, or systemd?',
    category: 'Deployment & Infrastructure',
    status: 'published',
    excerpt:
      'Two reasonable answers for one box. The deciding question is whether your application runs on the host or in a container.',
    tags: ['deployment', 'docker', 'systemd'],
    body: [
      'Once the databases are in Compose, there is an obvious question: why not the applications too?',
      '## The two shapes',
      '**Host plus containers.** Postgres and Redis in Compose, the three Node services on the host under systemd. This is what docs/learn/13-deploying-it.md describes.',
      '- Builds are simple — the code is right there',
      '- Logs go to journald with everything else',
      '- Node version is whatever you installed',
      '**Everything in Compose.** All five in containers, one file, `docker compose up -d`.',
      '- One mechanism instead of two',
      '- The Node version is pinned in the image, so the server cannot drift from your laptop',
      '- Rebuilds are image builds, which is slower but reproducible',
      '- Needs more memory — each container carries its own overhead',
      '## How to choose',
      '**Reach for host plus containers when** this is one project on one box you also use for other things, and you want to `git pull` and rebuild in place.',
      '**Reach for all-in-Compose when** you want the deployment to be reproducible, or you expect to move it to another host, or several projects share the server and you want them isolated.',
      '⚠️ **Do not mix carelessly.** Running Postgres in Compose and Payload on the host means Payload connects to `localhost:5433` while a containerised Payload would need the service name instead. That difference is responsible for a lot of confused debugging.',
      '## What this repo does',
      '`infra/docker-compose.yml` defines only Postgres and Redis, and `npm run dev` runs the three applications directly. The deployment chapter keeps that split because it is the smaller step from how you already work locally.',
    ],
  },
]
