import type { Guide } from './types'

/** Frontend — 5 guides. */
export const frontend: Guide[] = [
  {
    title: 'How routing works in Astro',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'A file in src/pages is a URL, and nothing else is. No template hierarchy, no rewrite rules, no flushing.',
    tags: ['astro', 'routing', 'themes'],
    body: [
      'WordPress resolves a URL by running the main query and then walking the template hierarchy — `single-{post_type}-{slug}.php`, then `single-{post_type}.php`, then `single.php`, then `index.php`. It is a cascade you memorise, backed by rewrite rules you sometimes have to flush.',
      'Astro has none of that. **A file in `src/pages/` is a URL. Nothing else is.**',
      '## The mapping',
      '- `src/pages/index.astro` → `/`',
      '- `src/pages/posts/index.astro` → `/posts`',
      '- `src/pages/posts/[slug].astro` → `/posts/anything`',
      '- `src/pages/posts/[id]/edit.astro` → `/posts/123/edit`',
      '- `src/pages/api/health.ts` → `/api/health`',
      'Square brackets mark a parameter. Read it in the frontmatter with `Astro.params`.',
      '## What you gain and lose',
      'You gain that the routing table is a directory listing. There is no cascade to reason about and no cache to flush — add a file and the route exists.',
      'You lose the automatic fallbacks. Nothing serves `/posts/missing` unless your `[slug].astro` handles the not-found case itself.',
      '## The gotcha from tutorials',
      "Most Astro tutorials are written for static output and tell you to export `getStaticPaths()`. This project runs `output: 'server'`, so routes are resolved per request and **`getStaticPaths` is not needed**. Copying it in from a tutorial causes confusing errors.",
      '## API routes live in the same tree',
      "A `.ts` file under `src/pages/api/` exporting `GET` or `POST` is an HTTP endpoint. Same routing rules — the file path is the URL. That is where this project's review endpoints live.",
      '## Middleware runs first',
      '`src/middleware.ts` sees every request before any page does. This project uses it for rate limiting and request logging. The nearest WordPress equivalent is an mu-plugin hooking `template_redirect`.',
      '## Going deeper',
      'The frontend guide has the full routing table for this project and the archive and single-page recipes.',
    ],
  },
  {
    title: 'How to build a posts archive page in Astro',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'The archive.php equivalent: one file, a fetch in the frontmatter, and a loop. No WP_Query, because there is no database.',
    tags: ['astro', 'archive', 'themes'],
    body: [
      'An archive page lists posts. In a WordPress theme that is `archive.php` or `home.php`, and the posts arrive automatically in the main query — you just run the loop.',
      'Here you fetch them yourself, over HTTP.',
      '## The steps',
      '1. Create `src/pages/posts/index.astro`.',
      '2. In the frontmatter, call the Payload client to list posts.',
      '3. Below the fence, loop the array and render each one.',
      'The real file in this project is exactly that, plus a delete form per row.',
      '## The frontmatter is where the query goes',
      'Everything between the `---` fences runs **on the server, once per request**, and never ships to the browser. It is the part of a PHP template above the HTML — except it is TypeScript and it cannot touch a database.',
      'Instead of `WP_Query`, you call a function that makes an HTTP request to Payload. In this project that is `listPosts()` in `src/lib/payload.ts`.',
      '## Pagination',
      'Payload returns an envelope, not a bare array: `docs` plus `totalDocs`, `totalPages`, `page`, `hasNextPage` and `hasPrevPage`. That is more than `WP_Query` gives you without extra work, and it is all you need to render a pager.',
      '## Showing drafts',
      "By default an anonymous request sees only published posts, because of the read access rule. This project's archive passes `includeDrafts: true` and authenticates with the API key, which is why drafts appear there with a status badge.",
      '> That is a deliberate choice for a teaching app. A public blog archive would not do this.',
      '## Depth matters here',
      'If you want to show a category name or a cover image on each card, you need `depth: 1` so the relationship comes back expanded rather than as an ID.',
      '## Going deeper',
      'The frontend guide builds this page step by step and shows the real response envelope.',
    ],
  },
  {
    title: 'How to build a single post page in Astro',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'One file serves every post. The twist is rich text: Lexical is a JSON tree, and the_content() has no equivalent.',
    tags: ['astro', 'lexical', 'richtext'],
    body: [
      'The `single.php` equivalent is `src/pages/posts/[slug].astro`. One file serves every post; the `[slug]` is a parameter.',
      '## The steps',
      '1. Create `src/pages/posts/[slug].astro`.',
      '2. Read the parameter: `const { slug } = Astro.params`.',
      '3. Fetch the matching post with `depth: 1`.',
      '4. If nothing came back, return a 404 response.',
      '5. Render the title, metadata and body.',
      '## The part with no WordPress equivalent',
      "`the_content()` echoes HTML, because WordPress stores HTML. Payload's rich text is **Lexical**, which stores a JSON tree of nodes — paragraphs, headings, lists, links, each with its own properties.",
      'There is no function that turns it into HTML for you. You walk the tree.',
      'This project has a converter at `src/lib/lexical.ts` that handles paragraphs, headings, lists, quotes, links and horizontal rules, plus the text-format bitmask for bold, italic, underline, strikethrough and inline code.',
      '## Why a bitmask',
      'Formatting is not nested tags. It is a number on the text node: bold is 1, italic is 2, strikethrough 4, underline 8, code 16. Bold-italic is `format: 3`, not two wrapper elements.',
      '> That is why a naive converter drops formatting — it looks for tags that are not there.',
      '## Escaping is your job',
      'Because you are producing HTML yourself, you must escape text nodes. The converter here escapes every text node and every link href, and that is covered by unit tests. Rendering it with `set:html` is safe only because of that escaping.',
      '## Handling not-found',
      'Nothing serves a missing slug for you. Check whether the fetch returned a document and return a real 404 if not — otherwise the page renders empty with a 200, which is worse.',
      '## Going deeper',
      'The frontend guide covers the page and the rich-text conversion, with the bitmask worked through.',
    ],
  },
  {
    title: 'How to create a reusable widget for your site',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'Widget means two different things. One is a reusable component an editor can fill; the other is an admin dashboard panel.',
    tags: ['astro', 'components', 'widgets'],
    body: [
      'In WordPress, a widget is a block of content you drop into a sidebar. In Medusa, a widget is a panel injected into the admin UI. The word covers both, so this guide covers both.',
      '## Sense one — a reusable front-end block',
      'The equivalent is an Astro component: a `.astro` file in `src/components/` that takes props and renders markup. It is `get_template_part()` with a signature and type checking.',
      'This project has seven, including `RatingStars`, `StatTile` and `ReviewCard`. They ship **zero JavaScript** — they render on the server and send HTML.',
      '## Making one editable',
      'A component alone is not a widget in the WordPress sense, because an editor cannot change it. For that, pair it with a Payload **global**.',
      'The announcement banner in this project is exactly that pattern. The content lives in the site settings global; the layout reads it on every page and renders it if enabled. An editor toggles a checkbox and types a message, and every page changes.',
      '> That is a sidebar widget, rebuilt from parts: a global for the content, a component for the markup.',
      '## Sense two — an admin dashboard widget',
      'Medusa supports injecting React components into defined zones of its admin. This project has one at `apps/commerce/src/admin/widgets/product-reviews.tsx`, registered with `defineWidgetConfig` and a zone of `product.details.after`.',
      'It fetches reviews for the product you are viewing and offers approve, reject and delete buttons — a moderation panel inside the product page.',
      '## Worth knowing',
      "Payload has **no custom admin UI** in this project. Both systems support admin extensions; only Medusa's is used here. If you need a custom Payload admin component, that is a supported feature, just not demonstrated.",
      '## When to make it an island',
      'Add a `client:` directive only when the browser must do something the server cannot pre-compute. This storefront has exactly one island, a review filter, and every other component is zero-JavaScript.',
      '## Going deeper',
      'The frontend guide covers both senses and the full component list with props.',
    ],
  },
  {
    title: 'How to use TypeScript across Payload, Medusa and Astro',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'It is all three, not just Payload. Each app types things differently, and one of them deliberately hand-writes its types.',
    tags: ['typescript', 'types', 'tooling'],
    body: [
      'A common assumption is that TypeScript is a Payload thing here. It is not — all three apps are TypeScript, and each uses it differently.',
      '## Payload — generated from the config',
      'Payload reads your collection configs and writes `apps/cms/src/payload-types.ts`, containing an interface per collection. Regenerate it after any field change with `npm --prefix apps/cms run generate:types`.',
      'This is genuinely useful: the types cannot drift from the schema, because both come from the same declaration.',
      '## Medusa — framework types plus generated entry points',
      'Models, services, routes and workflows are all `.ts`. Types come from `@medusajs/framework/types`, and a build step writes generated query entry points into `.medusa/types/`.',
      '> That directory is a build artefact. On a cold clone it does not exist, and `tsc` fails until you have booted the dev server once.',
      '## Astro — frontmatter is TypeScript',
      'The code between the `---` fences in a `.astro` file is TypeScript, checked by `astro check` rather than plain `tsc`. Action schemas use `astro/zod`, which gives you validation and inferred types from one declaration.',
      '## The honest part',
      'Payload generates perfectly good types, and **this project does not import them in the storefront**. The storefront hand-writes its own in `src/lib/types.ts`, and the file explains why.',
      "The reasoning: the storefront talks to Payload over HTTP, across a service boundary. Importing the CMS's internal types would couple the frontend to the CMS's internals and to its release cycle. A hand-written type is an explicit statement of the contract the frontend depends on — and it covers only the fields actually used.",
      '> Whether you agree or not, know that it is a decision rather than an oversight. On a single-team project, importing the generated types is reasonable.',
      '## Checking everything',
      '`npm run typecheck` runs all three: `tsc --noEmit` for the two backends and `astro check` for the storefront.',
      '## Going deeper',
      "The stack guide covers each app's setup and the regeneration commands.",
    ],
  },
  {
    title: 'SEO when no plugin does it for you',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'Yoast writes about fifteen tags into your head element. Here nothing injects anything, which is both the problem and the point.',
    tags: ['seo', 'astro', 'yoast'],
    body: [
      '📋 **This repo has almost no SEO.** A title and a description, and that is it. Here is what is missing and roughly what it costs.',
      '## Why nothing appears automatically',
      'In WordPress, `wp_head()` is an open hook and every plugin writes into it. That is why Yoast works without touching your theme — and also why a WordPress head element contains things nobody chose.',
      '> Nothing can inject into your head here, which means **nothing does**. You write every tag yourself.',
      '## The order worth doing it in',
      '1. **Per-page title and description** — add the fields to the collection, render them in the layout. Biggest effect for least work.',
      '2. **Canonical URLs** — one tag, prevents duplicate-content problems from query strings.',
      '3. **Open Graph and Twitter cards** — what controls the preview when a link is shared. ✅ The cover images already exist and are the obvious `og:image`.',
      '4. **`sitemap.xml`** — `@astrojs/sitemap` exists, or generate it from a Payload query since you know every slug.',
      '5. **`robots.txt`** — a static file.',
      '6. **JSON-LD structured data** — `Article` for posts, `Product` for products, `BreadcrumbList` for navigation.',
      '## Where the values live',
      'In Payload, as fields. `@payloadcms/plugin-seo` adds them with previews, or add three text fields yourself. ⚠️ **The `plugins: []` array in the config is currently empty**, so there is a clean place to start.',
      '## The one thing already right',
      '✅ Pages are server-rendered, so a crawler receives complete HTML. A client-rendered SPA has to work much harder for the same result. That is the hardest SEO problem to retrofit, and this stack does not have it.',
      '## Redirects',
      '⚠️ Change a slug and the old URL 404s. WordPress plugins track this automatically. `@payloadcms/plugin-redirects` exists; without it, plan slug changes rather than discovering them in search console.',
    ],
  },
  {
    title: 'Images: what the repo does, and what it should',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'Payload generates two sizes on upload, the storefront ignores them, and nothing serves modern formats. A short list of genuine wins.',
    tags: ['images', 'performance', 'astro'],
    body: [
      "Images are usually most of a page's weight, and this is the least optimised part of the stack.",
      '## What happens today ✅',
      'Upload an image and Payload uses sharp to generate a `thumbnail` at 400×300 and a `card` at 768×512, alongside the original. The seed produces 88 covers, so 264 files.',
      'The posts list requests the thumbnail; the single post page requests the card. ✅ That much is right — the list is not downloading full-size images.',
      '## What is wrong',
      '⚠️ **PNG only.** The covers are generated as PNG because that is what the generator emits. WebP is typically 25–35% smaller and AVIF better still, and sharp can produce both — it simply is not asked to.',
      '⚠️ **No `srcset`.** Each `img` names one URL, so a phone downloads the same file as a desktop. The two generated sizes exist and the markup does not offer the browser a choice between them.',
      '⚠️ **`astro:assets` is used nowhere.** Astro has an image component that handles formats, sizing and lazy loading — this app uses a plain `img` tag throughout.',
      '## The wins, in order',
      '1. **Emit WebP** in the placeholder generator. One line, 30% smaller.',
      '2. **Add `srcset`** with the sizes you already generate. The markup change is small.',
      '3. **Add more sizes.** Two is thin; four or five makes `srcset` genuinely useful.',
      '4. **Put a CDN in front**, with on-the-fly transformation. Then the stored original is all you need and the edge does the rest.',
      '## What is already right',
      '✅ `loading="lazy"` on list thumbnails, `eager` on the single-post hero — correct both times. And explicit `width` and `height`, which reserves space and prevents layout shift.',
      '⚠️ **Local disk is the real constraint.** Uploads do not survive a container rebuild and cannot be shared between two instances. Object storage comes before any of this matters.',
    ],
  },
  {
    title: 'Forms that work with JavaScript disabled',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'Astro Actions post to the page URL and the server handles them, so the form works before any JavaScript loads. Three parsing traps come with that.',
    tags: ['astro', 'forms', 'actions'],
    body: [
      '✅ **The post forms in this repo work with JavaScript disabled.** Turn it off and create a post; it still works.',
      '## Why that is possible',
      "An Astro Action with `accept: 'form'` is posted to by an ordinary HTML form. The browser does what browsers did before JavaScript — serialise the fields and POST them — and the server handles it, then re-renders the page with the result.",
      'The nearest WordPress equivalent is `admin-post.php`: a form posting to a handler. The differences are that the Action is **typed and zod-validated** with per-field errors, and there is no global router every plugin registers into.',
      '## The three traps',
      '⚠️ **Absent fields arrive as `null`, not `undefined`.** zod\'s `.optional()` accepts only `undefined`, so an unchecked checkbox fails validation with "expected string, received null". Use `.nullish()`.',
      '⚠️ **An empty text input sends `""`, not nothing.** A partial update then overwrites a stored value with an empty string. Normalise empty strings to undefined before they reach the update.',
      '⚠️ **HTML forms cannot issue DELETE.** Only GET and POST. The delete action is a POST form, which is why it looks inconsistent next to the REST endpoint that uses a real DELETE.',
      '## Showing errors',
      'Actions return field-level errors, so the form can render a message under the offending input and keep what the user typed. ✅ That is what the post forms do, and it is the part that would otherwise need client-side JavaScript.',
      '## When to use something else',
      '**Reach for an Action when** your own form submits it and you want progressive enhancement.',
      '**Reach for an endpoint when** something other than your form calls it — another service, a mobile app, curl. Reviews use endpoints for exactly this reason.',
      '> Working without JavaScript is not nostalgia. It is what happens on a slow connection before the bundle arrives, and for anyone whose script failed to load.',
    ],
  },
  {
    title: 'Accessibility, the part nothing in this repo covers',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'One mention across twenty-one thousand lines of documentation. An honest audit of what this app gets right by accident and wrong on purpose.',
    tags: ['accessibility', 'a11y', 'frontend'],
    body: [
      '🚫 **Accessibility is the biggest documentation gap in this repo.** Not a controversial opinion — it is mentioned once, in passing, across the whole course.',
      '## What it gets right by accident',
      '✅ **Server-rendered HTML.** Content arrives complete, so a screen reader is not waiting on JavaScript. That is the hardest accessibility problem in modern frontends and this stack avoids it structurally.',
      '✅ **Almost no JavaScript.** One island on one page. Fewer custom widgets means fewer chances to build something unusable by keyboard.',
      '✅ **Real form elements** with real labels, and errors rendered as text next to the field.',
      '## What is not checked at all',
      '- **Colour contrast.** The palette was chosen to look good in both themes, not measured against WCAG.',
      '- **Focus visibility.** Nothing defines a focus style, so you get the browser default — which custom CSS often weakens.',
      '- **The island.** The review filter updates a list client-side with no `aria-live` region, so a screen reader is not told the results changed.',
      '- **Alt text.** The field is required in the media collection ✅, which is good. But the generated covers all get the same formulaic text, and the list thumbnails use `alt=""` — correct for decoration, wrong if the image carries meaning.',
      '- **Heading order.** Nothing verifies headings descend without skipping.',
      '## Where to start',
      '1. **Keyboard-only.** Tab through a page. If you cannot see where you are, or cannot reach something, that is the first bug.',
      '2. **An automated check.** Lighthouse or axe catches contrast, missing labels and landmark problems in a minute.',
      '3. **`aria-live` on the island**, so filtering announces its result.',
      '> Automated tools find perhaps a third of real problems. They are still worth running, because that third is cheap to fix.',
      '⚠️ **This is a legal requirement in many places**, not only a nicety. If you build client work on this stack, it is yours to handle.',
    ],
  },
  {
    title: 'When a component should become an island',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'This storefront ships exactly one, and measuring it is more useful than any rule of thumb. 188 kB against zero.',
    tags: ['astro', 'islands', 'performance'],
    body: [
      '✅ **One island, one directive, in the whole application.** The review filter, hydrated with `client:visible`. Everything else renders on the server and ships no JavaScript.',
      '## The question to ask',
      '> Can the server pre-compute this?',
      'If yes, it is a component. If it genuinely needs to respond to the user without a round trip, it is an island.',
      '## Why the filter qualifies',
      'It filters an already-loaded list by text, status and rating. Every keystroke would otherwise be a server round trip for data the browser already has. That is the case for shipping JavaScript.',
      '## Why the rest do not',
      'Rating stars, stat tiles, review cards, the distribution bar — all pure functions of data the server already has. Making any of them an island would ship a React runtime to redraw markup that never changes after load.',
      '## What it costs, measured',
      '⚠️ **188 kB on the reviews page; 0 on the posts page.** That is the React runtime plus the component, and it is the honest price of one island. It is not a reason never to use one — it is a reason to know when you are.',
      '## The directives',
      '- `client:load` — hydrate immediately. For something interactive above the fold.',
      '- `client:idle` — when the browser is free. Good default for non-urgent interactivity.',
      '- `client:visible` — when scrolled into view. ✅ What this repo uses, and usually right for anything below the fold.',
      '- `client:media` — on a media query. Useful for mobile-only widgets.',
      '- `client:only` — skip server rendering entirely. ⚠️ No HTML until JavaScript runs, so avoid unless the component genuinely cannot render server-side.',
      '## How to check',
      'Request a page and count `astro-island` elements in the HTML. Zero means zero JavaScript. ⚠️ Count with `grep -o ... | wc -l` rather than `grep -c` — minified HTML puts everything on one line, and `grep -c` counts lines, not matches.',
    ],
  },
  {
    title: 'Navigation, view transitions and what this app does not do',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'Every click is a full page load. Astro has a feature to change that in one line, and there are reasons to think before adding it.',
    tags: ['astro', 'navigation', 'view-transitions'],
    body: [
      '📋 **Not configured here.** Every link is an ordinary navigation: the browser discards the page and loads the next one.',
      '## Why that is mostly fine',
      'Pages are server-rendered and small. A full load of a server-rendered page on a decent connection is fast, and it is what the web did for twenty years — including every WordPress site you have built.',
      '✅ It also means no client-side router, no stale state and no memory leaks across navigations.',
      '## What view transitions would add',
      'Astro can intercept navigation, fetch the next page, and swap the content with an animated transition — keeping some state across the change. Adding it is roughly one component in the layout.',
      'You get a smoother feel, persistent elements like a media player, and no flash of unstyled content.',
      '## The trade',
      '⚠️ **It makes navigation JavaScript-dependent.** The thing this app currently does without any. Astro falls back to normal navigation when scripts fail, so it degrades well — but you have added a moving part to something that had none.',
      '⚠️ **Islands re-hydrate** across transitions, and state you expected to persist may not. The rules are learnable and they are rules you now have to know.',
      '## When it is worth it',
      '**Reach for it when** the app feels like an app — a dashboard, a multi-step flow, anything where a full reload is jarring.',
      '**Skip it when** the site is content — a blog, a catalogue, documentation. Which is what this one is.',
      '## The thing that actually matters more',
      '> Prefetching beats transitions for perceived speed.',
      'Astro can prefetch a link on hover, so by the time the click lands the page is in cache. Cheaper than transitions, no behaviour change, and it makes ordinary navigation feel instant.',
    ],
  },
  {
    title: 'Layouts, slots and the shared page shell',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'One layout wraps every page in this app. It is the closest thing here to header.php and footer.php, and it is a component rather than two halves of a file.',
    tags: ['astro', 'layouts', 'components'],
    body: [
      '✅ Every page here wraps itself in `src/layouts/Layout.astro`. There is one layout, and it holds the document, the navigation and the global styles.',
      '## The WordPress comparison that actually holds',
      'A theme splits the shell across `header.php` and `footer.php`, and each template calls both. The opening and closing tags live in different files, which is why a stray `</div>` is so hard to find.',
      'An Astro layout is **one component that wraps its children**. The shell is never split in half.',
      '## Slots',
      "`<slot />` is where the page's content goes. ✅ `Layout.astro` has exactly one, so pages pass a single body.",
      '📋 **Named slots** are the next step: `<slot name="sidebar" />` in the layout, `<div slot="sidebar">` in the page. Useful when a page contributes to two separate regions — a sidebar and a main column — without prop-drilling markup.',
      '## Props, not globals',
      'This layout takes `title`, `subtitle` and `section`. The page passes them; the layout renders the `<title>` and highlights the right nav item.',
      '> The difference from `wp_title()` is that these are **typed props on a component**. Pass a prop the layout does not declare and TypeScript says so before the page renders.',
      '## Nesting them',
      '📋 Layouts compose: a `DocsLayout` can wrap `Layout` and add a table of contents, and pages using it get both. That is how you avoid a single layout accumulating conditionals for every section of the site.',
      '## Styles in a layout are global by default-ish',
      '⚠️ Astro scopes component styles by adding a data attribute. A `<style>` in the layout only reaches elements the **layout** renders — not the page inside the slot. Styling slotted content needs `:global()` or `is:global`.',
      'That catches everyone once: a rule that works in the layout does nothing to the page, and nothing warns you.',
    ],
  },
  {
    title: 'Astro Actions versus API endpoints',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'Two ways to handle a POST, and this repo uses both. They are not interchangeable, and the deciding question is who is calling.',
    tags: ['astro', 'actions', 'api', 'forms'],
    body: [
      '✅ Both exist here: Actions in `src/actions/index.ts`, endpoints under `src/pages/api/`. Knowing which to reach for is a two-second decision once you have the rule.',
      '## Actions are for your own forms',
      'An Action is a typed function with a zod input schema. Astro generates a client binding, validates the input, runs it on the server, and makes the result available on the next render.',
      "✅ With `accept: 'form'` it takes a **real HTML form post**, so the delete button on `/posts` works with JavaScript disabled.",
      '> That is the whole appeal: the progressive-enhancement story of a plain form, with the types and validation of an RPC call.',
      'Errors come back structured. `isInputError(result.error)` distinguishes "you sent nonsense" from "the backend fell over", which is the distinction users actually need.',
      '## Endpoints are for other callers',
      'A `.ts` file under `src/pages/api/` exporting `GET` or `POST` is an ordinary HTTP route returning a `Response`. ✅ `api/health.ts`, `api/monitor.ts`, `api/reviews/[id]/moderate.ts`.',
      '**Use one when** the caller is not a form on your own site: another service, a webhook, a fetch from an island, a monitoring probe.',
      '## The rule',
      '- A form on a page you control → **Action**',
      '- Anything else → **endpoint**',
      '## Two traps',
      '⚠️ **Form values are strings.** A number field arrives as `"3"`, an unchecked checkbox is **absent entirely** rather than `false`. Use `z.coerce.number()` and give booleans a default, or validation fails on input that looks correct.',
      '⚠️ **`security.checkOrigin` runs upstream of everything.** A non-GET request without a matching `Origin` header is rejected with 403 before your handler or your middleware sees it. ✅ Provable: `curl -X DELETE` fails, and the identical request with `-H "Origin: http://localhost:4321"` succeeds.',
      'This also means those rejections never reach the request log, so a traffic graph can disagree with reality.',
    ],
  },
  {
    title: 'Middleware, and what runs on every single request',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'One file sees every request before any page does. It is where cross-cutting concerns belong, and where two of them already live.',
    tags: ['astro', 'middleware', 'rate-limiting'],
    body: [
      '✅ `src/middleware.ts` runs on every request. It does two things today: rate limiting and request logging.',
      '## The shape',
      'An `onRequest(context, next)` function. Call `next()` to continue, or return a `Response` to stop — which is how the rate limiter returns a 429 without any page rendering.',
      '## What it does here',
      '**Rate limiting.** A sliding window, **120 requests per 60 seconds**, in memory. ✅ One of only two pieces of logic with unit tests, because off-by-one errors in a window are invisible until they are not.',
      '**Request logging.** Method, path, status and duration into an in-memory ring buffer, which is where `/monitor` gets p50 and p95.',
      '## `locals` is the useful part',
      '📋 `context.locals` is a per-request object that every page can read. Resolve something once in middleware — the current user, a tenant, a feature flag — and every page gets it without each one re-fetching.',
      'That is where authentication would go. ✅ Middleware already sees every request, so it is the natural place to check a session and populate `locals.user`.',
      '## Three things to know',
      '⚠️ **It is not the outermost layer.** `security.checkOrigin` rejects cross-origin non-GET requests **before** middleware runs, so those 403s never appear in the log. A tool can only measure what reaches it.',
      '⚠️ **In-memory means per-process.** Restart and the history is gone; run two instances and each sees only its own traffic, and the rate limit is effectively doubled. Redis is the fix, and it is already running for Medusa.',
      '⚠️ **It runs on static assets too** unless you filter. Logging every CSS and image request drowns the signal you wanted.',
      '## Keep it cheap',
      '> Every millisecond here is added to every response. Middleware is the wrong place for anything that calls a database or another service on each request.',
    ],
  },
  {
    title: 'Static, server and the rendering choice per page',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'This app renders everything per request, which is the right default here and the wrong one for most content sites. The switch is one line.',
    tags: ['astro', 'rendering', 'ssr', 'performance'],
    body: [
      "✅ `astro.config.mjs` sets `output: 'server'` with the Node standalone adapter, and every page carries `export const prerender = false`.",
      '## The three modes, and the one that no longer exists',
      '**Static** — HTML built once at build time. Fastest possible, cacheable everywhere, and stale until the next build.',
      '**Server** — rendered per request. Always current, costs a round trip to your backends every time.',
      "⚠️ **`output: 'hybrid'` was removed in Astro 5.** Plenty of tutorials still tell you to set it. The behaviour it provided is now what `static` plus an adapter gives you, with `prerender` deciding per page.",
      '## Why this app is fully server-rendered',
      'Because it is a **CRUD demonstration**. Create a post and the list must show it immediately. A static build would show content from whenever the build last ran, which would make every page a lie about what the database holds.',
      '> That reasoning does not transfer. A marketing site or a blog has no such requirement, and rendering it per request buys nothing while costing a backend call per visitor.',
      '## It is per page, not per project',
      '`export const prerender = true` on a page builds that one at build time; everything else stays dynamic. A static home page, about page and blog archive alongside a live dashboard is normal and correct.',
      '⚠️ **A prerendered page cannot read the request.** No query string, no headers, no cookies. The posts archive here reads `?page` and `?category`, so it cannot be prerendered without losing filtering.',
      '## The honest cost here',
      "📋 **Nothing is cached at any layer.** Every page view re-fetches from Payload or Medusa. The products page is worse: it makes one request per product, so fifteen products is sixteen round trips, and Medusa's 240-per-minute limit arrives at roughly fifteen page loads.",
      '✅ The cheapest fix is not switching to static — it is `Cache-Control` headers on responses that are identical for everybody.',
      '⚠️ Never cache a response that varies by caller. This app serves drafts to an authenticated request and hides them otherwise; cache that shared and unpublished content leaks to everyone.',
    ],
  },
  {
    title: 'Scoped styles, globals and theming without a framework',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'Every style in this app is hand-written and component-scoped. No Tailwind, no CSS-in-JS, and the scoping has one rule that surprises people.',
    tags: ['astro', 'css', 'styling', 'theming'],
    body: [
      '✅ No CSS framework here. Plain CSS in `<style>` blocks, scoped per component, plus custom properties for the palette.',
      '## How scoping works',
      'A `<style>` in a `.astro` file applies **only to that component**. Astro adds a `data-astro-cid-…` attribute to the elements it renders and rewrites your selectors to match.',
      'So a `.card` rule in one component cannot leak into a `.card` in another. No BEM, no naming convention, no discipline required.',
      '## The rule that catches everyone',
      '⚠️ **Scoping follows rendering, not nesting.** A style in a layout applies to elements the *layout* renders — not to the page passed into its `<slot />`.',
      'A rule that works perfectly in the layout does nothing to the page content, and nothing warns you. `:global()` or `is:global` reaches through deliberately.',
      '> I have spent real time on this. If a selector looks right and has no effect, ask which component actually rendered that element.',
      '## Custom properties for theming',
      'Colours as CSS variables on `:root` means one definition, used everywhere, overridable by a media query or a data attribute. ✅ The cover-image generator reads the **same palette** the UI uses, so generated images and the site agree.',
      '📋 A dark mode is a second block of variable definitions under `prefers-color-scheme`. No component changes, because every component references the variable rather than the value.',
      '## Why no Tailwind',
      'Not because it is bad. Because this repo is read more than it is extended, and `class="row between"` says what it means where `class="flex items-center justify-between"` says how it is achieved.',
      '> For a team shipping features daily, a utility framework is a reasonable trade. For a codebase whose job is to be legible, the indirection costs more than it saves.',
      '## What this app ships',
      '✅ A handful of kilobytes of CSS and **almost no JavaScript** — one React island on one page. That is not an optimisation anyone performed; it is what you get when components render on the server by default.',
    ],
  },
  {
    title: 'Error pages, 404s and what this app does when things break',
    category: 'Frontend',
    status: 'published',
    excerpt:
      'There is no 404 page and no error page. Here is what a visitor actually sees today, and the three things worth adding.',
    tags: ['astro', 'errors', '404', 'resilience'],
    body: [
      "🚫 **There is no `src/pages/404.astro` and no `500.astro`.** A missing post gets the adapter's default response: correct status code, no design, no navigation back.",
      '## What Astro gives you',
      '`src/pages/404.astro` is rendered for any unmatched route. `src/pages/500.astro` is rendered when a page throws.',
      '⚠️ Both are **static by default**. A 404 page that needs to fetch navigation must opt into server rendering, and a 500 page should fetch nothing at all — if your backend is the reason for the 500, the error page must not depend on it.',
      '## Returning a real 404 from a page that exists',
      'A dynamic route like `/posts/[slug]` matches *any* slug. When the lookup finds nothing you must say so explicitly, by returning a `Response` with status 404 rather than rendering an empty page.',
      '> ⚠️ Rendering "not found" with a **200** is the version of this bug that reaches production, because it looks right in a browser and is wrong to everything else — search engines index it, monitoring counts it as healthy, and link checkers pass it.',
      '## Partial failure is the more common case',
      'This app talks to two backends. One being down should not blank the page.',
      '✅ `src/lib/settle.ts` exists for exactly this. The home page health-checks both and **renders either way**, showing which one is unreachable rather than failing entirely.',
      '> That is the pattern worth taking: decide per section what happens when its data does not arrive. A dashboard with one broken tile is far better than a dashboard that is a stack trace.',
      '## Three things worth adding',
      '1. **A 404 page** with the site shell and a way back. Cheapest, most visible',
      '2. **A 500 page with no data dependencies**, so it works when everything else does not',
      '3. **Explicit 404 responses** from the dynamic routes, so the status code tells the truth',
      '📋 Nothing here reports errors anywhere. A server error is a line in a log file nobody is watching — see the operations guides for what to do about that.',
    ],
  },
]
