import type { Guide } from './types'

/** Getting Started — 5 guides. */
export const gettingStarted: Guide[] = [
  {
    title: 'What is the wp-config.php equivalent in this stack?',
    category: 'Getting Started',
    status: 'published',
    excerpt:
      'There is no single config file. Configuration is split three ways, and two of the three are code rather than settings.',
    tags: ['config', 'env', 'wordpress'],
    body: [
      'In WordPress, `wp-config.php` is the one file that holds database credentials, salts, debug flags and anything else you bolt on. There is exactly one, it sits at the web root, and everything reads from it.',
      'This stack has no such file, and looking for one is the first thing that goes wrong. Configuration is split across three apps, and it is split by *kind* as well as by app.',
      '## The three kinds of configuration',
      'Each app separates secrets from structure, which WordPress never did.',
      '- **Secrets and environment** live in a `.env` file — one per app. This is the part that genuinely maps to `wp-config.php`.',
      '- **Structure** lives in a TypeScript config file that is read at boot: `payload.config.ts`, `medusa-config.ts`, `astro.config.mjs`. There is no WordPress equivalent, because WordPress discovers plugins and post types at runtime.',
      '- **Per-app tooling** lives in `package.json` and `tsconfig.json`.',
      '## Where each one lives',
      '- `apps/cms/.env` plus `apps/cms/src/payload.config.ts`',
      '- `apps/commerce/.env` plus `apps/commerce/medusa-config.ts`',
      '- `apps/storefront/.env` plus `apps/storefront/astro.config.mjs`',
      'There is **no root `.env`**. Each app is a separate npm project with its own dependencies and its own deploy, so each carries its own environment.',
      '## The part that surprises people',
      'In WordPress, registering a post type is a function call that runs on every request. Here, the equivalent is a declaration in `payload.config.ts` that is read **once at boot** and diffed against the database. That is why adding a collection requires a restart, and why nothing can register one at runtime.',
      '> The trade: you lose runtime flexibility, and you gain a schema that is in version control and cannot drift.',
      'Each `.env` has a committed `.env.example` beside it listing the keys with dummy values. `.env` itself is gitignored.',
      '## Going deeper',
      'The file structure guide covers every directory, and the operations chapter covers which two keys are regenerated when you reset the database.',
    ],
  },
  {
    title: 'The file structure of a Payload, Medusa and Astro project',
    category: 'Getting Started',
    status: 'published',
    excerpt:
      'Three npm projects in one repository, two databases, and three .env files. Here is what lives where and why.',
    tags: ['structure', 'monorepo', 'env'],
    body: [
      'A WordPress install is one tree: `wp-content/themes` for presentation, `wp-content/plugins` for behaviour, `wp-admin` and `wp-includes` for core. One codebase, one deploy.',
      'This repository holds three independent applications that happen to live beside each other.',
      '## The top level',
      '- `apps/cms` — Payload 3, running inside Next.js, on port 3000',
      '- `apps/commerce` — Medusa 2, on port 9000',
      '- `apps/storefront` — Astro 7, on port 4321',
      '- `infra` — the Docker Compose file for Postgres and Redis',
      '- `scripts` — setup, backup and restore shell scripts',
      '- `docs` — three documentation tracks',
      'The root `package.json` holds **no dependencies**. It exists only to orchestrate: `npm run dev` starts all three, `npm run typecheck` checks all three.',
      '## Why three node_modules',
      'Because they have genuinely different dependency trees and genuinely different deploy targets. Payload needs Next. Medusa needs its own framework. Astro needs neither. A single workspace would force their versions to agree, and they do not.',
      '## There are three .env files, and no root one',
      'This is the question everyone asks, and the answer is three.',
      '- `apps/cms/.env` — `DATABASE_URL`, `PAYLOAD_SECRET`',
      '- `apps/commerce/.env` — `DATABASE_URL`, `JWT_SECRET`, `COOKIE_SECRET`, `REDIS_URL`, CORS settings',
      '- `apps/storefront/.env` — `PAYLOAD_URL`, `MEDUSA_URL`, and the two API keys',
      'Note that the two `DATABASE_URL` values point at **different databases** on the same Postgres server: `payload_crud` and `medusa_crud`. Neither app can see the other\'s tables, and no query can join across them.',
      '## The two generated keys',
      '`PAYLOAD_API_KEY` and `MEDUSA_PUBLISHABLE_KEY` in the storefront\'s `.env` are generated during setup and stored **in the databases**. Reset the database and both become invalid — which is why `npm run setup` rewrites that file for you.',
      '## Going deeper',
      'The how-to track walks each app\'s tree directory by directory, including which parts Next owns inside the CMS app.',
    ],
  },
  {
    title: 'The terminal commands worth memorising',
    category: 'Getting Started',
    status: 'published',
    excerpt:
      'A working set of about a dozen commands, grouped by what you are actually doing, with the wp-cli equivalent where one exists.',
    tags: ['cli', 'npm', 'workflow'],
    body: [
      'WordPress development needs very few commands — mostly `wp-cli` and whatever your host gives you. Here the terminal is the primary interface, and there is no admin screen that restarts a service for you.',
      '## Every day',
      '- `npm run dev` — all three services, colour-coded in one terminal',
      '- `npm run dev:cms` — just one of them, when you want a quiet log',
      '- `npm run logs` — tail all three log files',
      '- `npm run logs:errors` — grep warnings and errors out of them',
      '## Database',
      '- `npm run db:up` — start Postgres and Redis in Docker and wait for health',
      '- `npm run db:psql` — a psql shell inside the container, no client install needed',
      '- `npm run db:export` — dump both databases plus a manifest',
      '- `npm run db:import` — restore, with checksum and migration-drift checks',
      '- `npm run db:reset` — **destroys the Docker volume.** Take a backup first.',
      '## After changing things',
      '- `npm run typecheck` — all three apps',
      '- `npm --prefix apps/cms run generate:types` — after editing a Payload field',
      '- `npm --prefix apps/commerce run db:generate` — after editing a Medusa model',
      '- `npm --prefix apps/commerce run db:migrate` — apply it',
      '## Testing',
      '- `npm test` — unit tests plus the compensation test',
      '- `npm run postman:test` — the full API collection through newman',
      '## The one that catches everyone',
      'Astro 7 **backgrounds its own dev server**. Pressing Ctrl-C on `npm run dev` does not stop it. From `apps/storefront`, run `npx astro dev stop`, and `npx astro dev status` to ask which port it actually took.',
      '> If the storefront is not on 4321, something else has the port and Astro silently moved to 4322.',
      '## Going deeper',
      'The how-to track has the full table grouped by task, with wp-cli equivalents side by side.',
    ],
  },
  {
    title: 'What is seeding, and when should you use it?',
    category: 'Getting Started',
    status: 'published',
    excerpt:
      'Seeding is sample content as code: versioned, repeatable, and run from the terminal rather than clicked through an importer.',
    tags: ['seeding', 'database', 'workflow'],
    body: [
      'Seeding means running a script that inserts a known set of starting data into an empty database, so that every developer — and every reset — lands in the same state.',
      '## The WordPress equivalent, and the difference',
      'The closest things you already know are a WXR import or WooCommerce\'s sample-products importer. Both put demo content in a fresh install.',
      'The difference is that those are **one-off actions you click**, while a seed is **code in your repository**. It is versioned alongside the schema it populates, it runs from the terminal, and it is reviewed like any other code.',
      '## What this project seeds',
      '- `apps/cms/src/scripts/seed.ts` — the admin user, an API key, categories, these guides, a block-built page and the site settings global',
      '- `apps/commerce/src/scripts/seed.ts` — region, currencies, sales channel, warehouse, shipping options, product categories, products and inventory',
      '- `apps/commerce/src/scripts/seed-reviews.ts` — reviews, created through the workflow rather than written directly',
      'That last point matters. The review seed calls `createReviewWorkflow`, not the service, because the workflow is what writes the cross-module link row. Inserting directly would produce reviews attached to nothing.',
      '## When to use it',
      '- Setting up a development machine',
      '- Continuous integration, where every run needs identical data',
      '- Demos, where you want the app to look populated',
      '- Immediately after `npm run db:reset`',
      '## When not to use it',
      '- **Production content.** Seeds are sample data, not a content management strategy.',
      '- **Anything with real customer data.**',
      '- **As a migration mechanism.** Changing a table\'s shape is `db:migrate`. Seeds fill tables; migrations change them.',
      '## Idempotency is a design decision',
      'A seed can skip what already exists, or it can delete and rewrite. This project\'s Payload seed does both: it clears the content it owns, then writes it fresh, so you can re-run it without ending up with duplicates.',
      '> Medusa\'s seed is different — it is unguarded, so running it twice throws a unique-constraint violation on a product handle. That is why the documented path is a reset.',
      '## Going deeper',
      'The stack guide covers how to re-seed without duplicating everything, and what the two generated API keys have to do with it.',
    ],
  },
  {
    title: 'How to run this stack locally from a cold clone',
    category: 'Getting Started',
    status: 'published',
    excerpt:
      'Four commands, in order, and the two things that go wrong if you run them out of order.',
    tags: ['setup', 'docker', 'cli'],
    body: [
      'Unlike a WordPress install, there is no five-minute web installer. There is a sequence of terminal commands, and the order matters.',
      '## The sequence',
      '1. `npm run install:all` — installs dependencies in all three apps',
      '2. `npm run db:up` — starts Postgres and Redis and waits until both report healthy',
      '3. `npm run setup` — creates schemas, seeds content, generates both API keys and writes them into the storefront `.env`',
      '4. `npm run dev` — starts all three services',
      'Then open the storefront on port 4321. If the two service cards at the top of the dashboard say **reachable**, you are done.',
      '## What setup actually does',
      'It is idempotent, so running it again is safe. It pushes the Payload schema, runs Medusa migrations, seeds both databases, creates the Medusa admin user, and — the part that matters — captures the two generated keys and writes them into `apps/storefront/.env`.',
      'Doing those steps by hand is possible but easy to get wrong, because the keys are generated mid-sequence and the storefront cannot talk to either backend without them.',
      '## The two things that go wrong',
      '**Running the seed before the database is up.** The Payload seed reads `DATABASE_URL` at module-evaluation time, before the script body runs. If Postgres is not listening you get a connection error rather than a helpful message.',
      '**A stale Astro dev server.** Astro backgrounds itself, so a previous run may still hold port 4321 even after you closed the terminal. Check with `npx astro dev status` from `apps/storefront`.',
      '## Credentials',
      'Both admin panels use the same development login: `admin@local.test` with the password `supersecret`. The CMS admin is on port 3000, the commerce admin on 9000.',
      '## Going deeper',
      'The infrastructure chapter covers the Docker Compose file line by line, and the recovery ladder for when something is wedged.',
    ],
  },
  {
    title: 'The mental model: three programs, two databases, one browser',
    category: 'Getting Started',
    status: 'published',
    excerpt:
      'Before any of the detail makes sense, you need the shape. Three programs that do not share memory, do not share tables, and talk only over HTTP.',
    tags: ['architecture', 'mental-model', 'getting-started'],
    body: [
      'If one idea makes everything else fall into place, it is this one.',
      '## Three programs, not one',
      '- **Payload** owns editorial content and the `payload_crud` database',
      '- **Medusa** owns commerce and reviews and the `medusa_crud` database',
      '- **Astro** owns **nothing** and is a client of both',
      'They are separate operating-system processes. They do not share memory, variables or tables. The only thing between them is HTTP.',
      '## The rule that follows',
      '> Astro has no database. Every read and every write is an HTTP request to the service that owns that data.',
      'This is the single biggest adjustment from WordPress, where a template can call `WP_Query` and reach MySQL directly. Here there is no connection string in the frontend and never will be.',
      '## Why anyone would do this',
      '- Each service owns its own schema and migrates independently',
      '- You can replace the frontend without touching the backends',
      '- The same content serves a website, a mobile app and a kiosk, because all three are just HTTP clients',
      'And the costs, which are real: three deployments, three sets of logs, no transaction spanning both databases, and no JOIN between content and commerce.',
      '## Where Astro earns its place',
      'It is a **backend for frontend**. It holds the credentials, so the browser never sees them. It hides inconsistency — Payload updates with PATCH, Medusa with POST, and your pages call one function and never learn which. And it fails gracefully, rendering the panels it can when one backend is down.',
      '## What to read next',
      'The foundations chapter defines every term this paragraph used. The worked-example chapter traces one request from browser to database and back.',
    ],
  },
  {
    title: 'Your first week with this stack, in order',
    category: 'Getting Started',
    status: 'published',
    excerpt:
      'A suggested path through 13 chapters, 8 recipes and 88 guides, for someone who wants to be productive rather than complete.',
    tags: ['getting-started', 'learning', 'onboarding'],
    body: [
      'There is a lot of material here. This is the order that works.',
      '## Day one — get it running and break it',
      'Run the setup, start the stack, open all three admin panels. Then **break something on purpose**: stop Medusa and reload the dashboard. Watch the Payload panels keep working while the commerce ones explain themselves.',
      '> You learn a system\'s shape from its failure modes, and this repo is disposable. Everything resets.',
      '## Day two — Payload',
      'The easiest of the three and the fastest win. Add a field to the posts collection, watch the column appear, see it in the admin and the API without writing a controller.',
      '## Day three — Astro',
      'Routing, the frontmatter, and the fact that it runs on the server. Build an archive page. Notice that the data arrives by fetch, not by query.',
      '## Days four and five — Medusa',
      'The hardest, and the most valuable. Budget real time. The payoff is watching a workflow roll back: force a failure, count the rows, find nothing left behind.',
      '⚠️ **If Medusa feels like too much ceremony, you have not yet felt the problem it solves.** Push through to the compensation lab before judging it.',
      '## Day six — the seams',
      'How reviews attach to products across a module boundary. Why there is no JOIN. What the backend-for-frontend layer actually does.',
      '## Day seven — operations',
      'Backups, monitoring, and what deployment requires. Less exciting, and the part that separates someone who can build this from someone who can run it.',
      '## The habits that matter more than the order',
      '- **Read the request, not the file.** Follow one HTTP request end to end.',
      '- **Keep four terminals open** — logs, curl, psql, and your editor.',
      '- **Prefer curl to the browser** when learning. It shows you the actual response.',
    ],
  },
  {
    title: 'The words you need before the rest makes sense',
    category: 'Getting Started',
    status: 'published',
    excerpt:
      'Twelve terms that everything else assumes. Mostly ordinary ideas wearing unfamiliar names, plus two that genuinely have no WordPress equivalent.',
    tags: ['getting-started', 'glossary', 'vocabulary'],
    body: [
      'Most confusion starting out is vocabulary rather than concept.',
      '## The ones that are just new names',
      '- **Headless** — the backend exposes data over HTTP and owns no HTML',
      '- **SSR** — HTML built on the server per request, which is what WordPress always did',
      '- **CSR** — HTML built in the browser by JavaScript',
      '- **ORM** — a library that turns objects into SQL for you',
      '- **Migration** — a versioned, reviewable schema change',
      '- **Soft delete** — the row stays with a `deleted_at` timestamp and is filtered out of reads',
      '- **Slug** — `post_name`, exactly as you know it',
      '## The ones worth real attention',
      '**BFF, backend for frontend.** A server that exists specifically to serve one frontend. Astro is this. It holds credentials, hides the differences between two backends, and fails gracefully when one is down.',
      '**Module isolation.** A Medusa module knows nothing about any other module — no imports, no foreign keys, no JOINs. Every piece of Medusa ceremony exists because of this one rule.',
      '**Compensation.** A workflow step declares how to undo itself. When a later step fails, the completed ones are reversed. WooCommerce has no equivalent, and it is the best idea in Medusa.',
      '**Link table.** Because modules cannot JOIN, a third table records that a review belongs to a product. You declare it once and the query layer resolves it.',
      '**depth.** How far Payload expands relationships on a read. No WordPress equivalent, and the cheapest performance lever in the stack.',
      '**Publishable key.** Identifies which storefront is asking. ⚠️ **Not a secret** — unlike the Payload API key, which very much is.',
      '## Where to look things up',
      'The glossary chapter defines around sixty terms, each with a link to the chapter that uses it properly.',
    ],
  },
]
