import type { Guide } from './types'

/**
 * Installation & Setup — 8 guides.
 *
 * First in the learning path, because everything else assumes a running stack.
 * These are deliberately the most literal guides in the collection: exact
 * commands, exact error strings, exact ports. The orientation material in
 * Getting Started comes next and explains *why* the shape is what it is.
 */
export const installationAndSetup: Guide[] = [
  {
    title: 'Start here: how to work through this knowledge base',
    category: 'Installation & Setup',
    status: 'published',
    excerpt:
      'A hundred-odd guides in a deliberate order, grouped into twelve categories that run from installing the thing to deploying it. Read this one first.',
    tags: ['start-here', 'learning-path', 'orientation'],
    body: [
      'This archive is sorted by **reading order**, not by date. The first guide is the one to read first, and the last assumes everything before it.',
      'That ordering is a real field on every post rather than a side effect of publication dates, so a guide can be revised without moving in the path.',
      '## The twelve categories, in order',
      '1. **Installation & Setup** — get it running on your machine',
      '2. **Getting Started** — the mental model, the vocabulary, the daily commands',
      '3. **Key Files & Folders** — the map: what every important file does',
      '4. **Content Modelling** — Payload collections, fields, blocks, relationships',
      '5. **Frontend** — Astro routing, layouts, islands, forms',
      '6. **Data & APIs** — moving data between three services over HTTP',
      '7. **Commerce** — Medusa products, pricing, carts, orders',
      '8. **Operations & Tooling** — logs, databases, editors, debugging',
      '9. **Testing & Quality** — what to test and what is worth mocking',
      '10. **Performance** — depth, indexes, pooling, caching',
      '11. **Security** — auth, secrets, CORS, injection',
      '12. **Deployment & Infrastructure** — sizing, hardening, TLS, shipping',
      '## The three labels, and why they matter',
      'Every claim in every guide is marked, because a tutorial that cannot tell you which commands actually work is worse than no tutorial:',
      '- ✅ **running here** — this works against this repo today, as written',
      '- 📋 **supported but unconfigured** — the framework does this, this repo does not yet',
      '- 🚫 **not in this repo** — named as a gap rather than implied to exist',
      '> If a guide says ✅ and the command fails, that is a bug in the guide. The labels are a promise.',
      '## You do not have to read it in order',
      'The sequence is for someone starting from zero. If you arrived with a specific problem, use the category filter — the archive is organised by **the part of the stack you are stuck in**, which is how people actually search.',
      '## The honest expectation',
      'Categories 1 through 3 are an afternoon. Four through seven are where the real learning is and will take weeks of building, not reading. Eight through twelve are reference you will return to rather than read once.',
    ],
  },
  {
    title: 'What to install before you clone anything',
    category: 'Installation & Setup',
    status: 'published',
    excerpt:
      'Five tools, and only three of them are strictly required. The versions matter more than you would expect, and one of them will bite you.',
    tags: ['prerequisites', 'node', 'docker', 'setup'],
    body: [
      'On WordPress the prerequisite list is "PHP, MySQL, and a web server", and your host has already installed all three. Here you are the host.',
      '## The three you must have',
      '**Node 22 or newer.** Not optional and not negotiable. Payload 3 runs inside Next 16, and Next 16 requires a modern Node. Check with `node --version`.',
      '⚠️ **Node 20 will install fine and fail later**, during the build rather than the install, with an error that does not mention your Node version. This is the most common wasted hour on a new machine.',
      '**npm 10 or newer.** Ships with Node 22, so if Node is right this is right. Check with `npm --version`.',
      '**Docker, with Compose.** Postgres and Redis run as containers; nothing else does. Check with `docker --version` and `docker compose version` — note that is `compose` as a subcommand, not the old `docker-compose` binary.',
      '## The two that make life easier',
      '**git**, to clone the repo and to have any history at all.',
      '**jq**, used by the setup and export scripts to read JSON. The scripts are more pleasant with it and some output is less readable without it.',
      '## What you do not need',
      "📋 You do **not** need to install PostgreSQL or Redis on your machine. They run in Docker, which is the point — your laptop stays clean and the versions match everyone else's.",
      'You do not need pnpm or yarn. The repo uses npm, and three separate lockfiles.',
      '> A stray `pnpm-lock.yaml` beside an `npm` project is a trap: whichever tool you run second will quietly resolve different versions than the one that was tested.',
      '## Disk and memory',
      'Three `node_modules` trees come to several gigabytes. More importantly, **building Payload peaks at 2.34 GB of RAM** — measured, not estimated. A machine with 4 GB total will swap badly or fail outright. See the deployment guides for what this means for a server.',
      '## Check all of it at once',
      'Run `node --version`, `npm --version`, `docker --version` and `git --version` in sequence. If all four answer, you are ready to clone.',
    ],
  },
  {
    title: 'What `npm run setup` actually does, step by step',
    category: 'Installation & Setup',
    status: 'published',
    excerpt:
      'One command does nine things in a required order, and two of them generate credentials that nothing else can produce. Worth understanding before it fails.',
    tags: ['setup', 'migrations', 'api-keys', 'seeding'],
    body: [
      '✅ `npm run setup` runs `scripts/setup.sh`. It is **idempotent** — running it twice is safe — and it is the only sanctioned way to get from an empty database to a working stack.',
      'Here is what it does, in order, because when it fails you need to know how far it got.',
      '## 1 — Confirm the databases exist',
      'It execs into the `apm-postgres` container and lists databases, expecting `payload_crud` and `medusa_crud`. Those are created by `infra/init/01-databases.sql`, which Postgres runs **only on first boot of an empty volume**.',
      '⚠️ If that file changed after you first started the container, it has not re-run. `npm run db:reset` destroys the volume and re-initialises.',
      '## 2 — Install dependencies in all three apps',
      'Skipped per app if `node_modules` is already there.',
      '## 3 — Seed Payload, and capture a key',
      'Runs the CMS seed, then **greps its own output** for `PAYLOAD_API_KEY=`. This is the part you cannot do by hand easily: the key is generated during seeding and stored in the database.',
      '## 4 — Run Medusa migrations',
      "Medusa uses real migration files, unlike Payload's schema push in development. Different philosophy, same goal.",
      '## 5, 6, 7 — Seed commerce, create the admin user, seed reviews',
      'Products, plans and prices; then the admin login; then the review data, including the pending and rejected rows that make moderation demonstrable.',
      '## 8 — Bootstrap, and capture the second key',
      'Runs the commerce bootstrap and greps for `MEDUSA_PUBLISHABLE_KEY=`. Same trick as step 3.',
      '## 9 — Write the storefront `.env`',
      '> This is the step that makes the command worth having. Both keys are **generated**, not chosen, and they live in the two databases. The storefront cannot reach either backend without them.',
      'This is also why **resetting the database invalidates both keys**, and why the storefront suddenly 400s and 403s after a restore until you re-run setup.',
      '## What it does not do',
      '🚫 It does not start the services. That is `npm run dev`, separately and afterwards.',
    ],
  },
  {
    title: 'Starting and stopping the stack every day',
    category: 'Installation & Setup',
    status: 'published',
    excerpt:
      'Two commands to start, one to stop, and the one that looks like "stop" but destroys all your data instead.',
    tags: ['daily', 'docker', 'cli', 'workflow'],
    body: [
      'Once setup has run once, the daily loop is short.',
      '## Starting',
      '1. `npm run db:up` — starts Postgres and Redis, and **waits until both report healthy** thanks to `--wait`. Without that flag the next command races the database and loses.',
      '2. `npm run dev` — starts all three applications under `concurrently`, colour-coded: magenta for the CMS, cyan for commerce, yellow for the storefront.',
      'Then open the storefront on port 4321. ✅ The home page health-checks both backends, so if the two service cards say reachable, everything is wired.',
      '## Stopping',
      '`Ctrl-C` in the `npm run dev` terminal stops all three applications. The containers keep running, which is fine — they are idle and cheap.',
      '`npm run db:down` stops the containers too, and **keeps your data** in the named volume.',
      '## The dangerous one',
      '⚠️ **`npm run db:reset` is not "restart".** It runs `docker compose down -v`, and the `-v` destroys the volume. Every post, product, order, API key and user is gone.',
      '> Reach for it deliberately, when you want a clean slate. Then expect to run `npm run setup` again, because both API keys died with the database.',
      '`npm run reset:all` chains reset, setup and Postman environment regeneration into one command for exactly that reason.',
      '## When something is wedged',
      'The order that resolves almost everything: `Ctrl-C`, then `npm run db:down`, then `npm run db:up`, then `npm run dev`. Reach for `db:reset` only when you actually want the data gone.',
      '## Watching it work',
      '`npm run logs` tails all three log files together. `npm run logs:errors` greps the same files for errors and warnings and shows the last forty — faster when you already know something broke.',
    ],
  },
  {
    title: 'When setup fails: the errors you will actually hit',
    category: 'Installation & Setup',
    status: 'published',
    excerpt:
      'Six real failures, what each one looks like, and the fix. Most of them are ordering problems wearing a database error as a disguise.',
    tags: ['troubleshooting', 'setup', 'errors'],
    body: [
      'Every failure here has happened in this repo. The messages are rarely about the real cause.',
      '## "ECONNREFUSED 127.0.0.1:5433"',
      'Postgres is not up, or not up **yet**. Run `npm run db:up` and let it finish — the `--wait` flag exists so it returns only when healthy.',
      "⚠️ The Payload seed reads `DATABASE_URL` at **module-evaluation time**, before the script body runs. So a connection failure surfaces before any of the script's own friendly logging, which makes it look like the script is broken rather than the database missing.",
      '## "database payload_crud does not exist"',
      'The init SQL only runs on a **brand-new volume**. If you created the container before that file existed, it never ran. `npm run db:reset` fixes it by destroying the volume.',
      '## Port 4321 is already in use',
      'Astro backgrounds itself, so a previous run can outlive the terminal you started it in. Worse, another project may own it — this has genuinely happened here.',
      '⚠️ **Do not reach for `pkill -f astro`.** The pattern matches your own shell and kills the terminal you are typing in. Find the owner by port instead, confirm what it is, then kill that process group.',
      '## The storefront returns 400 or 403 from both backends',
      'The two API keys are stale. They live in the databases, so a reset or a restore invalidates them. Re-run `npm run setup`, which rewrites `apps/storefront/.env`.',
      '## "Could not find index.html in the admin build directory"',
      'Only in production. Medusa must be started from `apps/commerce/.medusa/server`, with its own `.env` — not from the app root.',
      '## The Postman suite fails on everything',
      'Two causes, both environmental rather than real:',
      '- **Three runs inside a minute** exhausts the 120-per-60-second limiter. Wait sixty seconds.',
      '- **A locked account.** Payload locks a user after repeated failed logins, and then every subsequent run fails at login with a message that does not say "locked". Clear `login_attempts` and `lock_until` on the users row.',
      '> Both of these cost me an hour before I recognised them. Neither is a bug in your code.',
    ],
  },
  {
    title: 'Which ports this stack uses, and fixing a collision',
    category: 'Installation & Setup',
    status: 'published',
    excerpt:
      'Five ports, one of which is deliberately not the default. Here is who owns what and how to find out when something else got there first.',
    tags: ['ports', 'networking', 'troubleshooting'],
    body: [
      'Five processes, five ports. Knowing them turns most "it will not start" problems into a ten-second diagnosis.',
      '## The map',
      '- **4321** — Astro storefront. The one you actually open.',
      '- **3000** — Payload CMS, inside Next. Admin panel at `/admin`, REST API at `/api`.',
      '- **9000** — Medusa. Store API, admin API and its own admin panel.',
      '- **5433** — PostgreSQL, in Docker.',
      '- **6379** — Redis, in Docker.',
      '## Why 5433 and not 5432',
      "✅ Deliberate. **5432 is the Postgres default**, so anything else on your machine — a system install, another project's container — already owns it. Publishing on 5433 means this stack coexists with whatever else you run.",
      'The container still listens on 5432 internally; the mapping is `5433:5432`. So inside the container the port is standard, and only the host side is shifted.',
      '> This is the single cheapest decision in the repo. Pick a non-default host port for every project and port collisions mostly stop happening.',
      '## Finding out who owns a port',
      'Use `ss -ltnp` and look for the port. For containers, `docker ps` shows the published mapping — and note that `ss` cannot show you the PID of a container you do not own, so a port can look free when it is not.',
      '⚠️ I have made exactly that mistake: a scan reported Postgres and Redis down while both were healthy and serving queries. Confirm with an actual connection, not just a port scan.',
      '## Changing one',
      "All three application ports come from their app's own configuration and `.env`. Change the port and you must also change it **everywhere it is referenced**: the storefront's `PAYLOAD_URL` and `MEDUSA_URL`, Medusa's CORS settings, and the Postman environment.",
      '🚫 There is no single place that defines all five. That is the cost of three independent applications.',
    ],
  },
  {
    title: 'The two Docker containers, and why only two',
    category: 'Installation & Setup',
    status: 'published',
    excerpt:
      'Postgres and Redis run in containers. The three applications run on your machine directly, and that split is a deliberate teaching decision.',
    tags: ['docker', 'postgres', 'redis', 'architecture'],
    body: [
      'A common instinct is to containerise everything. This repo containerises exactly the stateful infrastructure, and nothing else.',
      '## What runs where',
      '✅ **In Docker:** `apm-postgres` (Postgres 17 Alpine) and `apm-redis` (Redis 7 Alpine).',
      '✅ **On your machine:** the CMS, commerce and storefront, as ordinary Node processes.',
      '## Why not containerise the apps too',
      'Because in development the feedback loop is everything. Running the apps natively gives you instant hot reload, a debugger that attaches without configuration, and stack traces pointing at files you can open.',
      '> Containerising a dev server mostly buys you a slower file watcher and a harder debugging story.',
      'Postgres and Redis are the opposite case: you never edit them, you want the exact same version everyone else has, and you want to throw them away cleanly.',
      '## Why these images',
      '**Alpine variants**, because they are a fraction of the size and nothing here needs the extras. **Postgres 17** and **Redis 7** are pinned by major version so the whole team gets the same engine.',
      '## The volume is the part that matters',
      'Data lives in the named volume `apm-pgdata`, not in the container. That is why `db:down` keeps your data and `db:reset` — which passes `-v` — does not.',
      '⚠️ **Redis has no volume here**, so its data does not survive. That is correct for this stack: Medusa uses it as a cache and a job queue, not a store of record.',
      '## Health checks earn their keep',
      'Both services declare a `healthcheck`, and `npm run db:up` passes `--wait`. So the command returns when the databases are genuinely **ready to accept connections**, not merely when the container has started.',
      'That distinction is the difference between a reliable setup script and one that fails intermittently on a cold machine.',
      '## Production is a different question',
      '📋 The deployment guides cover whether to run Compose in production or put the apps under systemd. The honest answer is that this repo does the latter, and the trade-offs are not obvious.',
    ],
  },
  {
    title: 'The admin panels, and how to log into both',
    category: 'Installation & Setup',
    status: 'published',
    excerpt:
      'Two separate admin interfaces with separate user tables, which happen to share a development password. Neither knows the other exists.',
    tags: ['admin', 'auth', 'credentials'],
    body: [
      'WordPress has one `/wp-admin`. This stack has two admin panels, and they share nothing but a convention.',
      '## Payload admin — port 3000',
      '✅ At `http://localhost:3000/admin`. This is where posts, pages, categories, media and users live. It is generated **from your collection config** — add a field to `Posts.ts` and the form grows a field with no admin code written.',
      '⚠️ The first load in development takes several seconds, because Next compiles the admin route on demand. That is not a problem with your install; the second load is fast.',
      '## Medusa admin — port 9000',
      '✅ At `http://localhost:9000/app`. Products, variants, prices, orders, regions and sales channels.',
      '## The development credentials',
      'Both use `admin@local.test` with the password `supersecret`.',
      '> They are the same string for convenience, not because the accounts are linked. **Two applications, two databases, two separate `users` tables.** Changing one password does nothing to the other.',
      '⚠️ Obviously, never carry these into anything reachable from the internet. The deployment guides cover real secrets.',
      '## The third credential, which is not a login',
      'The storefront does not log in at all. It holds a **Payload API key** and a **Medusa publishable key**, both generated during setup, and attaches them server-side.',
      'That is why the storefront can see drafts that an anonymous browser request to the Payload API cannot: same data, different access rules. Load `http://localhost:3000/api/posts` with no key and the drafts are missing.',
      '🚫 **The storefront itself has no authentication whatsoever.** Anyone who can reach port 4321 can delete any post, because the storefront is holding admin credentials on their behalf. That is a deliberate teaching simplification and a genuine threat model — the Security guides treat it properly.',
      '## Locked out',
      'Payload locks an account after repeated failed logins. Clearing `login_attempts` and `lock_until` on that row in `payload_crud` restores it.',
    ],
  },
]
