import type { Guide } from './types'

/**
 * Key Files & Folders — 7 guides.
 *
 * Third in the learning path. The Getting Started track already gives the
 * top-level tour; these go one level deeper, per application, and answer the
 * question that tour leaves open: *which of these files will I actually open?*
 */
export const keyFiles: Guide[] = [
  {
    title: 'The files you will actually edit, and the ones you never will',
    category: 'Key Files & Folders',
    status: 'published',
    excerpt:
      'Three applications hold hundreds of files. About fifteen of them are where real work happens, and knowing which fifteen saves weeks.',
    tags: ['structure', 'orientation', 'files'],
    body: [
      'A WordPress theme has a shape you learn once: `functions.php`, a template hierarchy, `style.css`. This repo has three shapes. Here are the files that matter.',
      '## The ones you will open constantly',
      '- `apps/cms/src/collections/*.ts` — your content model. **Adding a field here changes the database, the admin UI and the TypeScript types at once.**',
      '- `apps/storefront/src/pages/**` — every URL on the site. The file path *is* the route.',
      '- `apps/storefront/src/lib/payload.ts` and `medusa.ts` — every call to a backend goes through these two.',
      '- `apps/commerce/src/modules/*/models/*.ts` — Medusa data models.',
      '- `apps/commerce/src/workflows/*.ts` — multi-step commerce operations with rollback.',
      '## The ones you will open occasionally',
      '- `apps/cms/src/payload.config.ts` — wiring, not content. You visit it to register a new collection.',
      '- `apps/commerce/medusa-config.ts` — the same role for Medusa.',
      '- `apps/storefront/src/middleware.ts` — runs on every request.',
      '- `apps/storefront/src/actions/index.ts` — form handlers.',
      '- The three `.env` files.',
      '## The ones you will never touch',
      '- `apps/cms/src/payload-types.ts` — **generated**. Payload rewrites it from your collections. Editing it is always a mistake; your change disappears on the next generate.',
      '- `next-env.d.ts`, `vite-env.d.ts`, `*.tsbuildinfo` — tool bookkeeping.',
      '- `package-lock.json` — generated, but **do commit it**. It pins the exact resolved version of every transitive dependency.',
      '- `apps/commerce/src/modules/*/migrations/` — generated from your models, and once applied they are history. Write a new one rather than editing an old one.',
      '> The useful instinct: if a file has a header comment saying it is generated, believe it.',
      '## The trap',
      '⚠️ `apps/cms/src/collections/` and `apps/commerce/src/modules/` look like they do the same job, and they do not. Payload collections are **content**; Medusa modules are **commerce domain logic**. They live in different databases and cannot join.',
    ],
  },
  {
    title: "Payload's key files: config, collections and hooks",
    category: 'Key Files & Folders',
    status: 'published',
    excerpt:
      'One config file registers everything. Five collection files define the entire content model. A sixth file is generated and should never be edited.',
    tags: ['payload', 'structure', 'collections'],
    body: [
      'Payload is config-as-application. There is no admin UI for defining fields — the code *is* the definition, and the UI is generated from it.',
      '## `src/payload.config.ts` — the spine',
      'Everything is registered here, and it is worth reading top to bottom once. Its keys:',
      '- `collections` — the five content types, imported from `src/collections/`',
      '- `globals` — single-instance content; `SiteSettings` here',
      '- `endpoints` — custom REST routes bolted onto the API',
      '- `editor` — the Lexical rich-text configuration',
      '- `db` — the Postgres adapter and its connection string',
      '- `cors` and `csrf` — which origins may call the API',
      '- `typescript` — where to write the generated types',
      '## `src/collections/` — the content model',
      '✅ Five files, each one a content type: `Users.ts`, `Media.ts`, `Categories.ts`, `Posts.ts`, `Pages.ts`.',
      '`Posts.ts` is the one to read first. It demonstrates nearly every field type, access control, hooks, drafts and versioning in about two hundred lines.',
      '> Add a field to `Posts.ts`, save, and three things change at once: the Postgres column, the admin form, and the TypeScript type. That single fact is most of what makes Payload different from ACF.',
      '## `src/globals/SiteSettings.ts`',
      'A global is a collection with exactly one row — site title, announcement banner. The equivalent of WordPress options, but typed.',
      '## `src/hooks/slugify.ts`',
      'A **field-level** hook that derives a slug from the title. Field hooks transform one value; collection hooks in `Posts.ts` see the whole document.',
      '⚠️ It **strips** punctuation rather than replacing it, so `How to debug` and `How to debug?` produce the same slug — and `slug` is unique, so the second write fails. This has broken a seed mid-run.',
      '## `src/endpoints/`',
      '`schema.ts` and `postStats.ts` — custom routes for things no collection owns. ✅ Both drop to raw SQL against `information_schema`, which is exactly when raw SQL is reasonable: no user input reaches them.',
      '## `src/payload-types.ts` — generated, never edited',
      'Regenerated from your collections. It is how the storefront gets types for data it fetches over HTTP from another application.',
    ],
  },
  {
    title: "Medusa's key files: modules, workflows and API routes",
    category: 'Key Files & Folders',
    status: 'published',
    excerpt:
      'Four directories carry the weight. The module boundary is enforced by the framework, which is why some obvious things are impossible.',
    tags: ['medusa', 'structure', 'modules', 'workflows'],
    body: [
      'Medusa 2 is organised around **modules**, and the boundaries between them are real rather than conventional.',
      '## `medusa-config.ts`',
      'Database, Redis, CORS and the list of custom modules. A module that is not registered here does not exist, however complete its code.',
      '## `src/modules/` — the domain logic',
      'Two custom modules here:',
      '- `review/` — the review model, its service and its migrations',
      '- `ops/` — uptime samples, for the monitoring page',
      "Each module holds `models/` (the data model, in Medusa's DML), `service.ts` (extending `MedusaService`, which generates CRUD for you), `migrations/` and an `index.ts` that exports the definition.",
      '⚠️ **A module cannot query another module\'s tables.** Not "should not" — cannot. Reviews cannot join to products even though both live in `medusa_crud`.',
      '## `src/links/product-review.ts`',
      'Which is why this exists. `defineLink` creates a **link table** connecting a review to a product across the module boundary, and `query.graph` reads across it.',
      '> This is the single most surprising thing about Medusa 2 coming from any ORM. The isolation is the feature; links are the sanctioned way through it.',
      '## `src/workflows/` — multi-step operations',
      'Three files: create, update and delete a review. A workflow is a sequence of steps, each of which may define a **compensation** handler — an undo. If step 4 throws, the engine runs the compensations for 3, 2 and 1 in reverse.',
      '✅ This is genuinely tested. `src/scripts/test-compensation.ts` forces a failure and asserts the database is byte-for-byte unchanged, with not even a soft-deleted orphan left behind.',
      '## `src/api/` — the HTTP surface',
      "File-based routing, like Astro's. `src/api/store/reviews/route.ts` becomes `/store/reviews`.",
      '- `store/*` — public, requires the publishable key',
      '- `admin/*` — requires an admin JWT',
      '- `middlewares.ts` — registers validators and the rate limiter',
      '## `src/subscribers/` and `src/jobs/`',
      'Subscribers react to events; jobs run on a schedule. `uptime-check.ts` samples all three services every minute, which is where the monitor page gets its data.',
    ],
  },
  {
    title: "Astro's key files: pages, middleware, actions and lib",
    category: 'Key Files & Folders',
    status: 'published',
    excerpt:
      'The storefront owns no data at all. Every file here is about fetching from somewhere else and rendering it — which makes the structure unusually easy to predict.',
    tags: ['astro', 'structure', 'routing', 'middleware'],
    body: [
      '✅ **The storefront has no database connection.** Not a configuration choice — there is no adapter and no credentials. Everything arrives over HTTP. That constraint makes the file layout predictable.',
      '## `astro.config.mjs`',
      "Three lines that matter: `output: 'server'` (render per request, not at build), the Node standalone adapter, and the React integration for the one island.",
      '## `src/pages/` — the routes',
      'The file path **is** the URL. `src/pages/posts/[slug].astro` serves `/posts/anything`.',
      'Two kinds of file live here:',
      '- `.astro` — renders HTML',
      '- `.ts` under `pages/api/` — returns JSON, no HTML',
      '`posts/index.astro` is the best one to read first: it lists, filters, pages and deletes, all server-rendered.',
      '## `src/lib/` — where the backends live',
      'Every outbound call goes through here, and nothing else talks to a backend directly:',
      '- `payload.ts` — the Payload REST client, and where the `Authorization: users API-Key` header is attached',
      '- `medusa.ts` and `medusa-admin.ts` — the store and admin surfaces, which need different credentials',
      "- `lexical.ts` — converts Payload's rich-text node tree to HTML. ✅ Escapes every text node and href, and that escaping is unit-tested",
      '- `env.ts` — reads and validates configuration once',
      '- `rate-limit.ts`, `request-log.ts` — in-memory, feeding `/monitor`',
      '- `settle.ts` — so one dead backend degrades a page instead of killing it',
      '> Centralising the clients is why swapping a backend URL is a one-line change rather than a search across forty files.',
      '## `src/middleware.ts`',
      'Runs on **every** request: rate limiting and request logging.',
      "⚠️ It does not run on everything. Astro's `security.checkOrigin` rejects cross-origin non-GET requests with a 403 **upstream of middleware**, so those never reach the log. If your traffic graph and your users disagree, that gap is the reason.",
      '## `src/actions/index.ts`',
      "Astro Actions — typed form handlers. With `accept: 'form'` they take a real form post and work with JavaScript disabled.",
      '## `src/components/`',
      'All `.astro` and therefore zero JavaScript, except `ReviewFilter.tsx` — the single React island, loaded with `client:visible`.',
    ],
  },
  {
    title: 'Every environment variable, and what breaks without it',
    category: 'Key Files & Folders',
    status: 'published',
    excerpt:
      'Three .env files, no root one, and twenty-odd keys between them. Two are generated and cannot be invented by hand.',
    tags: ['env', 'configuration', 'secrets'],
    body: [
      'There is no `wp-config.php` here, and no single file that configures the stack. **There are three `.env` files and no root one**, because there are three independent applications.',
      '🚫 None are in git. `.gitignore` excludes `.env` everywhere.',
      '## `apps/cms/.env`',
      '- `DATABASE_URL` — points at **`payload_crud`**',
      '- `PAYLOAD_SECRET` — signs tokens. Change it and every existing session and API key becomes invalid',
      '- `NEXT_PUBLIC_SERVER_URL` — how Payload refers to itself in generated links',
      '- `PAYLOAD_CORS_ORIGINS` — feeds **both** `cors` and `csrf` in the config',
      '## `apps/commerce/.env`',
      '- `DATABASE_URL` — points at **`medusa_crud`**, a different database on the same server',
      '- `JWT_SECRET`, `COOKIE_SECRET` — admin session signing',
      '- `STORE_CORS`, `ADMIN_CORS`, `AUTH_CORS` — three separate lists. ⚠️ All are `localhost` by default; shipping that means production cannot read its own API',
      '- `REDIS_URL` — cache and job queue',
      '- `RATE_LIMIT_STORE_MAX`, `RATE_LIMIT_WINDOW_MS` — **240 per 60 seconds** on the store surface. This is the limit the products page N+1 runs into',
      '- `DEMO_FAIL_LINK_STEP` — ✅ the deliberate failure switch the compensation test flips. A real variable read at execution time, which is why the test exercises the true failure path',
      '## `apps/storefront/.env`',
      '- `PAYLOAD_URL`, `MEDUSA_URL` — where the backends are',
      '- `PAYLOAD_API_KEY` — ⚠️ **generated during setup, stored in the database.** Belongs to an admin user, so it carries admin permissions. A real secret',
      '- `MEDUSA_PUBLISHABLE_KEY` — also generated, also stored in the database, but **not a secret**: it identifies a sales channel and is designed to be public',
      "- `RATE_LIMIT_MAX`, `RATE_LIMIT_WINDOW_MS` — the storefront's own limiter, **120 per 60 seconds**. Three Postman runs inside a minute trips it",
      '## The two you cannot write by hand',
      '> Both API keys are **generated and stored in the databases**. You cannot invent them, and a database reset invalidates both.',
      'That is the whole reason `npm run setup` rewrites the storefront `.env` rather than asking you to. If the storefront starts returning 400 and 403 from both backends at once, these are why.',
    ],
  },
  {
    title: 'The generated folders, and why none of them are in git',
    category: 'Key Files & Folders',
    status: 'published',
    excerpt:
      'Seven directories appear after you run things and none belong in version control. One of them caused a real bug by not being cleaned.',
    tags: ['git', 'build', 'gitignore'],
    body: [
      'After a full install and run, directories appear that were not in the clone. All of them are reproducible, and none are committed.',
      '## What gets ignored',
      '- `node_modules/` — three of them, several gigabytes',
      '- `.next/` — the Payload/Next build',
      '- `.medusa/` — the Medusa build, including the compiled admin panel',
      "- `.astro/` — Astro's type generation and dev state",
      '- `dist/`, `build/` — compiled output',
      '- `logs/` and `*.log` — written by the dev scripts',
      '- `backups/` — produced by `npm run db:export`',
      '- `apps/cms/public/media/` — uploaded files',
      '- `postman/local.postman_environment.json` — contains generated keys',
      '## The rule',
      '> If a command creates it, git should not track it. If a human writes it, git should.',
      '`package-lock.json` is the edge case that confuses people: it is **generated but committed**, because its job is to make installs reproducible. Ignoring it defeats its only purpose.',
      '## The media directory bug',
      '⚠️ `apps/cms/public/media/` is **on disk, not in the database**. So `npm run db:reset` wipes the database and leaves every file behind.',
      'The seed then re-uploaded the same filenames, Payload refused to collide, and appended `-1` to each. The directory grew on every reset — 192 files for 32 posts — while the database correctly reported one image each.',
      '✅ Fixed by having the seed clear the directory before uploading. It now converges: 264 files for 88 guides, no suffixes, however many times you run it.',
      '> The general lesson: **a reset that only truncates tables is not a reset** if any part of your state lives on disk. Uploads, caches and generated images all need the same treatment.',
      '## Why this matters for deployment',
      "The same fact bites in production. `apps/cms/public/media` lives on the server's filesystem, so a container rebuild loses every upload. 📋 Moving uploads to S3-compatible storage is the fix; until then, the media directory must be in your backups — which `npm run db:export` already handles.",
    ],
  },
  {
    title: 'Four package.json files, and what each is responsible for',
    category: 'Key Files & Folders',
    status: 'published',
    excerpt:
      'The root one has no dependencies at all. That is deliberate, and it explains why there are three node_modules instead of one workspace.',
    tags: ['npm', 'monorepo', 'scripts'],
    body: [
      'Four `package.json` files: one at the root and one per application. They do genuinely different jobs.',
      '## The root one — orchestration only',
      '✅ **It has no dependencies.** None. It exists purely to run commands across the three apps:',
      '- `npm run dev` — all three under `concurrently`, colour-coded per service',
      '- `npm run typecheck` — all three in sequence',
      '- `npm run setup` — the one-shot installer',
      '- `npm run db:up`, `db:down`, `db:reset` — Docker',
      '- `npm run db:export`, `db:import` — backup and restore, including the media directory',
      '- `npm test`, `npm run postman:test` — the test suites',
      '> Read the root scripts block once. It is the most efficient map of the repo that exists, because every routine operation has a name there.',
      '## The three app ones',
      'Each is a genuinely independent project with its own lockfile and its own `node_modules`.',
      '## Why not one npm workspace',
      'This is the question everyone asks, and the answer is version conflicts.',
      'Payload 3 runs inside **Next 16**. Medusa brings its own framework and its own build tooling. Astro needs neither. A workspace hoists dependencies to a shared root and forces the three to agree on shared transitive versions — and they genuinely do not agree.',
      '⚠️ They also have **different deploy targets**. The storefront can go on a tiny box; Payload needs 2.34 GB to build. Keeping them separate means deploying one without rebuilding the others.',
      'The cost is honest: three installs, three lockfiles, more disk. The benefit is that upgrading Astro cannot break Medusa.',
      '## A real wart',
      "⚠️ Running `npm install --prefix apps/commerce` from inside `apps/storefront` resolves the prefix **relative to your current directory** and silently creates `apps/storefront/apps/commerce/`. Four such files were committed in this repo's initial import and sat there unnoticed.",
      'Always run npm scripts from the repository root, where the root `package.json` means every path resolves the way you expect.',
    ],
  },
]
