import type { Guide } from './types'

/** Operations & Tooling — 8 guides. */
export const operations: Guide[] = [
  {
    title: 'Are there plugins for SEO and caching in this stack?',
    category: 'Operations & Tooling',
    status: 'published',
    excerpt:
      'Yes, but far fewer, and installing one means npm plus a config edit plus a restart. The honest comparison to 60,000 WordPress plugins.',
    tags: ['plugins', 'seo', 'caching'],
    body: [
      'The honest answer first: WordPress has roughly sixty thousand free plugins, installable from inside the admin with no build step. These three projects have a few dozen official packages each.',
      'There is no marketplace, no one-click install, and far less "somebody already solved this". That is a genuine loss and worth knowing before you plan a project.',
      'What you gain is that what you do install is typed, versioned, and cannot silently inject into your `<head>` or rewrite your queries.',
      '## Payload plugins that exist',
      '- `@payloadcms/plugin-seo` — meta fields and previews',
      '- `@payloadcms/plugin-form-builder` — the Gravity Forms analogue',
      '- `@payloadcms/plugin-redirects` — redirect management',
      '- `@payloadcms/plugin-search` — a search index collection',
      '- `@payloadcms/plugin-nested-docs` — parent/child pages and breadcrumbs',
      '- `@payloadcms/storage-s3` — move uploads off local disk',
      '## Astro integrations',
      '- `@astrojs/sitemap` — sitemap.xml',
      '- `@astrojs/rss` — a feed',
      '- `@astrojs/partytown` — third-party scripts off the main thread',
      '- `astro-seo` — a community meta and Open Graph component',
      '## Medusa modules',
      '- `@medusajs/payment-stripe` — payments',
      '- `@medusajs/file-s3` — file storage',
      '- `@medusajs/notification-sendgrid` — email',
      '## How you install one',
      'npm install it in the right app, add it to that app\'s config array, restart. For Payload that is the `plugins` array in `payload.config.ts` — which in this project is currently **empty**, so it is a clean place to start.',
      '## Caching is the awkward one',
      '**There is no caching plugin.** Nothing in this project caches pages. Astro re-renders every request, Medusa has a Redis cache for module data, and Payload has none.',
      'Page caching here is a CDN or reverse-proxy concern, not something you install. Coming from WP Super Cache, that is a real adjustment.',
      '## Going deeper',
      'The plugins guide covers installation step by step and the four questions worth asking before adding any dependency.',
    ],
  },
  {
    title: 'How to build a multilingual site without WPML',
    category: 'Operations & Tooling',
    status: 'published',
    excerpt:
      'Payload localises fields inside one document rather than duplicating posts per language. That difference changes how you query.',
    tags: ['i18n', 'localization', 'wpml'],
    body: [
      'With WPML or Polylang you install a plugin, pick languages, and each post gets a translated **copy** linked to the original. Two languages means two posts.',
      'Payload does it differently, and the difference is structural rather than cosmetic.',
      '## Field-level localization',
      'You declare locales once in `payload.config.ts`, then mark individual fields `localized: true`. One document holds every translation of those fields.',
      '> One post, one ID, many language values. There is no "translation of" relationship, because there is no second post.',
      '## Why that matters in practice',
      '- A relationship pointing at that post keeps working in every language. Under WPML you have to decide which translation a link refers to.',
      '- Fields you do not mark localized are shared, so a publish date or a category stays in sync automatically.',
      '- Queries take a `locale` parameter and return that language\'s values in the normal field names, so your rendering code does not change.',
      '- Migrating from WPML is not a copy — it is a restructure, because you are collapsing N posts into one.',
      '## The Astro half',
      'Astro has built-in i18n routing: configure locales and a default, and it handles prefixed URLs like `/de/posts/...` and locale detection. You then pass the locale through to your Payload queries.',
      '## The Medusa half',
      'Commerce multilingualism is partly a **region** concern rather than a translation one — currency, tax and available payment providers vary by region, independently of the language a visitor reads.',
      '## Not configured here',
      'Both features are genuinely built in, and **neither is configured in this project**. There are no locales in the Payload config and no i18n block in the Astro config. The shapes above are the map, not a transcript — you cannot run them against this repo as it stands.',
      '## Going deeper',
      'The plugins guide covers the configuration for both and the WPML comparison in more detail.',
    ],
  },
  {
    title: 'How to browse PostgreSQL with pgAdmin and other tools',
    category: 'Operations & Tooling',
    status: 'published',
    excerpt:
      'The phpMyAdmin question. Several good options, one connection detail that catches everyone, and one warning about editing rows.',
    tags: ['postgres', 'pgadmin', 'tooling'],
    body: [
      'Coming from phpMyAdmin or Adminer, you want a window into the database. There are several, and they all need the same five values.',
      '## The connection details',
      '- Host: `localhost`',
      '- **Port: 5433** — not 5432',
      '- User: `postgres`',
      '- Password: `postgres`',
      '- Databases: `payload_crud` and `medusa_crud`',
      'The port is the thing that catches everyone. The container maps 5433 on your machine to 5432 inside, deliberately, so it cannot collide with a Postgres already installed locally.',
      '## The options',
      '- **pgAdmin 4** — the closest thing to phpMyAdmin, a web UI, free. Heavy, but familiar if you are used to a browser-based tool.',
      '- **DBeaver** — free desktop client, works with many engines, a better query editor than pgAdmin.',
      '- **TablePlus** — desktop, paid with a limited free tier, the nicest interface of the group.',
      '- **Beekeeper Studio** — open-source desktop client.',
      '- **Adminer** — a single PHP file, the literal analogue of phpMyAdmin. Can be added to the Docker Compose file as another service.',
      '- **psql** — already wired up. `npm run db:psql` opens a shell inside the container with nothing to install.',
      '## The psql commands worth knowing',
      '- `\\l` — list databases',
      '- `\\c payload_crud` — connect to one',
      '- `\\dt` — list tables',
      '- `\\d posts` — describe a table',
      '- `\\x` — toggle expanded output, which makes wide rows readable',
      '- `\\q` — quit',
      '## The warning that matters',
      'A GUI lets you edit rows directly. In WordPress, editing `wp_posts` by hand is risky. **Here it is architecturally wrong.**',
      '> A review edited in pgAdmin skips its Medusa workflow, so no link row is written and no event is emitted. A post edited in pgAdmin skips Payload\'s hooks, so no slug is derived and no version is recorded.',
      'Read freely. Write through the APIs.',
      '## Going deeper',
      'The tools guide has connection steps for each client and the full psql command table.',
    ],
  },
  {
    title: 'Which VS Code extensions to install for this stack',
    category: 'Operations & Tooling',
    status: 'published',
    excerpt:
      'A short list that earns its place, plus the one extension without which .astro files are unreadable.',
    tags: ['vscode', 'tooling', 'editor'],
    body: [
      'Coming from a PHP setup you probably have Intelephense and a linter. This stack needs a different short list, and one of them is essential rather than nice to have.',
      '## The essential one',
      '**Astro** (`astro-build.astro-vscode`). Without it a `.astro` file has no syntax highlighting, no IntelliSense and no type checking in the frontmatter — it reads like a text file with angle brackets. Install this first.',
      '## Strongly recommended',
      '- **ESLint** — all three apps are configured for it; surfacing problems inline beats finding them in a terminal.',
      '- **Prettier** — consistent formatting across `.ts`, `.astro` and `.tsx`.',
      '- **Docker** — the database and Redis run in containers; being able to see status and logs without leaving the editor is worth the install.',
      '## Worth having',
      '- **REST Client** — runs the `docs/requests.http` file in this repository directly. Every endpoint in the stack is already written out there, so you get a working API client with no setup.',
      '- **Error Lens** — puts TypeScript errors inline instead of in a panel. Opinionated, and very good when learning a new type system.',
      '- **PostgreSQL** — query the database from the editor, as an alternative to a separate GUI.',
      '## If you use React',
      'The storefront has exactly one React island. If you add more, the usual React and JSX tooling applies — but note that most components here are `.astro` and ship no JavaScript, so React tooling matters less than it would in a Next project.',
      '## What you can skip',
      'You do not need a PHP extension, and you do not need anything WordPress-specific. There is no `functions.php`, no theme to lint, and no plugin boilerplate to generate.',
      '## Checking it worked',
      'Open any `.astro` file. If the frontmatter between the fences is syntax-highlighted as TypeScript and hovering a variable shows its type, the Astro extension is active.',
      '## Going deeper',
      'The tools guide lists the extensions with IDs and covers the rest of the local toolkit.',
    ],
  },
  {
    title: 'How to debug when a request fails',
    category: 'Operations & Tooling',
    status: 'published',
    excerpt:
      'Four layers can produce an error. Identifying which one is talking is most of the work, and the status code usually tells you.',
    tags: ['debugging', 'troubleshooting', 'logs'],
    body: [
      'With WordPress there is one program, so an error is in one place. Here a failed request may have been rejected by any of four layers, and each produces a different-looking error.',
      '## The four layers',
      '1. The browser or curl — never reached the server',
      '2. Astro — middleware, a page, or one of its endpoints',
      '3. Payload or Medusa — the backend that owns the data',
      '4. Postgres — a constraint or a connection problem',
      '## Read the status code first',
      '- **400** from Medusa — usually a missing publishable key header',
      '- **401** — no credentials, or the wrong kind',
      '- **403** — credentials present but not permitted; from Astro on a `DELETE`, almost always the missing `Origin` header',
      '- **404** — the route does not exist, or a read-access rule narrowed it out of existence',
      '- **422** — validation failed; the body will name the field',
      '- **429** — rate limited',
      '- **500** — the backend threw; check its log',
      '- **502** — your BFF reached the backend and the backend failed',
      '## The 404 that is really access control',
      'Worth internalising: a draft post requested anonymously returns 404, not 403. The read rule narrows the query to published documents, so the draft genuinely does not exist for that request. Nothing is hidden — it was never in the result set.',
      '## Where to look',
      '`npm run logs` tails all three services. `npm run logs:errors` greps warnings and errors out of them.',
      'The storefront also keeps an in-memory log of recent requests with status and duration, visible on its monitor page.',
      '## The blind spot',
      'That request log cannot see anything rejected **before** middleware runs — including Astro\'s own origin check. So a 403 from a missing `Origin` header never appears there.',
      '> If your traffic graph and your users disagree about whether requests are arriving, that gap is where to look.',
      '## The escalation ladder',
      'Restart one service, then all three, then reset the database, then reinstall dependencies. Work down it and stop at the first thing that works.',
      '## Going deeper',
      'The troubleshooting chapter is organised as symptom, cause, fix, with the literal error strings as headings.',
    ],
  },
  {
    title: 'Draft: how to migrate an existing WordPress site to this stack',
    category: 'Operations & Tooling',
    status: 'draft',
    excerpt:
      'Unfinished notes on content migration. Left as a draft deliberately, so the access-control rules have something to hide.',
    tags: ['migration', 'wordpress', 'draft'],
    body: [
      'This post is an unpublished draft. It exists so that the draft machinery has something real to demonstrate: fetch the posts list anonymously and it will not appear, because the read access rule narrows the query to published documents.',
      'Authenticate with the API key, or pass the draft flag while logged in, and it appears.',
      '## Rough notes so far',
      '- Export `wp_posts` and `wp_postmeta`, and decide which meta keys become real Payload fields. There is no key-value store on the other side, so every one needs a home in the config or it has nowhere to go.',
      '- ACF Flexible Content layouts map reasonably well onto Payload blocks, but each layout needs declaring up front.',
      '- The media library is the slow part. Files need re-uploading so Payload can generate its own derivative sizes; the URLs in post content need rewriting afterwards.',
      '- Rich text is the hard part. WordPress stores HTML; Payload stores a Lexical node tree. Converting means parsing the HTML and emitting nodes, and anything unusual needs a decision.',
      '- Redirects matter. Permalink structures rarely survive a migration unchanged, so plan the old-to-new URL map before cutover rather than after.',
      '- WooCommerce products to Medusa is a separate project from content migration, with its own variant and pricing model to reconcile.',
      '## Still to write',
      'A worked example with a real export, and an honest estimate of how long each stage takes.',
    ],
  },
  {
    title: 'Draft: a performance budget for this stack',
    category: 'Operations & Tooling',
    status: 'draft',
    excerpt:
      'Working notes on what to measure and what to cap. Unpublished until the numbers are measured rather than guessed.',
    tags: ['performance', 'draft'],
    body: [
      'Another deliberate draft. Anonymous requests will not see it; authenticated ones will.',
      '## What is worth measuring',
      '- Time to first byte on a server-rendered page, which is dominated by backend round trips rather than by rendering',
      '- JavaScript shipped per route. Most pages here send **zero**, and the one island is the exception worth watching',
      '- Backend calls per page. The products page currently makes one request per product on top of the list request',
      '## What is not yet decided',
      'Whether to set a hard cap on island count, and where page caching should live given there is none today.',
      'Numbers go here once they are measured on something other than a laptop.',
    ],
  },
  {
    title: 'Draft: deployment notes for three services',
    category: 'Operations & Tooling',
    status: 'draft',
    excerpt:
      'Rough notes on taking this to production. Three deploys, two databases, and several things this repo deliberately does not do.',
    tags: ['deployment', 'production', 'draft'],
    body: [
      'A third draft, kept unpublished on purpose.',
      '## The shape of the problem',
      'Three applications means three build pipelines and three deploys that can be out of step with each other. WordPress has one artefact; this has three, and they must agree on API contracts across versions.',
      '## Known blockers in this repo',
      '- Payload runs in `push` mode, so there are no migration files to apply on deploy',
      '- Files are stored on local disk, so a container rebuild loses uploads',
      '- The storefront has no authentication at all',
      '- Secrets are development placeholders',
      '## Still to work out',
      'Whether the three services deploy together or independently, and what the rollback story is when only one of them moves.',
    ],
  },
  {
    title: 'How to read logs across three services',
    category: 'Operations & Tooling',
    status: 'published',
    excerpt:
      'Three processes, three formats, one filesystem. Two of them you have to guess the severity of, and one tells you honestly.',
    tags: ['logs', 'debugging', 'operations'],
    body: [
      'With one program, logs are one file. With three, the first question is always which of them is talking.',
      '## Where they are',
      '✅ `npm run logs` tails all three. `npm run logs:errors` greps warnings and errors out of them.',
      '- Payload and Medusa are teed to `logs/` by the dev scripts',
      '- Astro writes its own **JSON-lines** log to `.astro/dev.log`',
      '⚠️ **Astro backgrounds its own dev server**, so the tee captures only the launch banner. The real log is Astro\'s own file. This surprises everyone once.',
      '## Two formats, and the lesson in it',
      'Astro emits structured JSON with a real `level` field, so the log viewer **reads** the severity. Payload and Medusa print human-formatted text, so the viewer **guesses** it from the words in the line.',
      '> Put those two paths side by side and the argument for structured logging makes itself: one is exact, the other is a regex over prose.',
      'The guess is wrong sometimes — an informational line containing the word "error" gets misfiled. That imprecision is visible rather than hidden.',
      '## One refinement worth copying',
      'Astro logs every request at info level, **including 5xx**. Taken literally, a page full of 500s reads as "no errors". The viewer upgrades `[5xx]` to error and `[4xx]` to warn. ✅ Trusting a structured level is right; trusting it blindly is not.',
      '## In production this does not work',
      '⚠️ Reading files off disk works only because all three share a machine. Two instances means two sets of logs on two boxes, and a question like "what happened to this user\'s request" needs them aggregated with a shared request id — which nothing here does.',
      '## The blind spot',
      'The in-app request log cannot see anything rejected **before** middleware, including the origin check\'s 403s. The framework\'s own log sits further out and does record them.',
    ],
  },
  {
    title: 'What to do when production breaks',
    category: 'Operations & Tooling',
    status: 'published',
    excerpt:
      'An escalation ladder, cheapest first, and the one rule that matters more than any individual step.',
    tags: ['operations', 'incident', 'debugging'],
    body: [
      'The ladder, and when to stop climbing.',
      '## First, establish what is actually broken',
      '✅ One command answers it: the storefront\'s health endpoint reports both backends and returns **503** if either is unreachable.',
      'Then separate the two questions that look identical from outside: **is it down, or is it wrong?** A service returning 200 to a health check while every real request 500s is the classic trap, and the reason uptime and request monitoring are both worth having.',
      '## The ladder',
      '1. **Restart one service.** Fixes a wedged process or stale environment. Seconds, and no data risk.',
      '2. **Restart all three.** Fixes ordering problems — a service that started before its database was ready.',
      '3. **Check disk and memory.** A full disk presents as unrelated mysterious failures.',
      '4. **Check the database is accepting connections.** `too many clients` is a different problem from a crash.',
      '5. **Roll back the deploy.** If it broke after a release, stop debugging and go back.',
      '6. **Restore from backup.** Only for data loss or corruption, never for an application bug.',
      '⚠️ **Stop at the first step that works, and write down what it was.** The instinct to keep going and find the root cause is right — afterwards, not during.',
      '## The rule',
      '> Restore service first. Understand second.',
      'A root cause found while users are down is expensive. The same root cause found an hour later, from logs, is free.',
      '## Afterwards',
      'Write down what broke, what you did, and what would have caught it earlier. That last part is the only one that changes anything — most incidents are a monitoring gap as much as a code defect.',
      '⚠️ **Reaching step 6 means losing everything since the last backup.** That is why the export runs on a schedule and why you restore one before you need it.',
    ],
  },
  {
    title: 'What this stack actually costs to run',
    category: 'Operations & Tooling',
    status: 'published',
    excerpt:
      'A realistic monthly figure for a small production deployment, and the three line items that grow faster than you expect.',
    tags: ['operations', 'cost', 'hosting'],
    body: [
      'Worth knowing before you promise someone a price.',
      '## The honest baseline',
      'One 4 GB VPS runs everything — three services, Postgres and Redis. That is roughly **five to fifteen euros a month**, and it genuinely is the whole bill for a small site.',
      '⚠️ **Compare that to five-euro shared hosting fairly.** Shared hosting includes backups, updates, monitoring and somebody else being responsible at 3am. On a VPS you are that person. The hosting is cheap; the operational load is the real cost.',
      '## Where it grows',
      '**Managed databases.** Moving Postgres off the box is the usual first step as traffic grows, and managed Postgres typically costs more than the server did. It buys backups, failover and patching.',
      '**Object storage.** Cheap to store, and **egress is what costs**. Images served directly from a bucket to visitors can cost more than the storage by an order of magnitude. A CDN in front changes the arithmetic.',
      '**A second server.** The jump from one to two is the expensive one: you also need a load balancer, shared file storage and probably managed databases, because the single-box shortcuts stop working.',
      '## The thing that catches people',
      '> Bandwidth is free until it is not.',
      'Most providers include a generous allowance and charge sharply beyond it. A popular page with large unoptimised images is the usual cause. ⚠️ **Nothing in this repo optimises images** — the cover images are served at full size and resized by CSS.',
      '## Keeping it down',
      '- Serve images through a CDN with on-the-fly resizing',
      '- Cache pages at the edge — this stack re-renders every request today',
      '- Right-size the box. 4 GB is for the **build**; runtime needs 1.2 GB. Building elsewhere lets you run a smaller server.',
      '- Measure before upgrading. The instinct to add RAM usually precedes knowing what is using it.',
    ],
  },
]
