import type { Guide } from './types'

/** Performance — 6 guides. */
export const performance: Guide[] = [
  {
    title: 'The N+1 on the products page, left visible on purpose',
    category: 'Performance',
    status: 'published',
    excerpt:
      'One request for the list, then one more per product. It was invisible at four products and obvious at fifteen — which is exactly how an N+1 behaves.',
    tags: ['performance', 'n+1', 'medusa'],
    body: [
      '✅ **This is real and running.** The products page fetches the product list, then loops the result and fetches reviews for each one. Fifteen products means sixteen requests.',
      '## Why it is not fixed',
      'Because recognising the shape matters more than this particular instance. The page says so on itself rather than hiding it.',
      '## It got worse when the catalogue grew',
      'At four products it was five requests and nobody noticed. At fifteen it is sixteen, and Medusa\'s store surface is rate limited to **240 requests per 60 seconds**.',
      '⚠️ **That works out at roughly fifteen page loads a minute** before the storefront starts getting 429s and the page returns a 500. I hit this during testing and briefly thought the deployment was broken.',
      '> That is the characteristic shape of an N+1: invisible until the collection grows, then it fails suddenly rather than degrading.',
      '## Why it exists at all',
      'Module isolation. Reviews live in a custom module, products in Medusa\'s own, and a module cannot join to another module. The route that returns one product with its reviews uses the link table and `query.graph`; there is no equivalent that takes fifteen product ids at once because nobody wrote one.',
      '## The three fixes, in order',
      '1. **A batch endpoint** — one route taking many product ids and resolving all their reviews in one pass. The right answer, and the one the docs sketch.',
      '2. **Cache the aggregate.** Ratings change rarely; a short TTL removes most of the traffic.',
      '3. **Denormalise.** Store the average on the product. Fastest to read, and now you own keeping it correct.',
      '## How to see it',
      'Load the products page and watch Medusa\'s log. Count the `GET /store/products/.../reviews` lines. The number equals your product count, every single page view.',
    ],
  },
  {
    title: 'How to decide what depth should be',
    category: 'Performance',
    status: 'published',
    excerpt:
      'Payload\'s depth parameter is the cheapest performance lever in the stack, and the default is higher than you usually need.',
    tags: ['performance', 'payload', 'depth'],
    body: [
      'Every Payload read takes a `depth`, and most people never change it. It is the difference between one query and several.',
      '## What it controls',
      '- `depth=0` — `category: 3`. Just the id. One query.',
      '- `depth=1` — `category: { id: 3, name: "Frontend", slug: "frontend" }`. Joined.',
      '- `depth=2` — also expands relationships **inside** the category.',
      '**The default is 2**, which is almost always more than you need.',
      '## The rule',
      '> Ask for the depth your template renders, and not one level more.',
      '- Building a filter or checking an id — `depth=0`',
      '- Rendering a card that shows the category name — `depth=1`',
      '- A relationship of a relationship — `depth=2`, and expect to pay',
      '## It is not linear',
      '⚠️ On a list of fifty posts, depth 1 joins fifty categories. Depth 2 then expands whatever those categories point at, for each one. The cost compounds per row, which is why a list endpoint is where depth matters and a single-document read is where it rarely does.',
      '## The gotcha that looks like a bug',
      '`coverImage` is an upload relationship. At `depth=0` it is a number, so `imageUrl()` returns null and **no image renders** — with no error anywhere.',
      '✅ That is why the posts list passes `depth: 1` and the single post page `depth: 2`. If an image silently fails to appear, check the depth before anything else.',
      '## Also worth knowing',
      '`select` narrows which **fields** come back, where `depth` controls how far relationships expand. They compose: a shallow read of three named fields is dramatically cheaper than the default.',
    ],
  },
  {
    title: 'Indexes, and the ones this schema already has',
    category: 'Performance',
    status: 'published',
    excerpt:
      'Which indexes exist, why unique fields get one free, and how to tell whether a query is using the one you added.',
    tags: ['performance', 'postgres', 'indexes'],
    body: [
      'An index is a lookup table the database maintains so it does not have to read every row. Getting them right is most of query performance.',
      '## What this schema has ✅',
      '- Every primary key, automatically',
      '- Every `unique: true` field — `posts.slug`, `categories.slug`, `pages.slug` — because a unique constraint **is** an index',
      '- Explicit `index: true` on the slug fields',
      '- Medusa\'s review model declares a composite index on `(status, created_at)`',
      '- Partial indexes on `deleted_at IS NULL` across Medusa, because almost every query filters out soft-deleted rows',
      'That last pattern is worth stealing. A partial index covers only the rows you actually query, so it is smaller and faster than one over the whole table.',
      '## Why the composite one is ordered that way',
      '`(status, created_at)` serves "approved reviews, newest first" — the exact query the store surface makes. **Column order matters**: this index helps a query filtering on `status`, and does not help one filtering only on `created_at`.',
      '> An index on `(a, b)` can serve a query on `a`, or on `a` and `b`. It cannot serve one on `b` alone.',
      '## How to tell if yours is used',
      'Put `EXPLAIN ANALYZE` in front of the query in psql. Look for **Index Scan** rather than **Seq Scan**. A sequential scan on a large table is the thing you are hunting.',
      '⚠️ **Postgres will ignore your index if the table is small.** On a few hundred rows a sequential scan genuinely is faster, so testing index changes against seed data can mislead you. Test against production-shaped volume.',
      '## The cost',
      'Indexes are not free. Each one is written on every insert and update, and takes disk. Index the columns you filter and sort on, not every column.',
      'Chapter 10 of the course opens both schemas up if you want to see all of them.',
    ],
  },
  {
    title: 'Connection pooling, and the limit you will hit first',
    category: 'Performance',
    status: 'published',
    excerpt:
      'Three Node processes sharing one Postgres. Nothing in this repo configures pool sizes, which is fine until suddenly it is not.',
    tags: ['performance', 'postgres', 'pooling'],
    body: [
      '📋 **Nothing here configures a pool.** Both ORMs use their defaults and the stack is small enough that it works. This is what to know before it stops working.',
      '## What a pool is',
      'Opening a Postgres connection is expensive — a process fork on the server side. So clients keep a pool of open connections and lend them out per query.',
      '## The arithmetic that bites',
      'Postgres defaults to **`max_connections = 100`**. Against that:',
      '- Payload holds a pool',
      '- Medusa holds a pool',
      '- Each **instance** of each holds its own',
      '⚠️ **Pools are per process, not per application.** Two Payload instances with a pool of 10 is 20 connections, and the number you must reason about is instances × pool size, plus anything else connecting — your psql session, a GUI client, a backup job.',
      '> The symptom is `FATAL: sorry, too many clients already`, and it arrives under load rather than in testing.',
      '## Sizing it',
      'Bigger is not better. Each connection costs memory on the server, and a pool larger than the database can usefully serve just moves the queue. A common starting point is `(cores × 2) + effective_spindles` — single digits for a small box, not fifty.',
      '## When you need PgBouncer',
      '📋 Not yet, here. Reach for it when the number of application instances grows past what `max_connections` comfortably allows — it multiplexes many client connections onto few database ones.',
      '⚠️ **Transaction-mode pooling breaks prepared statements and session state.** ORMs that rely on either need configuring for it. Adding PgBouncer is not transparent.',
      '## What to do today',
      'Nothing, probably — but know the number. `select count(*) from pg_stat_activity;` tells you where you stand, and it is a useful thing to look at before scaling rather than after.',
    ],
  },
  {
    title: 'Where caching could go, and why none of it exists yet',
    category: 'Performance',
    status: 'published',
    excerpt:
      'Five distinct layers, one of which is already running for a different reason. Nothing caches pages, and that is the honest starting point.',
    tags: ['performance', 'caching', 'redis', 'cdn'],
    body: [
      '📋 **Nothing in this repo caches a page.** Astro re-renders every request, Payload has no cache, and the Redis that is running serves Medusa\'s modules rather than your pages.',
      'Coming from WP Super Cache or LiteSpeed Cache, that is a real adjustment — on WordPress a cache plugin is the first thing you install.',
      '## The five layers, outermost first',
      '**1. CDN.** Caches whole responses at the edge. Highest leverage for a content site, and the closest thing to a cache plugin. Your pages are server-rendered and mostly identical for everyone, so they cache well.',
      '**2. Reverse proxy.** Caddy or nginx caching in front of the app. Same idea, one hop closer.',
      '**3. HTTP headers.** `Cache-Control` and `ETag` on your own endpoints, so browsers and proxies know what is reusable. Cheapest to add — and nothing here sets them.',
      '**4. Application cache.** Redis, holding computed values like the rating aggregates behind the N+1. ✅ Redis is already running and already connected.',
      '**5. Database.** Postgres caches its own pages; mostly not your problem.',
      '## Start at 3 and 4',
      'Header caching and an application cache for the expensive aggregates would remove most of the load this app generates, and neither needs new infrastructure.',
      '## The hard part is invalidation',
      '⚠️ **A cache is a promise that stale data is acceptable for a known period.** Decide that period deliberately. The seam already exists: `Posts.afterChange` currently only logs, and the comment says plainly that it is where a purge belongs.',
      '## What must never be cached',
      'Anything that varies by caller. The storefront serves drafts to an authenticated request and hides them otherwise — cache that response shared and you leak unpublished content to everyone.',
      '> Cache what is the same for everybody. Think twice about anything else.',
    ],
  },
  {
    title: 'Measure before you optimise — what to measure here',
    category: 'Performance',
    status: 'published',
    excerpt:
      'The stack already reports p50 and p95, uptime and build sizes. What those numbers mean, and the three things nothing measures yet.',
    tags: ['performance', 'monitoring', 'profiling'],
    body: [
      'Optimising without measuring is how afternoons disappear into code that was never slow.',
      '## What is already measured ✅',
      '- **Request duration, p50 and p95**, in the storefront\'s in-memory request log, visible on the monitor page',
      '- **Uptime and latency per service**, sampled every minute by a scheduled job in Medusa',
      '- **Island JavaScript cost** — the one React island is measured in the docs rather than estimated',
      '- **Build and runtime memory** — 834 MB running, 2.34 GB to build Payload',
      '## Why p95 and not an average',
      '> An average hides the slow tail, and the slow tail is the only part anyone complains about.',
      'If p50 is 40 ms and p95 is 900 ms, one request in twenty is dreadful and the mean says everything is fine.',
      '## What nothing measures yet 📋',
      '- **Core Web Vitals.** No real-user measurement. Lighthouse against the deployed site is a ten-minute start.',
      '- **Database query time.** Enable `pg_stat_statements` and you get the slowest queries ranked — usually the fastest route to a real win.',
      '- **Load behaviour.** Nothing has ever had concurrent traffic. A few minutes with `k6` or `autocannon` answers where it falls over, and the N+1 means the products page will fall over first.',
      '## The order that works',
      '1. Measure, and write the number down',
      '2. Find the biggest single contributor — not the one that is most interesting to fix',
      '3. Change one thing',
      '4. Measure again',
      '5. Keep it only if the number moved',
      '⚠️ **Step 5 is the one people skip.** Plenty of optimisations make code harder to read and change nothing measurable. Without the second measurement you cannot tell which ones.',
      '## The blind spots',
      'The request log is in-memory and per-process: it resets on restart, and a second instance sees only its own traffic. It also cannot see anything rejected before middleware — including the origin check\'s 403s. Knowing where a measurement is blind is part of reading it.',
    ],
  },
]
