import type { Guide } from './types'

/** Security — 6 guides. */
export const security: Guide[] = [
  {
    title: 'The storefront has no authentication, and what that means',
    category: 'Security',
    status: 'published',
    excerpt:
      'Not a missing feature — a threat model. The storefront holds an admin-capable API key and authenticates nobody, so anyone who reaches it can delete anything.',
    tags: ['security', 'auth', 'threat-model'],
    body: [
      '🚫 **There is no authentication in the storefront.** None. This is the most important security fact about this repo and it is worth stating as a threat model rather than a TODO.',
      '## What an attacker can do',
      'Anyone who can reach port 4321 can:',
      '- Create, edit and delete any post',
      '- Moderate reviews — approve, reject, delete',
      '- Read drafts, which are hidden from anonymous Payload queries but not from the storefront',
      'They do not need credentials, because **the storefront has them**. It holds `PAYLOAD_API_KEY`, which belongs to an admin user, and attaches it server-side to every request.',
      '## Why it is built this way',
      'Deliberately, for teaching. Adding auth would mean a login page, sessions, and a guard on every mutating route — real work that would obscure the thing each page is demonstrating.',
      '> The danger is that it does not *look* insecure. The pages render, the API works, nothing warns you. It is only insecure the moment it is reachable by someone else.',
      '## Access control does not save you',
      'Payload\'s access rules are excellent and irrelevant here. They answer "what may **this user** do", and the storefront always presents the same admin user. The rules are working exactly as designed; the design assumes the caller is authenticated, and it is not.',
      '## Fixing it, cheapest first',
      '1. **Do not expose it.** On a laptop behind a firewall this is a non-issue.',
      '2. **Basic auth at the proxy** on the mutating routes — minutes of work, and genuinely effective.',
      '3. **A session layer in `src/middleware.ts`** — the real fix. Middleware already sees every request for rate limiting, so it is the natural place.',
      '⚠️ **Option 2 is not a substitute for option 3.** The proxy is a lock on the door of a house with no walls — anything that reaches the app directly, including another process on the same box, bypasses it entirely.',
    ],
  },
  {
    title: 'Three credential types, and which one goes where',
    category: 'Security',
    status: 'published',
    excerpt:
      'A Payload API key, a Medusa publishable key and a Medusa admin JWT. They are not interchangeable, and one of them is not a secret at all.',
    tags: ['security', 'auth', 'api-keys'],
    body: [
      'WordPress has essentially one credential model. This stack has three at once, and confusing them is a common source of both bugs and leaks.',
      '## The Payload API key ✅',
      'Header: `Authorization: users API-Key <key>` — the collection slug, a literal space, `API-Key`, then the key. **Not `Bearer`.** That format catches everyone once.',
      'It belongs to a **user**, so it carries that user\'s permissions. Here it is an admin, which is why the storefront can do anything.',
      '⚠️ **This is a real secret.** Server-side only, never in client code.',
      '## The Medusa publishable key ✅',
      'Header: `x-publishable-api-key`. Required on every `/store/*` call — omit it and you get **400, not 401**, which is confusing the first time.',
      '> This one is **not a secret**. It identifies which sales channel the request belongs to, so one Medusa can serve several storefronts. It is designed to be visible in a browser.',
      'Treating it as a secret causes needless architecture; treating the Payload key as non-secret causes an incident.',
      '## The Medusa admin JWT ✅',
      'Obtained from `POST /auth/user/emailpass`, sent as `Authorization: Bearer <token>`. Short-lived, for `/admin/*`.',
      '## Where they live',
      '⚠️ **The first two are stored in the databases**, not chosen by you. Setup generates them and writes them into `apps/storefront/.env`. A database reset invalidates both — which is why the storefront suddenly cannot reach either backend after a restore, and why `npm run postman:env` exists.',
      '## The rule',
      'Secrets live in the app that owns the backend relationship — Astro, server-side. The browser gets nothing except the publishable key, and only because it is meant to be public.',
    ],
  },
  {
    title: 'CORS, CSRF and the 403 that confuses everyone',
    category: 'Security',
    status: 'published',
    excerpt:
      'Two different protections people constantly conflate. One decides who may read your response; the other decides whether a request is genuine.',
    tags: ['security', 'cors', 'csrf'],
    body: [
      'These get mixed up because both produce errors in a browser and neither does anything from curl.',
      '## CORS answers "may this site read my response?"',
      'Enforced **by the browser**, not your server. The server says which origins may read a response, and the browser refuses to hand it over if the origin is not on the list.',
      'Medusa\'s `STORE_CORS`, `ADMIN_CORS` and `AUTH_CORS` are these lists. ⚠️ **They are `localhost` in the example env.** Shipping that means your production storefront cannot read its own API.',
      '> CORS is not a server-side protection. A non-browser client ignores it entirely, which is why curl works when your JavaScript does not.',
      '## CSRF answers "did the user mean to do this?"',
      'The attack: you are logged in here, you visit a malicious page, it submits a form to this app, and your cookies go along automatically.',
      'Astro\'s defence is `security.checkOrigin`, **on by default** for server-rendered sites. Non-GET requests whose `Origin` header does not match are rejected with 403.',
      '## The 403 you will hit',
      '✅ Try deleting a review from the terminal without an `Origin` header and you get **403 before any of your code runs**. Add `-H "Origin: http://localhost:4321"` and the identical request succeeds.',
      '⚠️ **It runs upstream of middleware**, so those rejected requests never appear in the request log. A tool can only log what reaches it — if your traffic graph and your users disagree about whether requests are arriving, that gap is where to look.',
      '## The WordPress comparison',
      'A nonce is per-user, per-action and time-limited, embedded in the form. An origin check is a header comparison. The nonce also protects against replay and confirms intent; the origin check does neither. It is cheaper and weaker, and for this app it is enough.',
    ],
  },
  {
    title: 'Security headers and a content security policy',
    category: 'Security',
    status: 'published',
    excerpt:
      'None are set in this repo. What each one does, and why CSP is both the most valuable and the easiest to get wrong.',
    tags: ['security', 'headers', 'csp'],
    body: [
      '📋 **Nothing in this repo sets security headers.** The middleware handles rate limiting and request logging and stops there. This is the map of what to add.',
      '## The cheap ones, worth adding immediately',
      '- `X-Content-Type-Options: nosniff` — stops browsers guessing a response is JavaScript when you said it was not',
      '- `Referrer-Policy: strict-origin-when-cross-origin` — stops full URLs leaking to third parties',
      '- `X-Frame-Options: DENY` — blocks clickjacking by framing',
      '- `Strict-Transport-Security` — forces HTTPS on return visits. ⚠️ Has a long memory; do not set a large `max-age` until TLS is definitely working',
      'All four are one-liners, either in `src/middleware.ts` or in the Caddy configuration.',
      '## Content Security Policy',
      'The valuable one, and the fiddly one. CSP tells the browser which sources of script, style and image it may load, so an injected `<script>` does not execute.',
      'This app is unusually well-placed for a strict policy: **it ships almost no JavaScript**. One island on one page, no third-party scripts, no analytics. A policy that would break a typical site is realistic here.',
      '⚠️ **`unsafe-inline` for styles is the thing you will reach for and should resist.** Astro scopes component styles by injecting them, so a naive strict policy breaks the design. Use hashes or nonces rather than opening it up.',
      '## Where this matters most',
      'The rich-text renderer converts a Lexical tree to HTML and inserts it with `set:html`. It escapes every text node and every link href, and that escaping is unit-tested — ✅ genuinely covered. CSP is the second line behind it, for the day something slips through.',
      '## How to check',
      'Point any security-header scanner at the deployed site. It will grade you honestly, and the first run is sobering.',
    ],
  },
  {
    title: 'Why this stack is hard to SQL-inject, and where it is not',
    category: 'Security',
    status: 'published',
    excerpt:
      'Both ORMs parameterise everything, so classic injection is largely closed. The holes that remain are the raw queries and the places user input shapes a query.',
    tags: ['security', 'sql-injection', 'validation'],
    body: [
      'Classic SQL injection is mostly solved here, and it is worth understanding why rather than assuming.',
      '## Why it is mostly closed',
      'Neither backend concatenates strings into SQL. Payload builds queries through Drizzle and Medusa through MikroORM, and both **parameterise** — values travel separately from the statement, so a value cannot become syntax.',
      'Payload\'s `where[title][contains]=x` is not a SQL fragment. It is a structured filter the query builder turns into a parameterised statement.',
      '## Where it is not closed',
      '**Raw queries.** Two places drop to raw SQL deliberately: Payload\'s `/api/schema` endpoint and Medusa\'s `/admin/schema`. ✅ Both query `information_schema` with no user input, which is exactly when raw SQL is reasonable.',
      '⚠️ **The rule: raw SQL is fine for questions no module owns. It is not fine anywhere user input reaches.** If you add a raw query, parameterise it, and do not build the string.',
      '**Identifiers, not values.** Parameterisation protects values, not table or column names. A sort parameter passed straight through as an identifier is injectable even with a parameterised query. Validate against an allowlist.',
      '## Validation is defence in depth, not the defence',
      'The repo validates twice — zod in the storefront, then Medusa\'s own validators. That is not redundancy to remove: the first buys a good error message, the second is the one that actually protects the database.',
      '✅ Medusa\'s validators use `.strict()`, so an unknown field is **rejected** rather than ignored. That is what stops a caller setting `status: "approved"` on a public review.',
      '## The more realistic risk',
      'Not injection — **authorisation**. An endpoint that trusts an id from the request without checking the caller may read it is a far more common hole than injection in a parameterised codebase. The storefront has no authentication at all, so every endpoint is in that category today.',
    ],
  },
  {
    title: 'Dependency risk, and keeping 1,900 packages honest',
    category: 'Security',
    status: 'published',
    excerpt:
      'Three node_modules trees, no automated scanning. What to run, what to automate, and why the lockfiles matter more than you think.',
    tags: ['security', 'dependencies', 'supply-chain'],
    body: [
      'WordPress has a plugin directory with a security team. npm has neither, and this stack installs a lot.',
      '## What you actually have',
      'Three independent dependency trees — one per app — each with its own `package-lock.json`. ✅ Those lockfiles are committed, which matters more than it sounds: they pin the **exact** resolved version of every transitive dependency, so your server installs what you tested rather than whatever is newest.',
      '## The minimum',
      '`npm audit` in each app. It is noisy and the severity ratings are often generous, but it finds the genuinely bad ones. Run it per app — the root `package.json` has no dependencies of its own.',
      '📋 **Nothing automates this today.** No Dependabot, no scheduled scan, no CI gate.',
      '## What to automate, in order of value',
      '1. **Dependabot or Renovate** on the repository. Opens PRs for updates, which turns upgrading from a project into a habit.',
      '2. **`npm audit` in CI**, failing on high and critical. Cheap, and stops a known-vulnerable dependency reaching production.',
      '3. **Pin the Node version** in CI to match production, so a build does not pass on 22 and fail on 20.',
      '## The version-drift trap',
      '⚠️ Installed here are Payload 3.88, Medusa 2.19 and Astro 7.2, while the official plugins publish at higher patch versions. Installing a plugin can pull a newer peer dependency than the core you are running. Match majors, and read the release notes rather than assuming semver protects you.',
      '## The supply-chain question',
      'Every dependency is code you run with your server\'s privileges. Before adding one, the four questions worth asking: does the framework already do this, how many transitive dependencies does it bring, when was it last updated, and what happens to you if it is abandoned.',
      '> A dependency you cannot replace in an afternoon is a dependency you should think about for more than an afternoon.',
    ],
  },
]
