import type { Guide } from './types'

/** Testing & Quality — 5 guides. */
export const testing: Guide[] = [
  {
    title: 'What this repo actually tests, and what it does not',
    category: 'Testing & Quality',
    status: 'published',
    excerpt:
      'Twenty unit tests, one integration test and 104 API assertions. An honest inventory, including the large areas nothing covers.',
    tags: ['testing', 'vitest', 'quality'],
    body: [
      'Start by knowing what exists, because the gaps are more interesting than the coverage.',
      '## What runs today ✅',
      '- **20 unit tests** in vitest, covering the Lexical-to-HTML converter and the rate limiter',
      '- **One integration test** — the compensation test, which runs a real workflow against a real database',
      '- **104 API assertions** across 49 requests, through newman',
      '- **Type checking** across all three apps',
      '`npm test` runs the first two; `npm run postman:test` the third.',
      '## Why those two units and not others',
      'They are the two pieces of genuinely tricky pure logic. The Lexical converter walks a tree and must escape HTML correctly — ✅ XSS escaping is explicitly tested. The rate limiter implements a sliding window, where off-by-one errors are easy and invisible.',
      '> Everything else in the repo is mostly orchestration — fetch, transform, render. That is better covered by integration tests than by unit tests with heavy mocking.',
      '## The compensation test is the valuable one',
      'It creates a review normally, then forces a failure in the link step, and asserts the database is unchanged — 11 rows before, 11 after, no orphan, not even a soft-deleted one. It exits non-zero on regression.',
      '✅ It has caught a real one: swapping a hard delete for a soft delete in a compensation handler made it go red immediately.',
      '## What nothing covers 🚫',
      '- Access-control rules — nothing asserts a draft is invisible anonymously',
      '- The Astro Actions, including the form-parsing traps',
      '- Any page rendering',
      '- The BFF translation layer, where PATCH becomes POST',
      '- Failure modes — what the dashboard does when a backend is down',
      '## The honest summary',
      'The tests that exist are good and test the right things. There are not many of them, and the largest untested surface is the one most likely to break: the glue between three services.',
    ],
  },
  {
    title: 'Why the compensation test is an integration test, not a unit test',
    category: 'Testing & Quality',
    status: 'published',
    excerpt:
      'It needs a real database, a real workflow engine and a real link table. Mocking those would test the mocks instead of the behaviour.',
    tags: ['testing', 'integration', 'workflows'],
    body: [
      'The single most valuable test in this repo does not run in vitest and does not mock anything. That is deliberate.',
      '## What it asserts',
      'That a failed workflow leaves **nothing** behind. It:',
      '1. Runs the create-review workflow normally and checks the row and the link row both exist',
      '2. Runs it again with a deliberate failure injected into the link step',
      '3. Asserts the failure reaches the caller',
      '4. Asserts the review count is unchanged, the link count is unchanged, and the rolled-back row does not exist even as a soft delete',
      '## Why mocking would defeat it',
      'The behaviour under test is an **interaction**: the orchestrator runs compensation handlers in reverse when a later step throws. Mock the database and you assert that your mock recorded a delete — not that the row is gone.',
      '> A test that mocks the thing it is testing passes when the real thing is broken.',
      'Step 4 is the point, and only a real database can answer it.',
      '## The failure is injected, not simulated',
      '✅ There is a real environment variable read at execution time inside the link step. Set it and that step throws. Nothing else in the test knows the difference — the workflow engine sees an ordinary failure and does exactly what it would in production.',
      'That is a nice pattern generally: make the failure path reachable from outside rather than reachable only by rewriting code.',
      '## What it costs',
      'It needs Postgres and Redis running, so it is slower than a unit test and cannot run in isolation. That is the trade for testing something true.',
      '**Reach for an integration test when** the behaviour only exists in the interaction — transactions, rollbacks, cascades, cross-service calls.',
      '**Reach for a unit test when** the logic is pure and the inputs are easy to construct.',
    ],
  },
  {
    title: 'Testing against a real database without wrecking your data',
    category: 'Testing & Quality',
    status: 'published',
    excerpt:
      'The compensation test runs against your development database and cleans up after itself. That approach has limits, and here is where they are.',
    tags: ['testing', 'database', 'fixtures'],
    body: [
      'Integration tests need data, and data is where test suites become unreliable.',
      '## What this repo does ✅',
      'The compensation test runs against the **development database**, creates what it needs, and cleans up. It works because it is one test, it is careful, and it asserts on counts relative to the start rather than absolute values.',
      '⚠️ **It does not generalise.** Ten tests doing this will interfere with each other, and a test that fails halfway leaves residue that breaks the next run.',
      '## The three strategies, cheapest first',
      '**1. Relative assertions.** Never assert "there are 11 reviews". Assert "there is one more than before". Survives a dirty database and parallel work. This is what the compensation test does.',
      '**2. A transaction per test, rolled back.** Fast and perfectly isolated — but it does not work when the code under test manages its own transactions, which workflow engines do.',
      '**3. A separate test database, reset per run.** The honest answer for a real suite. Slower, completely isolated, and it needs the schema created before each run.',
      '## Fixtures',
      'The seed scripts are already a fixture system — ✅ idempotent, versioned, and they produce a known state. A test database could reuse them directly rather than inventing a parallel mechanism.',
      '⚠️ **Do not let tests depend on seed *content*.** Asserting "the first post is titled X" breaks the day the seed changes — which, in this repo, it has repeatedly. Assert on shape and on relative change.',
      '## The thing to avoid',
      '> Tests that pass on a fresh database and fail on yours are worse than no tests, because the team learns to ignore red.',
      'If a test only works against clean data, make that explicit and let it reset — rather than leaving it fragile and blaming the person whose local database has an extra row.',
    ],
  },
  {
    title: 'The API test suite, and the two false failures it produces',
    category: 'Testing & Quality',
    status: 'published',
    excerpt:
      'Forty-nine requests and 104 assertions through newman, including ten deliberate failures. Both of its flaky modes are environmental, not real.',
    tags: ['testing', 'postman', 'api'],
    body: [
      '✅ **`npm run postman:test` is real and runs today** — 49 requests, 104 assertions, across all three services.',
      '## What makes it good',
      '**Ten of the requests are negative cases**, and they are the point. It asserts that a request without a publishable key returns 400, that a public caller cannot set a review to approved, that an unknown field is rejected, that a draft is 404 anonymously, and that a DELETE without an `Origin` header is refused.',
      '> Testing that the right thing fails is more valuable than testing that the right thing succeeds, because the success path is what you exercise by hand anyway.',
      '## It is data-independent',
      '✅ It captures ids at runtime — the first product, the post it just created — rather than hard-coding them. That is why it survived a complete replacement of the seed data without a single edit.',
      'Worth copying. A test suite that breaks when content changes is a test suite people stop running.',
      '## False failure one: the rate limiter',
      '⚠️ **Three runs inside a minute will fail.** The suite makes 49 requests against a 120-per-60-second limit, so the third run trips it and the failures look like broken assertions.',
      'Leave 60 seconds between runs. I have been caught by this more than once and briefly believed I had broken something.',
      '## False failure two: account lockout',
      '⚠️ Payload locks a user after repeated failed logins. Running the suite repeatedly while debugging an auth problem can lock the admin account, and then **every** subsequent run fails on login with a message that does not obviously say "locked".',
      'Clearing `login_attempts` and `lock_until` on the users row fixes it.',
      '## Where it should run',
      '📋 Nowhere automated. It is a manual command. The highest-value change to this repo\'s testing is running these three commands in CI on every pull request — see the CI gates guide.',
    ],
  },
  {
    title: 'The CI pipeline this repo does not have',
    category: 'Testing & Quality',
    status: 'published',
    excerpt:
      'Everything needed to gate a pull request already exists as npm scripts. Nothing runs them automatically, which makes them optional in practice.',
    tags: ['testing', 'ci', 'automation'],
    body: [
      '🚫 **There is no CI.** No workflow file, no pipeline, no automated anything. The deployment chapter names this as a gap and moves on; this is what closing it looks like.',
      '## You already have the gate',
      'The commands exist and are reliable:',
      '- `npm run typecheck` — all three apps',
      '- `npm test` — unit plus compensation',
      '- `npm run postman:test` — the API suite',
      '✅ All three pass today. The only missing piece is something running them without being asked.',
      '## Why that matters more than it sounds',
      '> A check that someone has to remember to run is a check that is optional, and optional checks are skipped exactly when you are in a hurry — which is when you most need them.',
      '## The minimum worth building',
      'On every pull request into `development`: install, typecheck, unit test. Those need no services and finish in under a minute.',
      '## The complication',
      '⚠️ **The integration and API tests need the whole stack running** — Postgres, Redis, all three services, and a seeded database. That means the CI job has to do what `npm run setup` does, which is a real piece of work.',
      'A pragmatic split: typecheck and unit tests on every PR, the full suite nightly or before a promotion to `main`.',
      '## A trap specific to this repo',
      '⚠️ Running the API suite more than twice in a minute trips the rate limiter and fails for a reason that has nothing to do with your change. A CI job that retries on failure will make it worse, not better. Either raise the limit for the test environment or run the suite once.',
      '## The order I would build it',
      '1. Typecheck and unit tests on PRs — an afternoon, and immediately useful',
      '2. `npm audit` failing on high and critical',
      '3. The full integration suite on a schedule, once the service setup is scripted',
      '4. Build verification, so a PR that breaks the Payload build is caught before deploy day rather than on it',
    ],
  },
]
